const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const {MajorityRoom}=require('./majority'),{CommunityStore}=require('./community');
function setup(n=3,start=true){const r=new MajorityRoom('T','test',()=>0);for(let i=0;i<n;i++)r.add('P'+i);if(start)r.start();return r;}
function ask(r,type='blank'){r.act(r.presenterId,'ask',{type,prompt:'早餐想到什麼？',options:type==='blank'?[]:['A','B']});}
function answers(r,a){a.forEach((answer,i)=>r.act(r.players[i].id,'answer',{answer}));if(r.phase==='review')r.act(r.host,'score');}
test('blank largest group at exactly a third scores +2 and penalizes only presenter',()=>{let r=setup(6);ask(r);answers(r,['A','A','B','C','D','E']);assert.deepEqual(r.players.map(p=>p.score),[1,2,0,0,0,0]);assert.equal(r.result.presenterPenalty,1);assert.equal(r.result.points,2);assert.equal(r.result.gains[r.host],1);r=setup(5);ask(r);answers(r,['A','A','B','C','D']);assert.deepEqual(r.players.map(p=>p.score),[2,2,0,0,0]);assert.equal(r.result.presenterPenalty,0);r=setup(3);ask(r);answers(r,['A','B','C']);assert.deepEqual(r.players.map(p=>p.score),[-1,0,0]);});
test('blank merge happens before third threshold; ties never award points',()=>{const r=setup(6);ask(r);['A','B','C','D','E','F'].forEach((answer,i)=>r.act(r.players[i].id,'answer',{answer}));r.act(r.host,'merge',{from:r.groups[1].id,to:r.groups[0].id});r.act(r.host,'merge',{from:r.groups[1].id,to:r.groups[0].id});r.act(r.host,'score');assert.equal(r.result.presenterPenalty,0);assert.deepEqual(r.players.map(p=>p.score),[2,2,2,0,0,0]);const tie=setup(6);ask(tie);answers(tie,['A','A','B','B','C','C']);assert.deepEqual(tie.players.map(p=>p.score),[-1,0,0,0,0,0]);});
test('withdraw restores hidden editing before all submit, cannot withdraw after reveal or deadline',()=>{const r=setup();ask(r,'two');r.act(r.host,'answer',{answer:0});r.act(r.host,'withdraw');assert.equal(r.view(r.host).ownAnswer,null);assert.equal(r.view(r.players[1].id).answers,undefined);r.act(r.host,'answer',{answer:1});r.act(r.players[1].id,'answer',{answer:1});r.act(r.players[2].id,'answer',{answer:0});assert.equal(r.phase,'reveal');assert.throws(()=>r.act(r.host,'withdraw'));const late=setup();ask(late);late.act(late.host,'answer',{answer:'A'});late.deadline=Date.now()-1;assert.throws(()=>late.act(late.host,'withdraw'));assert.equal(late.phase,'review');assert.equal(late.answers[late.host],'A');});
test('prepared questions are private, FIFO, removed only by owner and rotate to their author',()=>{const r=setup(3,false),a=r.players[1].id,b=r.players[2].id;r.act(a,'enqueue',{type:'two',prompt:'秘密第一題',options:['A','B']});r.act(b,'enqueue',{type:'blank',prompt:'秘密第二題'});assert.equal(r.view(r.host).ownQueue.length,0);assert.ok(!JSON.stringify(r.view(r.host)).includes('秘密'));assert.throws(()=>r.act(r.host,'unqueue',{queueId:r.questionQueue[0].id}));r.start();assert.equal(r.phase,'answering');assert.equal(r.presenterId,a);assert.equal(r.question.prompt,'秘密第一題');answers(r,[0,0,1]);r.act(r.host,'next');assert.equal(r.presenterId,b);assert.equal(r.question.prompt,'秘密第二題');assert.equal(r.view(r.host).queueCount,0);});
test('prepared custom validation and per-player capacity; reaction whitelist and cooldown',()=>{const r=setup();assert.throws(()=>r.act(r.host,'enqueue',{type:'two',prompt:'X',options:['Ａ','a']}));for(let i=0;i<5;i++)r.act(r.host,'enqueue',{type:'blank',prompt:'Q'+i});assert.throws(()=>r.act(r.host,'enqueue',{type:'blank',prompt:'extra'}));r.act(r.host,'react',{emoji:'😂'});assert.equal(r.view(r.players[1].id).reactions[0].emoji,'😂');assert.throws(()=>r.act(r.host,'react',{emoji:'😂'}));assert.throws(()=>r.act(r.players[1].id,'react',{emoji:'<script>'}));});
test('community persists issues, questions and shared avatars; hides owner credentials and rejects invalid uploads',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bga-community-'));try{const c=new CommunityStore(dir);const issue=c.issue({game:'majority',title:'Test',body:'Issue',name:'P'});assert.ok(issue.owner);assert.equal(c.issues()[0].owner,undefined);assert.throws(()=>c.updateIssue({id:issue.id,action:'status',owner:'wrong',status:'closed'}));c.updateIssue({id:issue.id,action:'comment',name:'B',body:'Hi'});c.updateIssue({id:issue.id,action:'status',owner:issue.owner,status:'closed'});const q=c.question({type:'two',prompt:'Question',options:['A','B'],pack:'Test',name:'P'});assert.ok(q.id.startsWith('shared-'));assert.throws(()=>c.upload({image:'data:image/svg+xml;base64,AAA='}));assert.throws(()=>c.upload({image:'data:image/png;base64,'+Buffer.from('not a real image').toString('base64')}));const a=c.upload({image:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aY1cAAAAASUVORK5CYII=',name:'P'});assert.equal(c.avatar(a.id),a.url);const reread=new CommunityStore(dir);assert.equal(reread.issues()[0].status,'closed');assert.equal(reread.issues()[0].comments.length,1);assert.equal(reread.data.questions[0].id,q.id);assert.equal(reread.avatars().length,1);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
