const {test}=require('node:test');const assert=require('node:assert/strict');const {Room,evaluate,compare}=require('./engine');
test('hand rankings: wheel, flush, full house, royal flush',()=>{assert.deepEqual(evaluate([12,0,1,2,3]),[8,5]);assert.equal(evaluate([12,25,38,11,24,0,1])[0],6);assert.deepEqual(evaluate([8,9,10,11,12,15,21]),[8,14]);assert.ok(compare(evaluate([8,9,10,11,12]),evaluate([12,25,38,51,0]))>0);});
test('heads up blinds, private cards and check/call full hand',()=>{const r=new Room('T','T'),a=r.add('A'),b=r.add('B');r.start();assert.equal(r.turn,0);assert.equal(a.bet,10);assert.equal(b.bet,20);assert.deepEqual(r.view(a.id).players[1].cards,[null,null]);assert.throws(()=>r.act(b.id,'check'));let count=0;while(r.phase!=='showdown'&&count++<30){let p=r.players[r.turn];r.act(p.id,p.bet<r.currentBet?'call':'check');}assert.equal(r.phase,'showdown');assert.equal(r.board.length,5);assert.equal(a.stack+b.stack,4000);});
test('side pots return unmatched excess and conserve chips',()=>{const r=new Room('T','T');let a=r.add('A'),b=r.add('B'),c=r.add('C');a.stack=100;b.stack=300;c.stack=1000;r.start();for(let n=0;r.phase!=='showdown'&&n<10;n++)r.act(r.players[r.turn].id,'allin');assert.equal(r.phase,'showdown');assert.equal(r.players.reduce((s,p)=>s+p.stack,0),1400);assert.ok(c.stack>=700);});
test('short all-in does not reopen betting',()=>{const r=new Room('T','T');const a=r.add('A'),b=r.add('B'),c=r.add('C');b.stack=130;r.start();r.act(a.id,'raise',100);r.act(b.id,'allin');r.act(c.id,'call');assert.equal(r.turn,0);assert.equal(r.canRaise(a),false);assert.throws(()=>r.act(a.id,'raise',250));r.act(a.id,'call');assert.equal(r.phase,'flop');});
test('random actions across many hands preserve chips and finish',()=>{for(let run=0;run<100;run++){const r=new Room('T','T');for(let i=0;i<6;i++)r.add('p'+i);r.start();for(let n=0;r.phase!=='showdown'&&n<200;n++){const p=r.players[r.turn];assert.ok(p);const options=['call','fold',...(r.canRaise(p)?['allin']:[])];const action=options[Math.floor(Math.random()*options.length)];r.act(p.id,action);}assert.equal(r.phase,'showdown');assert.equal(r.players.reduce((s,p)=>s+p.stack,0),12000);}});
test('deterministic main and side pot winners',()=>{const r=new Room('T','T');const a=r.add('A'),b=r.add('B'),c=r.add('C');r.board=[0,18,33,9,42];a.cards=[12,25];b.cards=[11,37];c.cards=[10,23];for(const [p,total]of [[a,100],[b,300],[c,1000]]){p.total=total;p.stack=0;p.folded=false;}r.settle();assert.deepEqual([a.stack,b.stack,c.stack],[300,400,700]);});
test('community royal flush splits pot with odd chip after dealer',()=>{const r=new Room('T','T');const a=r.add('A'),b=r.add('B'),c=r.add('C');r.board=[8,9,10,11,12];r.button=0;for(const p of r.players){p.cards=[13,14];p.total=5;p.stack=0;p.folded=false;}c.folded=true;r.settle();assert.deepEqual([a.stack,b.stack,c.stack],[7,8,0]);});
test('a street transition preserves first player and joining waits for next hand',()=>{const r=new Room('T','T');const a=r.add('A'),b=r.add('B');r.start();r.act(a.id,'call');r.act(b.id,'check');assert.equal(r.phase,'flop');assert.equal(r.turn,1);const c=r.add('C');assert.equal(c.folded,true);assert.deepEqual(c.cards,[]);assert.equal(JSON.stringify(r.view(a.id)).includes(b.secret),false);});
