const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {GiftRoom}=require('./src/games/gift');
const {createApp}=require('./src/app');
const {openDatabase}=require('./src/db/index');
const {createAuth}=require('./src/auth/index');

test('gift rounds keep choices secret, score both tracks, and finish only after a complete round',()=>{
 const room=new GiftRoom('ABC123','送禮達人',()=>0);
 const players=['阿星','小河','雨點'].map(name=>room.add(name));
 assert.throws(()=>room.add('機器人',true),/真人/);
 room.configure(players[0].id,{target:8});room.start();
 assert.equal(room.gifts.length,4);
 const runRound=()=>{
  const [a,b,c]=players.map(player=>player.id),[g0,g1,g2,g3]=room.gifts.map(gift=>gift.id);
  room.act(a,'give',{assignments:{[b]:g0,[c]:g1}});
  assert.equal(room.view(b).ownAssignments,null);
  assert.equal(room.view(b).result,null);
  assert.throws(()=>room.act(b,'give',{assignments:{[a]:g0,[c]:g0}}),/不同/);
  room.act(b,'give',{assignments:{[a]:g0,[c]:g2}});
  room.act(c,'give',{assignments:{[a]:g1,[b]:g2}});
  assert.equal(room.phase,'wishing');
  room.act(a,'wish',{ranking:{great:g0,good:g1,ok:g2,noWay:g3}});
  assert.equal(room.view(b).ownRanking,null);
  assert.equal(room.view(b).result,null);
  room.act(b,'wish',{ranking:{great:g0,good:g2,ok:g1,noWay:g3}});
  room.act(c,'wish',{ranking:{great:g2,good:g1,ok:g0,noWay:g3}});
 };
 runRound();
 assert.equal(room.phase,'reveal');
 assert.deepEqual(room.players.map(player=>[player.giveScore,player.getScore]),[[5,5],[6,5],[4,5]]);
 assert.equal(room.view(players[0].id).result.entries.length,6);
 assert.throws(()=>room.act(players[1].id,'next'),/房主/);
 const previousGifts=new Set(room.gifts.map(gift=>gift.id));
 room.act(players[0].id,'next');
 assert.equal(room.round,2);
 assert.equal(room.view(players[0].id).result,null);
 assert.ok(room.gifts.every(gift=>!previousGifts.has(gift.id)));
 runRound();
 assert.equal(room.phase,'finished');
 assert.deepEqual(room.winner.ids,players.map(player=>player.id));
 assert.ok(room.players.every(player=>player.giveScore===8&&player.getScore===8));
 room.start();assert.equal(room.phase,'giving');assert.equal(room.round,1);
});

test('invalid input cannot leak choices or alter a locked round; kicking a player cannot stall it',()=>{
 const room=new GiftRoom('DEF456','朋友局',()=>0);
 const [host,friend,other,leaving]=['甲','乙','丙','丁'].map(name=>room.add(name));
 room.start();
 const [g0,g1,g2,g3,g4]=room.gifts.map(gift=>gift.id);
 assert.throws(()=>room.act(host.id,'give',{assignments:{[friend.id]:g0}}),/每位朋友/);
 room.act(host.id,'give',{assignments:{[friend.id]:g0,[other.id]:g1,[leaving.id]:g2}});
 assert.throws(()=>room.act(host.id,'give',{assignments:{[friend.id]:g0,[other.id]:g1,[leaving.id]:g2}}),/鎖定/);
 room.act(friend.id,'give',{assignments:{[host.id]:g4,[other.id]:g2,[leaving.id]:g3}});
 room.act(other.id,'give',{assignments:{[host.id]:g1,[friend.id]:g3,[leaving.id]:g4}});
 room.kick(host.id,leaving.id);
 assert.equal(room.phase,'wishing');
 assert.throws(()=>room.add('晚到'),/已開始/);
 assert.throws(()=>room.act(host.id,'wish',{ranking:{great:g0,good:g0,ok:g1,noWay:g2}}),/四件不同/);
 const ranking={great:g0,good:g1,ok:g2,noWay:g3};
 for(const player of [host,friend,other])room.act(player.id,'wish',{ranking});
 assert.equal(room.phase,'reveal');
 assert.equal(room.result.entries.length,6);
 assert.ok(room.result.entries.every(entry=>entry.giverId!==leaving.id&&entry.recipientId!==leaving.id));
 assert.ok(room.result.entries.some(entry=>entry.points===-1));
 assert.ok(room.result.entries.some(entry=>entry.points===-4));
});

test('authenticated players can create, join and reconnect to a gift room without seeing hidden choices',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'bga-gift-'));
 const config={port:0,host:'127.0.0.1',historyDir:path.join(root,'history'),communityDir:path.join(root,'community'),dbFile:path.join(root,'app.sqlite')};
 const db=openDatabase(config.dbFile);await createAuth(db).bootstrap('giftadmin','test-password-123');db.close();
 const app=createApp(config);
 try{
  const {port}=await app.listen(),base=`http://127.0.0.1:${port}`;
  const post=async(route,cookie,data)=>{const response=await fetch(base+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify(data)});return {status:response.status,body:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]};};
  const host=(await post('auth/login',null,{username:'giftadmin',password:'test-password-123'})).cookie;
  const register=async username=>{const invite=await post('admin/invites',host,{days:1});return (await post('auth/register',null,{username,displayName:username,password:'test-password-123',confirmPassword:'test-password-123',invite:invite.body.code})).cookie;};
  const friend=await register('giftfriend'),other=await register('giftother'),outsider=await register('giftoutside');
  const created=await post('create',host,{type:'gift',roomName:'送禮測試'});
  assert.equal(created.status,200);assert.equal(created.body.type,'gift');
  const code=created.body.code;
  const unauthorized=await fetch(base+'/gift/'+code,{redirect:'manual'});
  assert.equal(unauthorized.status,302);
  assert.equal((await fetch(base+'/gift/'+code,{headers:{Cookie:host}})).status,200);
  assert.equal((await fetch(base+'/gift.js',{headers:{Cookie:host}})).status,200);
  assert.equal((await post('join',friend,{code})).status,200);
  assert.equal((await post('join',other,{code})).status,200);
  const getState=async (cookie=host)=>(await (await fetch(base+'/api/state?code='+code,{headers:{Cookie:cookie}})).json());
  let state=await getState();assert.equal(state.phase,'waiting');
  assert.equal((await post('start',friend,{code})).status,403);
  assert.equal((await post('start',host,{code})).status,200);
  state=await getState();assert.equal(state.gifts.length,4);
  const [a,b,c]=state.players.map(player=>player.id),[g0,g1,g2,g3]=state.gifts.map(gift=>gift.id);
  assert.equal((await post('join',outsider,{code})).status,400);
  const visible=(await (await fetch(base+'/api/rooms',{headers:{Cookie:outsider}})).json()).rooms.find(room=>room.code===code);
  assert.equal(visible.joinable,false);
  assert.equal((await post('action',host,{code,action:'give',assignments:{[b]:g0,[c]:g1}})).status,200);
  state=await getState(friend);assert.equal(state.ownAssignments,null);assert.equal(state.result,null);
  assert.deepEqual(state.submittedIds,[a]);
  assert.equal((await post('reconnect',friend,{code})).body.reconnected,true);
  await post('action',friend,{code,action:'give',assignments:{[a]:g0,[c]:g2}});
  await post('action',other,{code,action:'give',assignments:{[a]:g1,[b]:g2}});
  const rank=(great,good,ok,noWay)=>({great,good,ok,noWay});
  await post('action',host,{code,action:'wish',ranking:rank(g0,g1,g2,g3)});
  assert.equal((await getState(other)).ownRanking,null);
  await post('action',friend,{code,action:'wish',ranking:rank(g0,g2,g1,g3)});
  await post('action',other,{code,action:'wish',ranking:rank(g2,g1,g0,g3)});
  state=await getState();assert.equal(state.phase,'reveal');assert.equal(state.result.entries.length,6);
  const history=await (await fetch(base+'/api/history',{headers:{Cookie:host}})).json();
  assert.equal(history[0].type,'gift');assert.equal(history[0].status,'playing');
 }finally{await app.close();fs.rmSync(root,{recursive:true,force:true});}
});
