const {test}=require('node:test');const assert=require('node:assert/strict');const {ThunderRoom,neighbor}=require('./src/games/thunder');
function room(n=2){const r=new ThunderRoom('TEST','測試');for(let i=0;i<n;i++)r.add('P'+i,true);r.start();return r;}
function clear(r){for(const t of r.tiles)for(const row of t.cells)for(const c of row){c.kind='R';delete c.hazard;}}
test('setup and hidden state',()=>{const r=room(4);assert.equal(r.cars.length,12);assert.equal(r.tiles.length,3);assert.ok(r.players.every(p=>p.dice.length===4));const view=r.view(r.players[0].id);assert.ok(view.tiles.flatMap(t=>t.cells.flat()).filter(c=>c.hazard).every(c=>c.hazard.kind==='unknown'));assert.ok(!JSON.stringify(view).includes(r.players[1].secret));assert.throws(()=>r.add('late'));assert.throws(()=>r.act(r.players[(r.turn+1)%4].id,'begin',{}));});
test('forward and reverse neighbors are reversible',()=>{for(let x=0;x<6;x++)for(let d=0;d<6;d++){const v=neighbor(x,4,d);if(v.x>=0&&v.x<6)assert.deepEqual(neighbor(v.x,v.y,[5,4,3,2,1,0][d]),{x,y:4});}});
test('one die, full movement, first-round no shooting',()=>{const r=room();clear(r);const p=r.players[r.turn],c=r.available(p)[0];p.dice[0].value=3;r.act(p.id,'begin',{car:c.id,die:0});r.act(p.id,'move',{x:2,y:0});r.act(p.id,'move',{x:2,y:1});r.act(p.id,'move',{x:2,y:2});assert.equal(c.y,2);assert.equal(r.phase,'assign');assert.equal(p.turns,1);assert.equal(c.moved,true);assert.equal(p.dice[0].used,true);});
test('command validation is atomic and nitro consumes distinct die',()=>{const r=room();const p=r.players[r.turn],c=r.available(p)[0];p.dice[0].value=5;p.dice[1].value=2;assert.throws(()=>r.act(p.id,'begin',{car:c.id,die:0,command:'nitro',commandDie:0}));assert.equal(p.dice[0].used,false);r.act(p.id,'begin',{car:c.id,die:0,command:'nitro',commandDie:1});assert.equal(r.active.remaining,7);assert.equal(p.dice.filter(d=>d.used).length,2);});
test('numeric-string dice cannot reuse a movement die as command',()=>{const r=room(),p=r.players[r.turn],c=r.available(p)[0];p.dice[0].value=2;assert.throws(()=>r.act(p.id,'begin',{car:c.id,die:0,command:'nitro',commandDie:'0'}));assert.equal(p.dice[0].used,false);});
test('revealed mud costs two, not three; revealed road preserves bonus eligibility',()=>{const r=room();clear(r);const p=r.players[r.turn],c=r.available(p)[0];c.x=2;c.y=3;p.dice[0].value=4;const cell=r.terrain(2,4);cell.hazard={kind:'mud',face:true};r.act(p.id,'begin',{car:c.id,die:0});r.act(p.id,'move',{x:2,y:4});assert.equal(r.active.remaining,2);});
test('road bonus is optional; coasting unavailable with unused operable car',()=>{const r=room();clear(r);const p=r.players[r.turn],c=r.available(p)[0];c.x=2;c.y=4;p.dice[0].value=1;r.act(p.id,'begin',{car:c.id,die:0});r.act(p.id,'move',{x:2,y:5});assert.equal(r.phase,'bonus');r.act(p.id,'bonus',{use:false});assert.ok(!r.available(p).includes(c));});
test('airstrike has legal placement and end-turn elimination',()=>{const r=room();clear(r);const p=r.players[r.turn],c=r.available(p)[0];p.dice[0].value=1;r.act(p.id,'begin',{car:c.id,die:0,command:'airstrike',commandDie:1});assert.equal(r.phase,'airplace');r.act(p.id,'airplace',{x:2,y:0});assert.equal(r.phase,'move');r.act(p.id,'move',{x:2,y:0});assert.equal(c.dead,true);});
test('larger vehicle gets collision choice, rejected for other player',()=>{const r=room();clear(r);const p=r.players[r.turn],c=r.available(p).find(c=>c.size===2),target=r.cars.find(c=>c.owner!==p.id&&c.size===0);target.x=2;target.y=0;p.dice[0].value=1;r.act(p.id,'begin',{car:c.id,die:0});r.act(p.id,'move',{x:2,y:0});assert.ok(r.pending);assert.equal(r.actor(),p.id);assert.throws(()=>r.act(target.owner,'slam',{reroll:true}));r.act(p.id,'slam',{reroll:false});assert.ok(!r.pending);assert.ok(c.dead||target.dead||c.x!==target.x||c.y!==target.y);});
test('two-player fifth tile places finish and rear cars are removed',()=>{const r=room();clear(r);for(const c of r.cars){c.x=c.size+1;c.y=20;}r.advanceBoard();assert.equal(r.finishAt,null);r.advanceBoard();assert.equal(r.finishAt,40);r.moveEffect({id:r.cars[0].id,x:2,y:40});assert.equal(r.phase,'finished');assert.equal(r.winner.id,r.cars[0].owner);});
test('repair restores an inoperable car and refunds one damage token',()=>{const r=room();const p=r.players[r.turn],cars=r.cars.filter(c=>c.owner===p.id);cars[1].damage=['dent','dent'];p.dice[1].value=6;r.act(p.id,'begin',{car:cars[0].id,die:0,command:'repair',commandDie:1,repairCar:cars[1].id});assert.equal(cars[1].damage.length,1);assert.equal(r.operable(cars[1]),true);});
test('automated full matches terminate without invalid state',()=>{for(let match=0;match<30;match++){const r=room(match%3+2);for(let step=0;r.phase!=='finished'&&step<5000;step++){r.auto();assert.ok(r.cars.every(c=>c.damage.length<=2));if(!r.pending)assert.ok(r.players[r.turn]);}assert.equal(r.phase,'finished',JSON.stringify({phase:r.phase,round:r.round}));assert.ok(r.winner);}});
