const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),net=require('node:net'),http=require('node:http'),crypto=require('node:crypto'),{spawn}=require('node:child_process'),{openDatabase}=require('./src/db/index'),{createAuth}=require('./src/auth/index');
test('HTTP community and majority integration: avatar sharing, issues, library, queue privacy, withdrawals and scoring archive',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bga-web-'));const testDb=openDatabase(path.join(dir,'app.sqlite'));await createAuth(testDb).bootstrap('testadmin','test-password-123');testDb.close();const probe=net.createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));
const remoteIssues=[];let remoteCommentId=1;
const github=http.createServer(async(request,response)=>{let body='';for await(const chunk of request)body+=chunk;const payload=body?JSON.parse(body):{};let result;
if(request.method==='POST'&&request.url==='/repos/stanley021039/BGA/issues'){result={number:remoteIssues.length+1,html_url:'https://github.com/stanley021039/BGA/issues/'+(remoteIssues.length+1),body:payload.body,state:'open'};remoteIssues.push(result);}
else if(request.method==='GET'&&request.url.startsWith('/repos/stanley021039/BGA/issues?'))result=remoteIssues;
else if(request.method==='POST'&&/\/issues\/\d+\/comments$/.test(request.url))result={id:remoteCommentId++,body:payload.body};
else {response.writeHead(404);return response.end('{}');}
response.setHeader('Content-Type','application/json');response.end(JSON.stringify(result));});
await new Promise(resolve=>github.listen(0,'127.0.0.1',resolve));
const child=spawn(process.execPath,[path.join(__dirname,'server.js')],{env:{...process.env,PORT:String(port),PUBLIC_URL:'http://example.test:'+port,HISTORY_DIR:path.join(dir,'history'),COMMUNITY_DIR:path.join(dir,'community'),DB_FILE:path.join(dir,'app.sqlite'),GITHUB_TOKEN:'test-token',GITHUB_API_BASE:'http://127.0.0.1:'+github.address().port},stdio:'pipe'});let stderr='';child.stderr.on('data',b=>stderr+=b);const base='http://127.0.0.1:'+port;let cookie='';const api=async(route,data,player)=>{const res=await fetch(base+'/api/'+route,{method:data?'POST':'GET',headers:{'Content-Type':'application/json',Cookie:player?.cookie||cookie},body:data?JSON.stringify(data):undefined});const out=await res.json();assert.equal(res.status,200,JSON.stringify(out));return route==='community/issues'&&data?out.issue:out;};try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server timeout '+stderr)),5000);child.stdout.on('data',()=>{clearTimeout(timer);resolve();});child.on('error',reject);});const login=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'testadmin',password:'test-password-123'})});assert.equal(login.status,200);cookie=login.headers.get('set-cookie').split(';')[0];for(const route of ['/','/community','/majority','/avatar-picker.js','/majority-social.js'])assert.equal((await fetch(base+route,{headers:{Cookie:cookie}})).status,200);
const info=await api('info');assert.equal(info.preferred,'http://example.test:'+port);assert.equal(info.addresses[0],info.preferred);const avatar=await api('community/avatars',{name:'測試頭像',image:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aY1cAAAAASUVORK5CYII='});assert.equal((await fetch(base+avatar.url)).headers.get('content-type'),'image/png');const issue=await api('community/issues',{game:'majority',title:'新建議',body:'完整內容',name:'朋友',submissionId:crypto.randomUUID()});await api('community/issues',{id:issue.id,action:'comment',name:'另一人',body:'回覆',submissionId:crypto.randomUUID()});const listed=await api('community/issues');assert.equal(listed[0].owner,undefined);assert.equal(listed[0].comments.length,1);
const question=await api('community/questions',{type:'blank',topic:'daily',prompt:'測試早餐',pack:'朋友早餐題庫',name:'朋友'});const bank=await api('community/questions');assert.ok(bank.questions.length>=289);assert.ok(bank.topics.length>=12);
const register=async username=>{const invite=await api('admin/invites',{days:1});const response=await fetch(base+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,displayName:username,password:'test-password-123',confirmPassword:'test-password-123',invite:invite.code})});assert.equal(response.status,200);return response.headers.get('set-cookie').split(';')[0];};
const otherCookie=await register('friend1'),thirdCookie=await register('friend2');
const host=await api('create',{type:'majority',name:'P0',avatar:avatar.id});const other=await api('join',{code:host.code,name:'P1',avatar:avatar.id},{cookie:otherCookie}),third=await api('join',{code:host.code,name:'P2'},{cookie:thirdCookie});other.cookie=otherCookie;third.cookie=thirdCookie;const players=[host,other,third];const act=(p,action,data={})=>api('action',{code:host.code,action,...data},p);await api('settings',{code:host.code,rounds:3},host);await act(other,'enqueue',{questionId:question.id});let view=await api('state?code='+host.code,undefined,host);assert.equal(view.queueCount,1);assert.ok(!JSON.stringify(view).includes('測試早餐'));assert.equal(view.players[1].avatar,avatar.url);await api('start',{code:host.code},host);view=await api('state?code='+host.code,undefined,host);assert.equal(view.phase,'answering');assert.equal(view.presenterId,view.players[1].id);await act(host,'answer',{answer:'蛋餅'});view=await act(host,'withdraw');assert.equal(view.ownAnswer,null);await act(host,'react',{emoji:'😂'});assert.equal((await api('state?code='+host.code,undefined,other)).reactions[0].emoji,'😂');for(const [i,p]of players.entries())await act(p,'answer',{answer:i===2?'飯糰':'蛋餅'});view=await act(host,'score');assert.deepEqual(view.players.map(p=>p.score),[2,2,0]);assert.equal(view.result.presenterPenalty,0);for(let round=2;round<=3;round++){view=await act(host,'next');const presenter=players[view.players.findIndex(p=>p.id===view.presenterId)];await act(presenter,'ask',{type:'two',prompt:'測試選擇',options:['A','B']});for(const [i,p]of players.entries())await act(p,'answer',{answer:i===2?1:0});}view=await act(host,'next');assert.equal(view.phase,'finished');assert.deepEqual(view.players.map(p=>p.score),[4,4,0]);const history=await api('history');assert.equal(history[0].status,'finished');const archive=await api('history/'+history[0].id);const raw=JSON.stringify(archive);for(const p of players)assert.equal(p.token,undefined);assert.ok(!raw.includes(cookie.split('=')[1]));assert.ok(raw.includes('withdraw'));assert.ok(raw.includes('enqueue'));assert.ok(raw.includes('presenterPenalty'));
const kickRoom=await api('create',{type:'majority',name:'KickHost'});
await api('join',{code:kickRoom.code,name:'Victim'},{cookie:otherCookie});
await api('join',{code:kickRoom.code,name:'Peer'},{cookie:thirdCookie});
const kickState=await api('state?code='+kickRoom.code),victimId=kickState.players[1].id;
const kickRequest=(actor,body)=>fetch(base+'/api/kick',{method:'POST',headers:{'Content-Type':'application/json',Cookie:actor},body:JSON.stringify({code:kickRoom.code,playerId:victimId,...body})});
assert.equal((await kickRequest(thirdCookie,{confirmed:true})).status,400);
assert.equal((await kickRequest(cookie,{})).status,400);
assert.equal((await kickRequest(cookie,{confirmed:true,playerId:kickState.me})).status,400);
assert.equal((await kickRequest(cookie,{confirmed:true})).status,200);
for(const route of ['state?code='+kickRoom.code,'join']){const response=await fetch(base+'/api/'+route,{method:route==='join'?'POST':'GET',headers:{'Content-Type':'application/json',Cookie:otherCookie},body:route==='join'?JSON.stringify({code:kickRoom.code}):undefined});assert.equal(response.status,403);assert.equal((await response.json()).code,'KICKED');}
for(const type of ['poker','thunder']){const p=await api('create',{type,name:'Avatar',avatar:avatar.id});assert.equal((await api('state?code='+p.code,undefined,p)).players[0].avatar,avatar.url);}
}finally{child.kill();await new Promise(resolve=>{if(child.exitCode!==null)resolve();else child.once('exit',resolve);});await new Promise(resolve=>github.close(resolve));fs.rmSync(dir,{recursive:true,force:true});}}, {timeout:20000});
