'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {appFixture}=require('./helpers/app-fixture.cjs'),{createAuth}=require('../src/auth');
test('bluff HTTP auth, private roles, all rounds, history, rejoin and static routing',async t=>{
 const {base}=await appFixture(t,{config:{achievementPurpose:'test',marketAutomationEnabled:false},seed:db=>createAuth(db).bootstrap('bluff_owner','synthetic-bluff-password')});
 async function post(route,cookie,data={},status=200){const res=await fetch(base+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify(data)}),s=await res.json();assert.equal(res.status,status,JSON.stringify(s));return {s,cookie:res.headers.get('set-cookie')?.split(';')[0]};}
 const owner=(await post('auth/login',null,{username:'bluff_owner',password:'synthetic-bluff-password'})).cookie,cookies=[owner];for(let i=1;i<3;i++){const invite=(await post('admin/invites',owner)).s.code;cookies.push((await post('auth/register',null,{username:'bluff_peer'+i,password:'synthetic-bluff-password',confirmPassword:'synthetic-bluff-password',invite})).cookie);}
 await post('create',null,{type:'bluff'},401);await post('create',owner,{type:'bluff',roleSeconds:11},400);const {code}=(await post('create',owner,{type:'bluff',roleSeconds:10})).s;for(const c of cookies.slice(1))await post('join',c,{code});
 await post('settings',cookies[1],{code,levels:[1]},403);await post('settings',owner,{code,levels:[1,2,3]});await post('start',cookies[1],{code},403);
 let s=(await post('start',owner,{code})).s;assert.equal(s.options.roleSeconds,10);assert.ok(s.deadline-s.serverNow<=10000&&s.deadline-s.serverNow>9000);
 const state=async c=>(await (await fetch(base+'/api/state?code='+code,{headers:{Cookie:c}})).json());
 for(let round=0;round<3;round++){const views=await Promise.all(cookies.map(state));assert.equal(views.filter(s=>s.secretAnswer).length,1);for(const v of views.filter(v=>v.myRole!=='honest')){assert.equal(v.secretAnswer,null);assert.equal(v.roles,undefined);assert.equal(v.prompt.answer,undefined);}for(const c of cookies)await post('action',c,{code,action:'ready',roundId:s.roundId,requestId:randomUUID()});const thinker=views.findIndex(v=>v.myRole==='thinker'),honest=views.find(v=>v.myRole==='honest').me;for(let i=0;i<3;i++)if(i!==thinker)await post('action',cookies[i],{code,action:'spoken',roundId:s.roundId,requestId:randomUUID()});s=(await post('action',cookies[thinker],{code,action:'guess',targetId:honest,confirmed:true,roundId:s.roundId,requestId:randomUUID()})).s;if(round<2){await post('reconnect',owner,{code});s=(await post('action',owner,{code,action:'next',roundId:s.roundId,requestId:randomUUID()})).s;}}
 assert.equal(s.phase,'finished');const list=await (await fetch(base+'/api/history',{headers:{Cookie:owner}})).json(),match=list.find(m=>m.type==='bluff');assert.equal(match.status,'finished');const history=await (await fetch(base+'/api/history/'+match.id,{headers:{Cookie:owner}})).json();assert.match(history[0].engine.source,/class BluffRoom/);assert.match(history[0].engine.catalog,/NOAA/);assert.equal(history.filter(r=>r.kind==='result').at(-1).after.results.length,3);
 for(const path of ['/bluff','/bluff/'+code]){assert.equal((await fetch(base+path,{redirect:'manual'})).status,302);assert.equal((await fetch(base+path,{headers:{Cookie:owner}})).status,200);}
 for(const path of ['/bluff.js','/bluff.css'])assert.equal((await fetch(base+path)).status,200);
 const rooms=await (await fetch(base+'/api/rooms',{headers:{Cookie:owner}})).json();assert.equal(rooms.rooms.find(r=>r.code===code).maxPlayers,9);
});
