const {test}=require('node:test');const assert=require('node:assert/strict');
const {ThunderRoom,neighbor,FIRE_DIE}=require('../src/games/thunder');
const {settleDice,autoStep}=require('./helpers/race-dice');
function setup(expansion=true){const r=new ThunderRoom('TEST','擴充測試');const p=r.add('A'),q=r.add('B');r.configure(p.id,{devilsRun:expansion});r.start();settleDice(r);for(const t of r.tiles)for(const row of t.cells)for(const c of row){c.kind='R';delete c.hazard;}r.turn=0;r.round=2;for(const c of r.cars){c.x=c.size*2;c.y=c.owner===p.id?3:18;}const c=r.cars[0];p.dice=[{value:3},{value:2},{value:6},{value:1}].map(d=>({...d,used:false}));return {r,p,q,c};}
function move(r,p,c,point,die=0){r.act(p.id,'begin',{car:c.id,die});settleDice(r);r.act(p.id,'move',point);settleDice(r);}
test('expansion setting is host-only, boolean, locked in play and shared',()=>{const r=new ThunderRoom('T','T'),a=r.add('A'),b=r.add('B');assert.throws(()=>r.configure(b.id,{devilsRun:true}));assert.throws(()=>r.configure(a.id,{devilsRun:'true'}));r.configure(a.id,{devilsRun:true});assert.equal(r.view(b.id).options.devilsRun,true);r.start();assert.throws(()=>r.configure(a.id,{devilsRun:false}));assert.equal(r.tileDeck.length+r.tiles.length,10);assert.ok(r.damageDeck.includes('fire'));});
test('base mode contains no expansion tiles, damage or hazards',()=>{const {r}=setup(false);assert.equal(r.tileDeck.length+r.tiles.length,5);assert.ok(r.tiles.every(t=>t.map<5));assert.ok(!r.damageDeck.includes('fire'));assert.ok(r.hazardDeck.every(h=>['road','oil','mud','mine','wreck'].includes(h)));});
test('toxic goo stops normal movement',()=>{const {r,p,c}=setup();r.terrain(0,4).kind='G';move(r,p,c,{x:0,y:4});assert.equal(c.y,4);assert.equal(p.turns,1);});
test('glass keeps diagonal direction and spends no extra move',()=>{const {r,p,c}=setup();r.terrain(1,3).kind='V';move(r,p,c,{x:1,y:3});assert.deepEqual({x:c.x,y:c.y},neighbor(1,3,2));assert.equal(r.active.remaining,2);});
test('ramp jumps straight forward, skips intermediate obstacles and stops',()=>{const {r,p,c}=setup();r.terrain(0,4).kind='J';r.terrain(0,5).kind='X';r.roll=()=>3;move(r,p,c,{x:0,y:4});assert.equal(c.y,7);assert.equal(c.dead,false);assert.equal(p.turns,1);});
test('ramp side entry eliminates car',()=>{const {r,p,c}=setup();r.terrain(1,3).kind='J';move(r,p,c,{x:1,y:3});assert.equal(c.dead,true);});
test('landing on a second ramp chains jumps in same direction',()=>{const {r,p,c}=setup();r.terrain(0,4).kind='J';r.terrain(0,6).kind='J';r.roll=()=>2;move(r,p,c,{x:0,y:4});assert.equal(c.y,8);assert.equal(c.dead,false);});
test('salt qualifies off-road movement for road bonus, but never coasting',()=>{const {r,p,c}=setup();r.terrain(0,3).kind='O';r.terrain(0,4).kind='S';p.dice[0].value=1;move(r,p,c,{x:0,y:4});assert.equal(r.phase,'bonus');const other=setup();other.r.cars.filter(v=>v.owner===other.p.id).forEach(v=>v.moved=true);other.r.terrain(0,4).kind='S';move(other.r,other.p,other.c,{x:0,y:4});assert.equal(other.p.turns,1);});
test('fire terrain ignites without damage or immediate fire roll; no stacking',()=>{const {r,p,c}=setup();r.terrain(0,4).kind='F';r.roll=()=>{throw Error('must not roll on entering fire');};move(r,p,c,{x:0,y:4});assert.equal(c.burning,true);assert.equal(c.damage.length,0);r.ignite(c);assert.equal(c.burning,true);assert.equal(r.active.remaining,2);});
test('fire die triggers before movement, including coast, and covers all results',()=>{for(const face of [1,2,'out','eliminate']){const {r,p,c}=setup();r.cars.filter(v=>v.owner===p.id).forEach(v=>v.moved=true);c.burning=true;r.roll=faces=>{assert.equal(faces,FIRE_DIE);return face;};r.act(p.id,'begin',{car:c.id,die:0});settleDice(r);if(typeof face==='number')assert.equal(r.active.remaining,1+face);else if(face==='out'){assert.equal(c.burning,false);assert.equal(r.active.remaining,1);}else assert.equal(c.dead,true);}});
test('airstrike resolves before active car fire die',()=>{const {r,p,c}=setup();c.burning=true;let rolls=0;r.roll=()=>{rolls++;return 'out';};r.act(p.id,'begin',{car:c.id,die:0,command:'airstrike',commandDie:1});assert.equal(rolls,0);r.act(p.id,'airplace',{x:5,y:22});assert.equal(rolls,0);settleDice(r);assert.equal(rolls,1);assert.equal(c.burning,false);});
test('repair does not extinguish an operable burning car',()=>{const {r,p,c}=setup();const target=r.cars[1];target.burning=true;target.damage=['fire'];r.act(p.id,'begin',{car:c.id,die:0,command:'repair',commandDie:2,repairCar:target.id});assert.equal(target.damage.length,0);assert.equal(target.burning,true);});
test('second damage resolves before inoperability, then extinguishes fire',()=>{const {r,c}=setup();c.burning=true;c.damage=['dent'];r.damageDeck=['skid1'];r.damage({id:c.id});assert.equal(c.damage.length,1);assert.equal(r.operable(c),true);r.drain();assert.equal(c.y,4);assert.equal(c.damage.length,2);assert.equal(c.burning,false);});
test('eliminated car returns unresolved damage token after landing effect',()=>{const {r,c}=setup();r.terrain(0,4).kind='X';r.damageDeck=['skid1'];r.damage({id:c.id});r.drain();assert.equal(c.dead,true);assert.deepEqual(r.damageDeck,['skid1']);assert.equal(c.damage.length,0);assert.equal(c.pendingDamage,0);});
test('revealed pit uses shooting die once; future entry is impassable',()=>{const {r,p,c}=setup();r.terrain(0,4).hazard={kind:'pit',face:false};r.roll=()=> 'L';move(r,p,c,{x:0,y:4});assert.equal(c.dead,false);assert.equal(r.terrain(0,4).hazard.face,true);c.x=0;c.y=3;r.moveEffect({id:c.id,x:0,y:4});assert.equal(c.dead,true);});
test('pit match eliminates revealing car',()=>{const {r,p,c}=setup();r.terrain(0,4).hazard={kind:'pit',face:false};r.roll=()=> 'SM';move(r,p,c,{x:0,y:4});assert.equal(c.dead,true);});
test('quake translates cars together without slamming into vacated spaces',()=>{const {r,c}=setup();const follower=r.cars[1];follower.x=0;follower.y=2;r.quake(1);assert.equal(c.y,4);assert.equal(follower.y,3);r.drain();assert.equal(r.pending,null);assert.equal(c.y,4);assert.equal(follower.y,3);});
test('sand worm eliminates all rear ties using staggered board positions',()=>{const {r,p,c}=setup();const tied=r.cars[1],ahead=r.cars[2];tied.x=2;tied.y=3;ahead.x=1;ahead.y=3;r.terrain(4,10).hazard={kind:'worm',face:false};r.moveEffect({id:r.cars[3].id,x:4,y:10,direction:1});assert.equal(c.dead,true);assert.equal(tied.dead,true);assert.equal(ahead.dead,false);});
test('dazed charges newly revealed mud two movement points',()=>{const {r,c}=setup();r.terrain(0,4).hazard={kind:'mud',face:false};r.rng=()=>1;r.roll=faces=>typeof faces[0]==='number'?3:faces[1];r.damageDeck=['dazed'];r.damage({id:c.id});r.drain();settleDice(r);assert.equal(c.y,5);});
test('stale collision event does not process a later landing twice',()=>{const {r,c}=setup();c.moveSeq=2;r.collision({id:c.id,x:0,y:2,seq:1});assert.equal(r.pending,null);});
test('100 mixed expansion matches complete and keep unique settled positions',()=>{for(let game=0;game<100;game++){const r=new ThunderRoom('T','T');for(let p=0;p<2+game%3;p++)r.add('P'+p,true);r.configure(r.host,{devilsRun:true});r.start();for(let step=0;r.phase!=='finished'&&step<6000;step++){autoStep(r);assert.ok(r.cars.every(c=>c.damage.length+(c.pendingDamage||0)<=2));if(!r.pending&&!r.diceCheck&&!r.queue.length&&r.phase!=='finished'){const positions=r.cars.filter(c=>!c.dead&&c.x!==null).map(c=>c.x+','+c.y);assert.equal(new Set(positions).size,positions.length);}}assert.equal(r.phase,'finished');}});
