const {test}=require('node:test'),assert=require('node:assert/strict');
const {DrawGuessRoom,readEnding}=require('../src/games/draw-guess');
const {mediaHarness,mediaSnapshot,roomState,json}=require('./helpers/media-browser.cjs');
function draw(ending,n=3){const r=new DrawGuessRoom('ABCDEF','ending',()=>0),p=Array.from({length:n},(_,i)=>r.add('p'+i));r.options.ending=ending;r.start();return {r,p};}
test('score target finishes only after full reveal, preserves final result and awards',()=>{const {r,p}=draw({mode:'score',value:30});r.choose(r.presenterId,r.candidates[0].id);r.guess(p[1].id,r.question.title);assert.equal(r.phase,'drawing');assert.ok(p[1].score>=30);r.guess(p[2].id,r.question.title);assert.equal(r.phase,'finished');assert.ok(r.result.resultId);assert.equal(r.results.length,1);assert.match(r.winner.reason,/分數達標/);});
test('fixed total questions rotate beyond one circle, stop exactly and retain only recent eight gallery entries',()=>{const {r}=draw({mode:'rounds',value:12},2),artists=[];for(let i=0;i<12;i++){artists.push(r.presenterId);r.choose(r.presenterId,r.candidates[0].id);r.reveal();if(i<11){assert.equal(r.phase,'reveal');r.next(r.host);}}assert.equal(r.round,12);assert.equal(r.phase,'finished');assert.equal(artists[0],artists[2]);assert.equal(r.results.length,8);assert.equal(r.publicResults.size,8);});
test('ending validation and legacy default keep old one-circle flow',()=>{for(const value of [null,{},[],{mode:'rounds',value:0},{mode:'rounds',value:65},{mode:'score',value:9},{mode:'score',value:1001},{mode:'score',value:NaN},{mode:'rounds',value:1.5}])assert.throws(()=>readEnding(value),e=>e.code==='INVALID_DRAW_ENDING');const {r}=draw({mode:'rounds',value:null},2);for(let i=0;i<2;i++){r.choose(r.presenterId,r.candidates[0].id);r.reveal();assert.equal(r.phase,'reveal');r.next(r.host);}assert.equal(r.phase,'finished');assert.equal(r.round,2);});
test('score mode caps at 64 questions when nobody reaches target',()=>{const {r}=draw({mode:'score',value:1000},2);for(let i=0;i<64;i++){r.choose(r.presenterId,r.candidates[0].id);r.reveal();if(i<63)r.next(r.host);}assert.equal(r.phase,'finished');assert.match(r.winner.reason,/64/);assert.equal(r.results.length,8);});
test('minimizing video keeps player and playback during queue add; restore keeps same iframe',async()=>{let state=mediaSnapshot({playback:{state:'playing',anchorPositionSec:5,anchorServerMs:100000,rate:1}});const f=mediaHarness({fetchHandler:request=>request.route==='/api/music'?json({tracks:[]}):json(state)});await f.update(roomState(state));await f.click('mediaConsentAccept');const player=f.players[0];player.ready();await f.flushFrames();const iframe=player.iframe,controls=()=>player.calls.filter(([name])=>['play','pause','seek','cue','destroy'].includes(name)),calls=controls().length;await f.click('mediaClose');assert.equal(f.node('tableMedia').open,true);assert.equal(f.node('tableMedia').classList.contains('media-minimized'),true);assert.equal(player.destroyed,false);const d=f.node('tableMedia').getBoundingClientRect();f.node('mediaPlayer').rect={left:d.left+10,top:d.top+80,width:d.width-20,height:d.height-100};state={...state,revision:2,queue:[{id:'pending',type:'video',videoId:'bZb4Zj7MfK0',title:'下一段'}]};await f.update(roomState(state));await f.flushFrames();assert.equal(f.players.length,1);assert.equal(player.iframe,iframe);assert.equal(player.destroyed,false);assert.equal(controls().length,calls);await f.click('mediaRestore');assert.equal(f.node('tableMedia').classList.contains('media-minimized'),false);assert.equal(player.iframe,iframe);});
test('explicit close of the mini player and pagehide still stop local video',async()=>{const f=mediaHarness();await f.update(roomState());await f.click('mediaConsentAccept');const player=f.players[0];await f.click('mediaClose');await f.click('mediaClose');assert.equal(player.destroyed,true);assert.equal(f.node('tableMedia').open,false);f.window.dispatch('pagehide');assert.equal(f.node('mediaPlayer').children.length,0);});
test('mini queue entry keeps video visible, paused state stays paused and next video stays minimized',async()=>{let state=mediaSnapshot({playback:{state:'paused',anchorPositionSec:5,anchorServerMs:100000,rate:1}});const f=mediaHarness({fetchHandler:r=>r.route==='/api/music'?json({tracks:[]}):json(state)});await f.update(roomState(state));await f.click('mediaConsentAccept');const first=f.players[0];first.ready();await f.click('mediaClose');const d=f.node('tableMedia').getBoundingClientRect();f.node('mediaPlayer').rect={left:d.left+10,top:d.top+80,width:d.width-20,height:d.height-100};await f.click('mediaMiniQueue');assert.equal(first.destroyed,false);assert.equal(f.node('tableMediaPlaylist').open,true);const plays=first.calls.filter(([name])=>name==='play').length;state={...state,revision:2,queue:[{id:'queued',type:'video',videoId:'bZb4Zj7MfK0',title:'下一段'}]};await f.update(roomState(state));assert.equal(first.calls.filter(([name])=>name==='play').length,plays);await f.click('mediaPlaylistClose');state={...state,revision:3,playbackSessionId:'session-next',current:{...state.current,id:'next-video',videoId:'bZb4Zj7MfK0'}};await f.update(roomState(state));assert.equal(first.destroyed,true);assert.equal(f.players.length,2);assert.equal(f.node('tableMedia').classList.contains('media-minimized'),true);});
