const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {MajorityRoom}=require('../src/games/majority');const {TOPICS,QUESTIONS}=require('../src/games/majority-questions');const {openDatabase}=require('../src/db/index');const {AchievementStore}=require('../src/achievements/store');
function room(n=3){const r=new MajorityRoom('TEST','測試',()=>0);for(let i=0;i<n;i++)r.add('P'+i);r.start();return r;}
function ask(r,type='two'){r.act(r.presenterId,'ask',{type,prompt:'選什麼？',options:type==='three'?['A','B','C']:['A','B']});}
function answerAll(r,answers){answers.forEach((answer,i)=>r.act(r.players[i].id,'answer',{answer}));}
test('players, minimum and maximum, configuration and membership',()=>{const r=new MajorityRoom('T','T');const p=r.add('host');assert.throws(()=>r.start());r.add('two');assert.throws(()=>r.start());for(let i=2;i<12;i++)r.add('P'+i);assert.throws(()=>r.add('extra'));assert.throws(()=>r.configure(r.players[1].id,{rounds:3}));for(const rounds of [2,31,'3',3.5])assert.throws(()=>r.configure(p.id,{rounds}));r.configure(p.id,{rounds:3});r.start();assert.equal(r.roundLimit,3);assert.throws(()=>r.configure(p.id,{rounds:4}));assert.throws(()=>r.add('late'));assert.throws(()=>r.act('outsider','answer',{answer:0}));});
test('only presenter draws and asks; candidates stay private and ids must be offered',()=>{const r=room(),other=r.players[1].id;assert.throws(()=>r.act(other,'draw',{topic:TOPICS[0].id,type:'two'}));r.act(r.presenterId,'draw',{topic:TOPICS[0].id,type:'two'});assert.equal(r.candidates.length,3);assert.equal(r.view(other).candidates.length,0);assert.equal(r.view(r.presenterId).candidates.length,3);assert.throws(()=>r.act(other,'ask',{questionId:r.candidates[0].id}));assert.throws(()=>r.act(r.presenterId,'ask',{questionId:'invented'}));r.act(r.presenterId,'ask',{questionId:r.candidates[0].id});assert.equal(r.phase,'answering');});
test('candidate pools exhaust before reuse and reused cards are labelled',()=>{const r=room(),topic=TOPICS[0].id,pool=QUESTIONS.filter(q=>q.topic===topic&&q.type==='two'),seen=new Set();for(let i=0;i<Math.ceil(pool.length/3)+1;i++){r.act(r.presenterId,'draw',{topic,type:'two'});assert.equal(new Set(r.candidates.map(q=>q.id)).size,3);for(const q of r.candidates){if(seen.has(q.id))assert.equal(seen.size,pool.length);assert.equal(q.reused,seen.has(q.id));seen.add(q.id);}}});
test('host custom percentage shapes suggested questions without changing manual asking',()=>{const r=new MajorityRoom('MIX','混合題庫',()=>0),host=r.add('房主'),other=r.add('朋友');r.add('第三位');const topic=TOPICS[0].id;r.questionProvider=()=>Array.from({length:4},(_,index)=>({id:'shared-question-'+index,topic,type:'two',prompt:'投稿題'+index,options:['甲','乙']}));assert.throws(()=>r.configure(other.id,{rounds:3,customPercent:75}),/房主/);for(const value of ['75',10,-25,125])assert.throws(()=>r.configure(host.id,{rounds:3,customPercent:value}),/比例/);r.configure(host.id,{rounds:3,customPercent:75});assert.equal(r.view(other.id).options.customPercent,75);r.start();r.act(r.presenterId,'draw',{topic,type:'two'});assert.equal(r.candidates.filter(q=>q.id.startsWith('shared-')).length,2);assert.equal(new Set(r.candidates.map(q=>q.id)).size,3);assert.throws(()=>r.configure(host.id,{rounds:3,customPercent:0}),/遊戲中/);r.act(r.presenterId,'ask',{type:'two',prompt:'現場想出的題目',options:['甲','乙']});assert.equal(r.question.prompt,'現場想出的題目');
 const few=new MajorityRoom('FEW','少量投稿',()=>0),owner=few.add('甲');few.add('乙');few.add('丙');few.questionProvider=()=>[{id:'shared-only',topic,type:'two',prompt:'投稿題',options:['甲','乙']}];few.configure(owner.id,{rounds:3,customPercent:100});few.start();few.act(few.presenterId,'draw',{topic,type:'two'});assert.equal(few.candidates.filter(q=>q.id.startsWith('shared-')).length,1);assert.equal(new Set(few.candidates.map(q=>q.id)).size,3);few.act(few.presenterId,'draw',{topic,type:'two'});assert.equal(few.candidates.filter(q=>q.id.startsWith('shared-')).length,0);
});
test('question validation and locked answers protect phase and secrets',()=>{const r=room();for(const data of [{type:'two',prompt:'',options:['A','B']},{type:'two',prompt:'x'.repeat(161),options:['A','B']},{type:'three',prompt:'x',options:['A','B']},{type:'two',prompt:'x',options:['Ａ','a']}])assert.throws(()=>r.act(r.presenterId,'ask',data));ask(r);const id=r.players[0].id;for(const answer of [-1,2,'0',null])assert.throws(()=>r.act(id,'answer',{answer}));r.act(id,'answer',{answer:1});assert.throws(()=>r.act(id,'answer',{answer:0}));for(const p of r.players){const v=r.view(p.id);assert.equal(v.answers,undefined);assert.deepEqual(v.groups,[]);assert.equal(v.result,null);assert.equal(v.ownAnswer,p.id===id?1:null);assert.ok(!JSON.stringify(v).includes(p.secret));}answerAllRemaining(r,[1,0]);assert.equal(r.phase,'reveal');});
function answerAllRemaining(r,answers){answers.forEach((answer,i)=>r.act(r.players[i+1].id,'answer',{answer}));}
test('three choice plurality scores two of four; top ties and singleton answers score zero',()=>{let r=room(4);ask(r,'three');answerAll(r,[0,0,1,2]);assert.deepEqual(r.players.map(p=>p.score),[1,1,0,0]);assert.equal(r.result.groups.filter(g=>g.winner).length,1);assert.throws(()=>r.act(r.host,'score'));assert.deepEqual(r.players.map(p=>p.score),[1,1,0,0]);r=room(4);ask(r);answerAll(r,[0,1,0,1]);assert.ok(r.players.every(p=>p.score===0));r=room();ask(r,'three');answerAll(r,[0,1,2]);assert.ok(r.players.every(p=>p.score===0));});
test('blank answers remain hidden until review, normalization, merge, reset and score once',()=>{const r=room(4);ask(r,'blank');r.act(r.players[0].id,'answer',{answer:'  ＣＡＴ   cafe  '});const v=r.view(r.players[1].id);assert.ok(!JSON.stringify(v).includes('ＣＡＴ'));assert.equal(v.answers,undefined);assert.throws(()=>r.act(r.host,'score'));for(const answer of ['', 'x'.repeat(61),0])assert.throws(()=>r.act(r.players[1].id,'answer',{answer}));answerAllRemaining(r,['cat cafe','kitten','dog']);assert.equal(r.phase,'review');assert.equal(r.groups.length,3);assert.equal(r.groups[0].count,2);assert.equal(Object.keys(r.view(r.players[1].id).answers).length,4);assert.throws(()=>r.act(r.players[1].id,'merge',{from:r.groups[1].id,to:r.groups[0].id}));r.act(r.host,'merge',{from:r.groups[1].id,to:r.groups[0].id});assert.equal(r.groups[0].count,3);r.act(r.host,'resetGroups');assert.equal(r.groups[0].count,2);r.act(r.host,'merge',{from:r.groups[1].id,to:r.groups[0].id});r.act(r.host,'score');assert.deepEqual(r.players.map(p=>p.score),[2,2,2,0]);assert.throws(()=>r.act(r.host,'score'));assert.throws(()=>r.act(r.host,'merge',{from:'group-3',to:'group-1'}));});
test('rotation, pass recovery, round limit, final standings and restart',()=>{const r=room();assert.throws(()=>r.act(r.players[1].id,'pass'));const presenter=r.presenterId;r.act(r.host,'pass');assert.notEqual(r.presenterId,presenter);assert.equal(r.round,1);r.roundLimit=3;for(let round=1;round<=3;round++){const idx=r.players.findIndex(p=>p.id===r.presenterId);ask(r);answerAll(r,[0,0,1]);assert.equal(r.phase,'reveal');r.act(r.host,'next');if(round<3)assert.equal(r.presenterId,r.players[(idx+1)%3].id);}assert.equal(r.phase,'finished');assert.equal(r.results.length,3);assert.equal(r.winner.ids.length,2);r.configure(r.host,{rounds:4});r.start();assert.equal(r.round,1);assert.ok(r.players.every(p=>p.score===0));assert.equal(r.roundLimit,4);});
test('timeout never silently excludes offline players; missing answers score zero',()=>{const r=room();ask(r);r.players[2].lastSeen=0;r.act(r.players[0].id,'answer',{answer:0});r.act(r.players[1].id,'answer',{answer:0});r.auto();assert.equal(r.phase,'answering');r.deadline=Date.now()-1;r.auto();assert.equal(r.phase,'reveal');assert.deepEqual(r.players.map(p=>p.score),[1,1,0]);assert.deepEqual(r.result.missingIds,[r.players[2].id]);assert.equal(r.result.reason,'timeout');r.auto();assert.deepEqual(r.players.map(p=>p.score),[1,1,0]);});
test('host close handles empty and single answers; blank close requires review',()=>{for(const type of ['two','blank']){const r=room();ask(r,type);assert.throws(()=>r.act(r.players[1].id,'close'));r.act(r.host,'close');if(type==='blank'){assert.equal(r.phase,'review');r.act(r.host,'score');}assert.equal(r.phase,'reveal');assert.deepEqual(r.result.groups,[]);assert.deepEqual(r.players.map(p=>p.score),type==='blank'?[-1,0,0]:[0,0,0]);}const r=room();ask(r);r.act(r.host,'answer',{answer:0});r.act(r.host,'close');assert.ok(r.players.every(p=>p.score===0));});

test('first vote badge is private, settled, and idempotent across a second round',()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'bga-majority-achievement-'));
 try{
  const db=openDatabase(path.join(root,'app.sqlite')),store=new AchievementStore(db),r=new MajorityRoom('BADGE2','舉牌測試',()=>0),seats=new Map();
  for(const name of ['甲','乙','丙','丁']){
   const userId='user-'+name;
   db.prepare("INSERT INTO users(id,username,display_name,password_hash,role,created_at) VALUES(?,?,?,?,?,?)").run(userId,userId,name,'unused','member',new Date().toISOString());
   seats.set(userId,r.add(name).id);
  }
  r.start();ask(r,'three');
  const [a,b,c,d]=[...seats.values()];r.act(a,'answer',{answer:0});r.act(b,'answer',{answer:1});
  assert.deepEqual(store.awardMajorityRound(r,seats),[]);
  r.kick(a,d);r.act(c,'answer',{answer:2});
  assert.equal(r.phase,'reveal');assert.deepEqual(r.players.filter(player=>!player.kicked).map(player=>player.score),[0,0,0]);
  assert.equal(store.awardMajorityRound(r,seats).length,3);
  assert.deepEqual(store.awardMajorityRound(r,seats),[]);
  assert.equal(store.list('user-丁').achievements.find(item=>item.id==='majority-first-vote').unlockedAt,null);
  for(const name of ['甲','乙','丙']){assert.ok(store.list('user-'+name).achievements.find(item=>item.id==='majority-first-vote').unlockedAt);assert.ok(store.list('user-'+name).achievements.find(item=>item.id==='all-first-table').unlockedAt);}
  r.act(r.host,'next');ask(r,'two');r.participantIds.forEach((id,index)=>r.act(id,'answer',{answer:index===2?1:0}));
  assert.deepEqual(store.awardMajorityRound(r,seats),[]);
  db.close();
 }finally{fs.rmSync(root,{recursive:true,force:true});}
});
