const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {PNG}=require('pngjs'),{openDatabase}=require('../src/db'),{MarketImageStore}=require('../src/market/images');
test('five decorative anchor slots preserve original bucket, weekday and approval eligibility',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'curve-images-')),db=openDatabase(path.join(root,'db.sqlite')),admin={id:randomUUID()},owner={id:randomUUID()};t.after(()=>{db.close();fs.rmSync(root,{recursive:true,force:true});});for(const [i,u] of [admin,owner].entries())db.prepare('INSERT INTO users(id,username,display_name,password_hash,role,created_at) VALUES(?,?,?,?,?,?)').run(u.id,'curveimage'+i,'作者'+i,'test',i?'member':'admin','2026-10-08T00:00:00.000Z');
 const store=new MarketImageStore(db),png=new PNG({width:2,height:2});png.data.fill(255);const base64=PNG.sync.write(png).toString('base64'),byBucket={};
 for(const bucket of ['crash','fall','dip','rise','rally','surge']){const image=(await store.upload(owner,{requestId:randomUUID(),mime:'image/png',base64,buckets:[bucket],weekdays:[1]})).image;byBucket[bucket]=image;await store.approve(admin,{requestId:randomUUID(),confirmed:true,images:[{id:image.id,version:image.version}]});}
 const pending=(await store.upload(owner,{requestId:randomUUID(),mime:'image/png',base64,buckets:['dip','rise'],weekdays:[1]})).image;
 for(let n=0;n<30;n++){const d=store.draw(owner,{targetDate:'2026-10-12',layout:'curve-five'});assert.deepEqual(Object.keys(d.images),['crash','fall','center','rally','surge']);for(const bucket of ['crash','fall','rally','surge'])assert.equal(d.images[bucket].id,byBucket[bucket].id);assert.ok(['dip','rise'].some(b=>d.images.center.id===byBucket[b].id));assert.notEqual(d.images.center.id,pending.id);assert.equal(d.images.center.authorName,'作者1');assert.equal(d.images.center.status,'approved');assert.equal(d.images.center.buckets.length,1);}
 assert.ok(Object.values(store.draw(owner,{targetDate:'2026-10-13',layout:'curve-five'}).images).every(x=>x===null));assert.deepEqual(Object.keys(store.draw(owner,{targetDate:'2026-10-12'}).images),['crash','fall','dip','rise','rally','surge']);assert.throws(()=>store.draw(owner,{targetDate:'2026-10-12',layout:'untrusted'}),e=>e.code==='INVALID_IMAGE_LAYOUT');
});
