const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{randomUUID,createHash}=require('node:crypto');
const {openDatabase,SCHEMA_VERSION}=require('../src/db');
const {MarketStore,validateMarketDatabase}=require('../src/market/store');
const {MarketAutomationStore}=require('../src/market/automation-store');
const {validateDatabase}=require('../src/data/validation'),{run}=require('../src/data/transfer');
const {createApp}=require('../src/app'),{settings}=require('../src/config');
const C=require('../public/market-curve'),R=require('../public/market-rules');
const start=Date.parse('2026-10-08T07:00:00.000Z'),target='2026-10-12',cutoff=Date.parse(target+'T00:00:00+08:00'),after=Date.parse(target+'T14:00:00+08:00');
const req=()=>randomUUID(),code=c=>e=>e.code===c;
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'market-curve-')),file=path.join(root,'source','app.sqlite'),db=openDatabase(file);let now=start;
 const users=['admin','member','member'].map((role,i)=>({id:req(),role}));for(const [i,u] of users.entries())db.prepare('INSERT INTO users(id,username,display_name,password_hash,role,created_at) VALUES(?,?,?,?,?,?)').run(u.id,'curve'+i,'曲線玩家'+i,'scrypt:'+'0'.repeat(32)+':'+'0'.repeat(128),u.role,new Date(start).toISOString());
 const store=new MarketStore(db,()=>now),auto=new MarketAutomationStore(db,store,{clock:()=>now});t.after(()=>{try{db.close();}catch{}fs.rmSync(root,{recursive:true,force:true});});return {root,file,db,store,auto,users,clock:()=>now,setTime:n=>{now=n;}};}
const create=f=>f.store.create(f.users[0],{requestId:req(),targetDate:target,confirmed:true}).roundId;
const vote=(f,id,tick,user=f.users[1],revision=0)=>f.store.vote(user,{requestId:req(),roundId:id,forecastTick:tick,expectedRevision:revision});
const settle=(f,id,value,revision=0)=>f.store.settle(f.users[0],{requestId:req(),roundId:id,returnPct:value,expectedRevision:revision,reason:revision?'官方更正':'',confirmed:true});
function addClose(f,date,returnPct,fetchedAt=new Date(start-1000).toISOString(),review=0){
 const changeCents=Math.round(returnPct*10000),values={targetDate:date,closeCents:1000000+changeCents,changeCents,returnPct:returnPct.toFixed(2)},sourceUrl='https://openapi.twse.com.tw/v1/exchangeReport/MI_INDEX',evidence=[{url:sourceUrl,sha256:'a'.repeat(64),fetchedAt},{url:'https://openapi.twse.com.tw/v1/exchangeReport/FMTQIK',sha256:'b'.repeat(64),fetchedAt}];
 f.db.prepare('INSERT INTO market_daily_closes VALUES(?,?,?,?,?,?,?,?,NULL)').run(date,values.closeCents,changeCents,values.returnPct,JSON.stringify({sourceUrl,evidence,returnPctSource:'official-published'}),createHash('sha256').update(JSON.stringify(values)).digest('hex'),fetchedAt,review);
}
test('new rounds freeze trusted prior evidence before opening and never recalibrate after later history',t=>{
 const f=fixture(t);for(let i=1;i<=35;i++)addClose(f,new Date(start-i*86400000).toISOString().slice(0,10),(i%5-2)*0.5);
 addClose(f,'2026-10-08',9,new Date(start+1000).toISOString());addClose(f,'2026-10-09',9);f.db.prepare('UPDATE market_daily_closes SET review_required=1 WHERE target_date=?').run('2026-10-07');
 const id=create(f),row=f.store.round(id),r=JSON.parse(row.rules_json);assert.equal(r.version,3);assert.equal(r.frozenAt,row.created_at);assert.equal(r.observations.length,34);assert.ok(r.observations.every(o=>o.targetDate<'2026-10-08'));assert.ok(r.observations.every(o=>JSON.parse(o.evidence).length===2));
 const before=row.rules_json;addClose(f,'2026-08-01',3);vote(f,id,0);assert.equal(f.store.round(id).rules_json,before);assert.equal(validateMarketDatabase(f.db),true);
});
test('fallback prior is explicit; numeric ticks reject type/range/legacy mixing and preserve revisions',t=>{
 const f=fixture(t),id=create(f),r=JSON.parse(f.store.round(id).rules_json);assert.equal(r.scaleTau,2);assert.equal(r.observations.length,0);
 for(const tick of [undefined,null,'0',0.1,101,-101,NaN,Infinity])assert.throws(()=>vote(f,id,tick),code('INVALID_FORECAST'));
 assert.throws(()=>f.store.vote(f.users[1],{requestId:req(),roundId:id,forecastTick:0,optionId:'dip',expectedRevision:0}),code('INVALID_FORECAST'));
 const input={requestId:req(),roundId:id,forecastTick:0,expectedRevision:0};assert.equal(f.store.vote(f.users[1],input).revision,1);assert.equal(f.store.vote(f.users[1],input).replayed,true);assert.equal(vote(f,id,0,f.users[1],1).unchanged,true);assert.throws(()=>vote(f,id,10),code('STALE_VOTE'));assert.equal(vote(f,id,10,f.users[1],1).revision,2);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM market_votes').get().n,0);
});
test('numeric deadline and rollback clock preserve canonical prediction history',t=>{
 const f=fixture(t),id=create(f);vote(f,id,-100);f.setTime(start+5000);vote(f,id,100,f.users[1],1);f.setTime(start-1000);vote(f,id,0,f.users[1],2);const v=f.db.prepare('SELECT * FROM market_forecasts').get();assert.equal(v.updated_at,new Date(start+5000).toISOString());assert.equal(validateMarketDatabase(f.db),true);
 f.setTime(cutoff-1);vote(f,id,100,f.users[1],3);f.setTime(cutoff);assert.throws(()=>vote(f,id,0,f.users[1],4),code('VOTING_CLOSED'));
});
test('zero actual scores, fractional units reverse exactly and replay does not award twice',t=>{
 const f=fixture(t),id=create(f);vote(f,id,0);vote(f,id,100,f.users[2]);f.setTime(after);const preview=f.store.preview(f.users[0],{roundId:id,returnPct:0,expectedRevision:0});assert.deepEqual(preview.counts,{positive:1,negative:1,zero:0});
 const input={requestId:req(),roundId:id,returnPct:0,expectedRevision:0,confirmed:true};f.store.settle(f.users[0],input);assert.equal(f.store.settle(f.users[0],input).replayed,true);assert.equal(f.store.stats(f.users[1].id).score,29.329315);assert.equal(f.store.stats(f.users[2].id).score,-70.806978);
 const before=f.db.prepare("SELECT * FROM market_curve_ledger WHERE kind='award'").all();settle(f,id,10,1);for(const old of before){const rev=f.db.prepare("SELECT * FROM market_curve_ledger WHERE kind='reversal' AND user_id=?").get(old.user_id);assert.equal(rev.points_units,-old.points_units);assert.equal(rev.return_pct,old.return_pct);}
 assert.equal(f.store.stats(f.users[2].id).score,100);assert.equal(f.store.view(f.users[2]).rounds[0].result.points,100);assert.equal(validateMarketDatabase(f.db),true);
});
test('out-of-slider actual remains true value and all settlement paths use frozen curve',t=>{
 const f=fixture(t),id=create(f);vote(f,id,100);f.setTime(after);settle(f,id,13);assert.equal(f.store.round(id).return_pct,13);assert.equal(f.store.stats(f.users[1].id).score,32.464019);assert.notEqual(f.store.stats(f.users[1].id).score,100);settle(f,id,0,1);assert.equal(validateMarketDatabase(f.db),true);
});
test('failed correction rolls back reversal, awards, result revision and receipt together',t=>{
 const f=fixture(t),id=create(f);vote(f,id,0);f.setTime(after);settle(f,id,0);const before=f.store.view(f.users[1]);f.db.exec("CREATE TRIGGER curve_fail BEFORE INSERT ON market_curve_ledger WHEN NEW.kind='award' AND NEW.revision=2 BEGIN SELECT RAISE(ABORT,'injected'); END");assert.throws(()=>settle(f,id,10,1),/injected/);assert.deepEqual(f.store.view(f.users[1]).stats,before.stats);assert.equal(f.store.round(id).result_revision,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM market_curve_ledger').get().n,1);assert.equal(validateMarketDatabase(f.db),true);
});
test('legacy rule snapshots and zero-void scores coexist without conversion with numeric totals',t=>{
 const f=fixture(t),id=create(f),old=req(),rules=R.snapshot();f.db.prepare('INSERT INTO market_rounds(id,target_date,cutoff_at,settlement_after,rules_json,created_by,created_at) VALUES(?,?,?,?,?,?,?)').run(old,'2026-10-09',R.cutoffFor('2026-10-09'),R.settlementFor('2026-10-09'),JSON.stringify(rules),f.users[0].id,new Date(start).toISOString());f.store.vote(f.users[1],{requestId:req(),roundId:old,optionId:'rally',expectedRevision:0});vote(f,id,0);f.setTime(after);settle(f,old,2);settle(f,id,0);assert.equal(f.store.stats(f.users[1].id).score,34.329315);assert.equal(f.db.prepare('SELECT points FROM market_ledger').get().points,5);settle(f,old,0,1);assert.equal(f.store.stats(f.users[1].id).score,29.329315);assert.equal(f.store.round(old).rules_json,JSON.stringify(rules));assert.equal(validateMarketDatabase(f.db),true);
});
test('official automated settlement uses numeric snapshot and remains idempotent',t=>{
 const f=fixture(t),id=create(f);vote(f,id,0);f.setTime(after);const fetchedAt=new Date(after).toISOString(),sourceUrl='https://openapi.twse.com.tw/v1/exchangeReport/MI_INDEX',close={targetDate:target,returnPct:'0.00',closeCents:1000000,changeCents:0,sourceUrl,fetchedAt,evidence:[{url:sourceUrl,sha256:'a'.repeat(64),fetchedAt},{url:'https://openapi.twse.com.tw/v1/exchangeReport/FMTQIK',sha256:'b'.repeat(64),fetchedAt}]};assert.equal(f.auto.recordClose(close).settled,true);assert.equal(f.auto.recordClose(close).alreadySettled,true);assert.equal(f.store.stats(f.users[1].id).score,29.329315);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM market_curve_ledger').get().n,1);assert.equal(validateMarketDatabase(f.db),true);
});
test('schema18 backup restore retains exact numeric snapshot, forecast and correction units',async t=>{
 const f=fixture(t),id=create(f);vote(f,id,33);f.setTime(after);settle(f,id,0);settle(f,id,10,1);const tables=['market_rounds','market_forecasts','market_curve_ledger','market_settlements','market_requests'],before=Object.fromEntries(tables.map(n=>[n,f.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));assert.equal(validateDatabase(f.file).schemaVersion,18);f.db.close();
 const source={envId:'curve-fixture',dbFile:f.file,historyDir:path.join(f.root,'source','history'),communityDir:path.join(f.root,'source','community'),musicDir:path.join(f.root,'source','music')};for(const dir of [source.historyDir,source.communityDir,source.musicDir])fs.mkdirSync(dir,{recursive:true});const keyFile=path.join(f.root,'key'),bundleDir=path.join(f.root,'bundle');await run({action:'keygen',keyFile});await run({action:'export',source,sourceStopped:true,keyFile,outputDir:bundleDir});await run({action:'verify',bundleDir,keyFile});const restored=await run({action:'restore',bundleDir,keyFile,destinationDir:path.join(f.root,'restored'),destinationEnvId:'curve-restored',apply:true});const db=openDatabase(settings(restored.config).dbFile);try{for(const n of tables)assert.deepEqual(db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all(),before[n]);assert.equal(validateMarketDatabase(db),true);}finally{db.close();}
});
test('validator rejects damaged micro-awards and frozen reference before export',t=>{
 const f=fixture(t),id=create(f);vote(f,id,0);f.setTime(after);settle(f,id,0);f.db.exec("UPDATE market_curve_ledger SET points_units=points_units+1");assert.throws(()=>validateDatabase(f.file),code('INVALID_DATABASE'));f.db.exec("UPDATE market_curve_ledger SET points_units=points_units-1");const r=JSON.parse(f.store.round(id).rules_json);r.scaleTau=3;f.db.prepare('UPDATE market_rounds SET rules_json=? WHERE id=?').run(JSON.stringify(r),id);assert.throws(()=>validateDatabase(f.file),code('INVALID_DATABASE'));
});
test('two SQLite connections accept one forecast revision and replay one settlement atomically',async t=>{
 const f=fixture(t),id=create(f),{Worker}=require('node:worker_threads');
 async function race(operation,inputs,now){const barrier=new SharedArrayBuffer(4),workers=inputs.map(input=>new Worker(path.join(__dirname,'helpers/market-worker.cjs'),{workerData:{file:f.file,barrier,operation,userId:operation==='vote'?f.users[1].id:f.users[0].id,input,now}})),results=workers.map(worker=>new Promise((resolve,reject)=>{worker.on('message',m=>{if(!m.ready)resolve(m);});worker.on('error',reject);}));await Promise.all(workers.map(worker=>new Promise(resolve=>worker.once('message',resolve))));Atomics.store(new Int32Array(barrier),0,1);Atomics.notify(new Int32Array(barrier),0);return Promise.all(results);}
 const responses=await race('vote',[-50,50].map(forecastTick=>({requestId:req(),roundId:id,forecastTick,expectedRevision:0})),start);assert.equal(responses.filter(r=>r.ok).length,1);assert.equal(responses.find(r=>!r.ok).code,'STALE_VOTE');
 const input={requestId:req(),roundId:id,returnPct:0,expectedRevision:0,confirmed:true},settled=await race('settle',[input,input],after);assert.ok(settled.every(r=>r.ok));assert.equal(settled.filter(r=>r.result.replayed).length,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM market_curve_ledger').get().n,1);assert.equal(validateMarketDatabase(f.db),true);
});
test('HTTP numeric contract serves shared math, rejects unauthed writes and passes five-slot layout',async t=>{
 const f=fixture(t),tokens=['admin-curve-fixture','member-curve-fixture'];for(const [i,token] of tokens.entries())f.db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').run(createHash('sha256').update(token).digest('hex'),f.users[i].id,'2099-01-01T00:00:00.000Z');f.db.close();
 const app=createApp({...settings({DB_FILE:f.file,HISTORY_DIR:path.join(f.root,'history'),COMMUNITY_DIR:path.join(f.root,'community'),MUSIC_DIR:path.join(f.root,'music'),EXTERNAL_SIDE_EFFECTS_ENABLED:'false'}),port:0,host:'127.0.0.1',marketClock:f.clock,githubClient:{configured:false}});const address=await app.listen(),base='http://127.0.0.1:'+address.port;
 async function post(route,body,user=0){const response=await fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json',...(user===null?{}:{Cookie:'ah-session='+tokens[user]})},body:JSON.stringify(body)});return {status:response.status,body:await response.json()};}
 try{const script=await fetch(base+'/market-curve.js');assert.equal(script.status,200);assert.match(await script.text(),/scorePredictionUnits/);assert.equal((await post('/api/market/vote',{},null)).status,401);
 const made=await post('/api/admin/market/rounds',{requestId:req(),targetDate:target,confirmed:true});assert.equal(made.status,200);const roundId=made.body.roundId;assert.equal((await post('/api/market/vote',{requestId:req(),roundId,forecastTick:0,expectedRevision:0},1)).status,200);
 const draw=await post('/api/market/images/draw',{targetDate:target,layout:'curve-five'},1);assert.equal(draw.status,200);assert.deepEqual(Object.keys(draw.body.images),['crash','fall','center','rally','surge']);assert.equal(draw.body.layout,'curve-five');
 f.setTime(after);assert.equal((await post('/api/admin/market/settle',{requestId:req(),roundId,returnPct:0,expectedRevision:0,confirmed:true})).status,200);const state=await (await fetch(base+'/api/market',{headers:{Cookie:'ah-session='+tokens[1]}})).json();assert.equal(state.rounds[0].vote.forecastTick,0);assert.equal(state.rounds[0].result.points,29.329315);
 }finally{await app.close();}
});
test('genuine schema17 migration preserves all old rows and creates only empty numeric tables',t=>{
 const f=fixture(t),id=req(),rules=R.snapshot();f.db.prepare('INSERT INTO market_rounds(id,target_date,cutoff_at,settlement_after,rules_json,created_by,created_at) VALUES(?,?,?,?,?,?,?)').run(id,target,R.cutoffFor(target),R.settlementFor(target),JSON.stringify(rules),f.users[0].id,new Date(start).toISOString());f.store.vote(f.users[1],{requestId:req(),roundId:id,optionId:'rally',expectedRevision:0});f.setTime(after);settle(f,id,2);
 f.db.exec('DROP TABLE market_curve_ledger; DROP TABLE market_forecasts; PRAGMA user_version=17');const tables=f.db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map(r=>r.name),before=Object.fromEntries(tables.map(n=>[n,f.db.prepare('SELECT rowid,* FROM '+n+' ORDER BY rowid').all()]));assert.equal(validateDatabase(f.file).schemaVersion,17);f.db.close();const db=openDatabase(f.file);try{assert.equal(db.prepare('PRAGMA user_version').get().user_version,18);for(const n of tables)assert.deepEqual(db.prepare('SELECT rowid,* FROM '+n+' ORDER BY rowid').all(),before[n]);for(const n of ['market_forecasts','market_curve_ledger'])assert.equal(db.prepare('SELECT COUNT(*) n FROM '+n).get().n,0);assert.equal(validateMarketDatabase(db),true);}finally{db.close();}
});
for(const table of ['market_forecasts','market_curve_ledger'])test(`schema18 rejects missing ${table} before migration or export`,t=>{const f=fixture(t);f.db.exec('DROP TABLE '+table);assert.throws(()=>validateDatabase(f.file),code('INVALID_DATABASE'));f.db.close();assert.throws(()=>openDatabase(f.file),/curve schema/);});
test('schema18 partial migration failure rolls back to untouched schema17',t=>{
 const f=fixture(t);f.db.exec('DROP TABLE market_curve_ledger; DROP TABLE market_forecasts; PRAGMA user_version=17');const before=f.db.prepare('SELECT * FROM users ORDER BY id').all();f.db.close();const {DatabaseSync}=require('node:sqlite'),original=DatabaseSync.prototype.exec;let injected=false;
 const mock=t.mock.method(DatabaseSync.prototype,'exec',function(sql){if(!injected&&sql.includes('CREATE TABLE IF NOT EXISTS market_forecasts(')&&sql.includes('PRAGMA user_version=18')){injected=true;original.call(this,sql.split(';')[0]);throw Error('injected partial curve migration');}return original.call(this,sql);});
 assert.throws(()=>openDatabase(f.file),/injected partial/);mock.mock.restore();assert.equal(injected,true);const db=new DatabaseSync(f.file);try{assert.equal(db.prepare('PRAGMA user_version').get().user_version,17);assert.deepEqual(db.prepare('SELECT * FROM users ORDER BY id').all(),before);assert.equal(db.prepare("SELECT name FROM sqlite_master WHERE name IN ('market_forecasts','market_curve_ledger')").all().length,0);assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(),[]);}finally{db.close();}
});
