const {legacyMarketSchema,upgradedMarketRows,useLegacyRoundSnapshot}=require('./helpers/market-legacy-schema.cjs');
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {openDatabase,SCHEMA_VERSION}=require('../src/db'),{createAuth}=require('../src/auth'),{MarketStore,validateMarketDatabase}=require('../src/market/store'),R=require('../public/market-rules');
const {createApp}=require('../src/app'),{settings}=require('../src/config'),{run}=require('../src/data/transfer'),{validateDatabase}=require('../src/data/validation');
const {Worker}=require('node:worker_threads');
const {DatabaseSync}=require('node:sqlite'),{DrawWordStore}=require('../src/games/draw-guess-store'),{WORDS}=require('../src/games/draw-guess-words');
const {createClient,waitFor,deferred,makeTransport}=require('./helpers/market-client.cjs'),clientSource=fs.readFileSync(path.join(__dirname,'../public/market.js'),'utf8');
const start=Date.parse('2027-01-04T12:00:00Z'),target='2027-01-06',cutoff=Date.parse('2027-01-05T16:00:00Z'),after=Date.parse('2027-01-06T05:30:00Z');
const req=()=>randomUUID(),code=c=>e=>e.code===c,password='test-'+randomUUID();
async function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'bga-market-')),file=path.join(root,'source','app.sqlite');let time=start;const db=openDatabase(file),auth=createAuth(db),id=await auth.bootstrap('market_admin',password),admin=db.prepare('SELECT * FROM users WHERE id=?').get(id),response={setHeader(){}};
 const members=[];for(let i=0;i<2;i++)members.push(await auth.register({username:'market_member_'+i,displayName:'測試玩家 '+i,password,confirmPassword:password,invite:auth.createInvite(admin).code},response));
 const store=new MarketStore(db,()=>time);t.after(()=>{try{db.close();}catch{}fs.rmSync(root,{recursive:true,force:true,maxRetries:5});});return {root,file,db,auth,admin,members,store,clock:()=>time,setTime:n=>{time=n;}};}
function createLegacyRound(f,rules=R.snapshot()){return useLegacyRoundSnapshot(f.db,f.store.create(f.admin,{requestId:req(),targetDate:target,confirmed:true}).roundId,rules);}
function vote(f,user,id,optionId,expectedRevision=0){return f.store.vote(user,{requestId:req(),roundId:id,optionId,expectedRevision});}
function settle(f,id,value,revision=0,reason=''){return f.store.settle(f.admin,{requestId:req(),roundId:id,returnPct:value,expectedRevision:revision,reason,confirmed:true});}
const marketTables=['market_rounds','market_votes','market_settlements','market_ledger','market_requests'],dropMarket='DROP TABLE market_requests; DROP TABLE market_ledger; DROP TABLE market_settlements; DROP TABLE market_votes; DROP TABLE market_rounds;';
function ban(f){const electorate=[f.admin.id,...f.members.map(user=>user.id)];new DrawWordStore(f.db).ban(WORDS[0],{roomCode:'ABC123',resultId:req(),gameRunId:req(),electorate,votes:electorate.slice(0,2),required:2});}

test('six ranges cover all exact boundaries, adjacent values and zero; uniform-choice expectation is zero',()=>{
 for(const [n,b] of [[-100,'crash'],[-5,'crash'],[-4.999999,'fall'],[-2,'fall'],[-1.999999,'dip'],[-.000001,'dip'],[0,'tie'],[-0,'tie'],[.000001,'rise'],[1.999999,'rise'],[2,'rally'],[4.999999,'rally'],[5,'surge'],[100,'surge']])assert.equal(R.classify(n),b,String(n));
 for(const value of ['', ' ', 'abc', '2%', '0x10', true, null, [],{}, NaN, Infinity, -101,101])assert.throws(()=>R.parseReturn(value));
 for(const o of R.CONFIG.options)assert.equal(R.CONFIG.options.reduce((sum,v)=>sum+R.points(v.id,o.id),0),0);
 assert.ok(R.CONFIG.options.every(o=>R.points(o.id,'tie')===0));assert.equal(R.cutoffFor(target),'2027-01-05T16:00:00.000Z');assert.equal(R.settlementFor(target),'2027-01-06T05:30:00.000Z');
 for(const date of ['2027-02-29','2026-99-99','2027-1-6','1999-01-01','2200-01-01',''])assert.equal(R.validDate(date),false);assert.equal(R.validDate('2028-02-29'),true);
});
test('creation is explicit, unique and admin-only; snapshots ignore client rules and client identities',async t=>{const f=await fixture(t);assert.throws(()=>f.store.create({...f.members[0],role:'admin'},{requestId:req(),targetDate:target,confirmed:true}),code('ADMIN_REQUIRED'));assert.throws(()=>f.store.create(f.admin,{requestId:req(),targetDate:target}),code('CONFIRM_REQUIRED'));
 const input={requestId:req(),targetDate:target,confirmed:true,rules:{hit:999},userId:f.members[0].id},first=f.store.create(f.admin,input);assert.equal(f.store.create(f.admin,input).replayed,true);assert.equal(f.store.view(f.admin).rounds[0].rules.version,3);assert.equal('hit' in f.store.view(f.admin).rounds[0].rules,false);assert.throws(()=>createLegacyRound(f),code('ROUND_EXISTS'));assert.throws(()=>f.store.create(f.admin,{...input,targetDate:'2027-01-07'}),code('REQUEST_ID_REUSED'));assert.equal(f.db.prepare('SELECT created_by FROM market_rounds').get().created_by,f.admin.id);assert.ok(first.roundId);
});
test('one canonical vote can change only before exact cutoff, with revision and idempotency checks',async t=>{const f=await fixture(t),id=createLegacyRound(f),u=f.members[0],input={requestId:req(),roundId:id,optionId:'dip',expectedRevision:0,userId:f.admin.id};assert.equal(f.store.vote(u,input).revision,1);assert.equal(f.store.vote(u,input).replayed,true);assert.throws(()=>vote(f,u,id,'rise'),code('STALE_VOTE'));assert.equal(vote(f,u,id,'dip',1).unchanged,true);f.setTime(cutoff-1);assert.equal(vote(f,u,id,'rally',1).revision,2);f.setTime(cutoff);assert.throws(()=>vote(f,u,id,'rise',2),code('VOTING_CLOSED'));assert.throws(()=>vote(f,f.members[1],id,'rise'),code('VOTING_CLOSED'));assert.equal(f.db.prepare('SELECT COUNT(*) n FROM market_votes').get().n,1);assert.equal(f.store.view(f.admin).rounds[0].vote,null);assert.equal(f.store.view(u).rounds[0].phase,'closed');
});
test('conflicting clients preserve the pending choice and retry explicitly with the refreshed revision',async t=>{const f=await fixture(t),id=createLegacyRound(f),user=f.members[0],eventsA=[],eventsB=[];vote(f,user,id,'dip');const a=await createClient({source:clientSource,rules:R,fetch:makeTransport(f.store,user,eventsA)}),b=await createClient({source:clientSource,rules:R,fetch:makeTransport(f.store,user,eventsB)});
 b.choose('rise');b.submit();await waitFor(()=>!b.inspect().busy);a.choose('rally');a.submit();await waitFor(()=>!a.inspect().busy);
 assert.equal(eventsA.filter(e=>e.method==='POST').length,1,'a conflict must not automatically resubmit');assert.equal(eventsA.find(e=>e.method==='POST').code,'STALE_VOTE');assert.equal(a.inspect().state.rounds[0].vote.revision,2);assert.equal(a.inspect().draft.optionId,'rally');assert.equal(a.inspect().draft.expectedRevision,2);assert.equal(a.node('#saveVote').disabled,false);
 a.submit();await waitFor(()=>!a.inspect().busy);assert.deepEqual(eventsA.filter(e=>e.method==='POST').map(e=>[e.expectedRevision,e.status]),[[1,409],[2,200]]);assert.equal(f.store.view(user).rounds[0].vote.optionId,'rally');assert.equal(f.store.view(user).rounds[0].vote.revision,3);
});
test('manual refresh holds the operation lock until its response finishes, blocking overlapping writes and refreshes',async t=>{const f=await fixture(t),id=createLegacyRound(f),user=f.members[0],events=[],old=deferred(),current=deferred();vote(f,user,id,'dip');let hold=false,reads=0;const client=await createClient({source:clientSource,rules:R,fetch:makeTransport(f.store,user,events,event=>{if(hold&&event.method==='GET'){reads++;return reads===1?old.promise:current.promise;}})});
 hold=true;client.choose('rally');const refresh=client.refresh();await waitFor(()=>reads===1);assert.equal(client.inspect().busy,true);assert.equal(client.node('#refresh').disabled,true);assert.equal(client.node('#saveVote').disabled,true);client.submit();await client.refresh();assert.equal(events.filter(e=>e.method==='POST').length,0);assert.equal(reads,1);
 old.resolve();await refresh;assert.equal(client.inspect().busy,false);assert.equal(client.node('#refresh').disabled,false);client.choose('rally');client.submit();await waitFor(()=>reads===2);await client.refresh();assert.equal(reads,2);assert.equal(client.inspect().busy,true);assert.equal(client.inspect().draft.optionId,'rally');current.resolve();await waitFor(()=>!client.inspect().busy);assert.equal(client.inspect().draft.expectedRevision,2);assert.equal(f.store.view(user).rounds[0].vote.optionId,'rally');assert.equal(events.filter(e=>e.method==='POST').length,1);
});
test('refresh releases its lock on failure and remains available to recover an uncertain mutation',async t=>{const f=await fixture(t),id=createLegacyRound(f),user=f.members[0],events=[];vote(f,user,id,'dip');let failReads=false;const transport=makeTransport(f.store,user,events),client=await createClient({source:clientSource,rules:R,fetch:(url,options)=>{if(failReads&&(!options||options.method!=='POST'))throw Error('synthetic connection failure');return transport(url,options);}});
 failReads=true;await client.refresh();assert.equal(client.inspect().busy,false);assert.equal(client.node('#refresh').disabled,false);client.choose('rally');client.submit();await waitFor(()=>!client.inspect().busy);assert.equal(client.inspect().uncertain,true);assert.equal(client.node('#saveVote').disabled,true);assert.equal(client.node('#refresh').disabled,false);assert.equal(events.filter(e=>e.method==='POST').length,1);assert.equal(f.store.view(user).rounds[0].vote.revision,2);
 failReads=false;await client.refresh();assert.equal(client.inspect().uncertain,false);assert.equal(client.inspect().busy,false);assert.equal(client.inspect().draft.expectedRevision,2);assert.equal(client.inspect().draft.optionId,'rally');assert.equal(client.node('#refresh').disabled,false);
});
test('clock rollback keeps vote timestamps monotonic and the complete database exportable',async t=>{const f=await fixture(t),id=createLegacyRound(f),user=f.members[0];vote(f,user,id,'dip');f.setTime(start+2000);vote(f,user,id,'rise',1);f.setTime(start-1000);assert.equal(vote(f,user,id,'rally',2).revision,3);const row=f.db.prepare('SELECT created_at,updated_at FROM market_votes').get();assert.equal(row.created_at,new Date(start).toISOString());assert.equal(row.updated_at,new Date(start+2000).toISOString());assert.equal(validateDatabase(f.file).schemaVersion,SCHEMA_VERSION);
 f.setTime(cutoff);assert.throws(()=>vote(f,user,id,'surge',3),code('VOTING_CLOSED'));f.db.close();const source={envId:'rollback-test',dbFile:f.file,historyDir:path.join(f.root,'source','history'),communityDir:path.join(f.root,'source','community'),musicDir:path.join(f.root,'source','music')};for(const dir of [source.historyDir,source.communityDir,source.musicDir])fs.mkdirSync(dir,{recursive:true});const keyFile=path.join(f.root,'test-key'),outputDir=path.join(f.root,'bundle');await run({action:'keygen',keyFile});await run({action:'export',source,sourceStopped:true,keyFile,outputDir});await run({action:'verify',bundleDir:outputDir,keyFile});
});
test('settlement awards hit/miss/tie, excludes nonvoters, rejects duplicates, and corrections reverse before re-awarding',async t=>{const f=await fixture(t),id=createLegacyRound(f);vote(f,f.members[0],id,'rally');vote(f,f.members[1],id,'dip');f.setTime(after-1);assert.throws(()=>settle(f,id,2),code('TOO_EARLY'));f.setTime(after);
 assert.throws(()=>settle(f,id,'nan'),code('INVALID_RETURN'));const preview=f.store.preview(f.admin,{roundId:id,returnPct:2,expectedRevision:0});assert.deepEqual(preview.counts,{hit:1,miss:1,tie:0});assert.equal(f.db.prepare('SELECT COUNT(*) n FROM market_ledger').get().n,0);
 const payload={requestId:req(),roundId:id,returnPct:2,expectedRevision:0,confirmed:true};assert.equal(f.store.settle(f.admin,payload).revision,1);assert.equal(f.store.settle(f.admin,payload).replayed,true);assert.throws(()=>settle(f,id,2),code('STALE_RESULT'));assert.throws(()=>settle(f,id,2,1,'unchanged'),code('RESULT_UNCHANGED'));assert.throws(()=>settle(f,id,-2,1),code('CORRECTION_REASON'));
 assert.equal(f.store.stats(f.members[0].id).score,5);assert.equal(f.store.stats(f.members[1].id).score,-1);assert.equal(f.store.stats(f.admin.id).score,0);
 settle(f,id,-2,1,'修正輸入');assert.equal(f.store.stats(f.members[0].id).score,-1);assert.equal(f.store.stats(f.members[1].id).score,-1);settle(f,id,0,2,'確認持平');assert.deepEqual(f.store.stats(f.members[0].id),{score:0,played:1,hits:0,ties:1});assert.equal(f.db.prepare('SELECT COUNT(*) n FROM market_ledger').get().n,10);assert.equal(validateMarketDatabase(f.db),true);f.setTime(start);assert.throws(()=>vote(f,f.members[0],id,'surge',1),code('VOTING_CLOSED'));
});
test('ledger failure rolls back settlement, scores and receipt as one transaction',async t=>{const f=await fixture(t),id=createLegacyRound(f);vote(f,f.members[0],id,'rally');vote(f,f.members[1],id,'rise');f.setTime(after);f.db.exec("CREATE TRIGGER market_injected_failure BEFORE INSERT ON market_ledger WHEN (SELECT COUNT(*) FROM market_ledger)>0 BEGIN SELECT RAISE(ABORT,'injected'); END");assert.throws(()=>settle(f,id,2));for(const table of ['market_ledger','market_settlements'])assert.equal(f.db.prepare('SELECT COUNT(*) n FROM '+table).get().n,0);assert.equal(f.store.view(f.admin).rounds[0].result,null);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM market_requests WHERE operation='settle'").get().n,0);f.db.exec('DROP TRIGGER market_injected_failure');settle(f,id,2);assert.equal(validateMarketDatabase(f.db),true);
});
test('DB identity and disabled/admin checks apply even to stale actor objects',async t=>{const f=await fixture(t),id=createLegacyRound(f);assert.throws(()=>f.store.view({id:req()}),code('UNAUTHORIZED'));assert.throws(()=>f.store.preview({...f.members[0],role:'admin'},{roundId:id,returnPct:0,expectedRevision:0}),code('ADMIN_REQUIRED'));f.db.prepare('UPDATE users SET disabled=1 WHERE id=?').run(f.members[0].id);assert.throws(()=>vote(f,f.members[0],id,'surge'),code('UNAUTHORIZED'));f.db.prepare("UPDATE users SET role='member' WHERE id=?").run(f.admin.id);assert.throws(()=>f.store.view(f.admin,true),code('ADMIN_REQUIRED'));
});

async function listenSafe(app){const address=await app.listen();return 'http://127.0.0.1:'+address.port;}
test('authenticated HTTP integration persists and handles simultaneous stale vote and settlement requests',async t=>{const f=await fixture(t),id=createLegacyRound(f),config={...settings({DB_FILE:f.file,HISTORY_DIR:path.join(f.root,'history'),COMMUNITY_DIR:path.join(f.root,'community'),MUSIC_DIR:path.join(f.root,'music'),EXTERNAL_SIDE_EFFECTS_ENABLED:'false'}),port:0,host:'127.0.0.1',githubClient:{configured:false},marketClock:f.clock};f.db.close();let app=createApp(config),base=await listenSafe(app);const post=async(route,data,cookie)=>fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify(data)});const login=async username=>{const r=await post('/api/auth/login',{username,password});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];};
 try{assert.equal((await fetch(base+'/api/market')).status,401);const redirect=await fetch(base+'/market',{redirect:'manual'});assert.equal(redirect.status,302);assert.equal(redirect.headers.get('location'),'/login?next=%2Fmarket');const adminCookie=await login('market_admin'),memberCookie=await login('market_member_0');assert.equal((await post('/api/admin/market/rounds',{requestId:req(),targetDate:target,confirmed:true,role:'admin'},memberCookie)).status,403);
  const made=await post('/api/admin/market/rounds',{requestId:req(),targetDate:'2027-01-07',confirmed:true},adminCookie);assert.equal(made.status,200);const newId=(await made.json()).roundId;const created=await(await fetch(base+'/api/market',{headers:{Cookie:adminCookie}})).json();assert.equal(created.rounds.find(round=>round.id===newId).rules.version,3);assert.equal('hit' in created.rounds.find(round=>round.id===newId).rules,false);
  const responses=await Promise.all(['dip','rally','surge'].map(optionId=>post('/api/market/vote',{requestId:req(),roundId:id,optionId,expectedRevision:0,userId:f.admin.id},memberCookie)));assert.deepEqual(responses.map(r=>r.status).sort(),[200,409,409]);
  let view=await (await fetch(base+'/api/market',{headers:{Cookie:memberCookie}})).json();assert.equal(view.rounds.find(round=>round.id===id).vote.revision,1);assert.equal((await fetch(base+'/api/market/vote',{headers:{Cookie:memberCookie}})).status,405);
  f.setTime(after);const results=await Promise.all([2,-2].map(returnPct=>post('/api/admin/market/settle',{requestId:req(),roundId:id,returnPct,expectedRevision:0,confirmed:true},adminCookie)));assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);view=await (await fetch(base+'/api/market',{headers:{Cookie:memberCookie}})).json();assert.equal(view.rounds.find(round=>round.id===id).result.revision,1);const score=view.stats.score;
  await app.close();app=createApp(config);base=await listenSafe(app);view=await (await fetch(base+'/api/market',{headers:{Cookie:memberCookie}})).json();assert.equal(view.stats.score,score);assert.equal(view.rounds.find(round=>round.id===id).vote.revision,1);assert.equal(view.ledger.length,1);
  const db=openDatabase(f.file);try{db.prepare('UPDATE users SET disabled=1 WHERE id=?').run(f.members[0].id);}finally{db.close();}assert.equal((await fetch(base+'/api/market',{headers:{Cookie:memberCookie}})).status,401);
 }finally{await app.close();}
});

test('true schema 12 migrates with empty market and ban data and preserves account hashes',async t=>{const f=await fixture(t),users=f.db.prepare('SELECT * FROM users ORDER BY id').all();legacyMarketSchema(f.db);f.db.exec(dropMarket+'DROP TABLE draw_word_exclusions; PRAGMA user_version=12');f.db.close();const upgraded=openDatabase(f.file);try{assert.equal(upgraded.prepare('PRAGMA user_version').get().user_version,SCHEMA_VERSION);assert.deepEqual(upgraded.prepare('SELECT * FROM users ORDER BY id').all(),users);for(const table of [...marketTables,'draw_word_exclusions'])assert.equal(upgraded.prepare('SELECT COUNT(*) n FROM '+table).get().n,0);assert.equal(validateMarketDatabase(upgraded),true);}finally{upgraded.close();}});
test('full encrypted export/verify/dry-run/restore preserves votes, corrected scores, receipts and word bans, and revokes sessions',async t=>{const f=await fixture(t),id=createLegacyRound(f);vote(f,f.members[0],id,'rally');ban(f);f.setTime(after);settle(f,id,2);settle(f,id,-2,1,'備份前更正');const expected=f.store.view(f.members[0]),users=f.db.prepare('SELECT * FROM users ORDER BY id').all(),tables=[...marketTables,'draw_word_exclusions'],before=Object.fromEntries(tables.map(x=>[x,f.db.prepare('SELECT * FROM '+x+' ORDER BY rowid').all()]));
 const source={envId:'market-test',dbFile:f.file,historyDir:path.join(f.root,'source','history'),communityDir:path.join(f.root,'source','community'),musicDir:path.join(f.root,'source','music')};for(const dir of [source.historyDir,source.communityDir,source.musicDir])fs.mkdirSync(dir,{recursive:true});const bundle=path.join(f.root,'bundle'),key=path.join(f.root,'test-key'),destination=path.join(f.root,'restored');f.db.close();
 await run({action:'keygen',keyFile:key});await run({action:'export',source,sourceStopped:true,outputDir:bundle,keyFile:key});await run({action:'verify',bundleDir:bundle,keyFile:key});const request={action:'restore',bundleDir:bundle,keyFile:key,destinationDir:destination};assert.equal((await run(request)).dryRun,true);assert.equal(fs.existsSync(destination),false);const restored=await run({...request,apply:true}),db=openDatabase(settings(restored.config).dbFile);try{assert.deepEqual(db.prepare('SELECT * FROM users ORDER BY id').all(),users);for(const table of tables)assert.deepEqual(db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all(),before[table]);assert.equal(db.prepare('SELECT COUNT(*) n FROM sessions').get().n,0);const s=new MarketStore(db,()=>after);assert.deepEqual(s.view(f.members[0]).stats,expected.stats);assert.equal(validateMarketDatabase(db),true);const auth=createAuth(db);const member=await auth.login({username:'market_member_0',password},{setHeader(){}});assert.equal(member.id,f.members[0].id);}finally{db.close();}
 assert.equal(validateDatabase(f.file).schemaVersion,SCHEMA_VERSION);
});
for(const version of [13,14,SCHEMA_VERSION])test(`schema ${version} backup validation rejects corrupt scoring even if SQLite integrity and foreign keys pass`,async t=>{const f=await fixture(t),id=createLegacyRound(f);vote(f,f.members[0],id,'rally');f.setTime(after);settle(f,id,2);if(version<17)legacyMarketSchema(f.db);if(version===13)f.db.exec('DROP TABLE draw_word_exclusions');f.db.exec('PRAGMA user_version='+version);f.db.prepare('UPDATE market_ledger SET points=999').run();assert.throws(()=>validateDatabase(f.file),code('INVALID_DATABASE'));});

for(const layout of ['main-ban-only','market-only'])test(`legacy schema 13 ${layout} upgrades and cold-restores to both features without changing existing data`,async t=>{const f=await fixture(t),id=createLegacyRound(f);vote(f,f.members[0],id,'rally');f.setTime(after);settle(f,id,2);settle(f,id,-2,1,'legacy correction');ban(f);legacyMarketSchema(f.db);f.db.exec((layout==='main-ban-only'?dropMarket:'DROP TABLE draw_word_exclusions;')+'PRAGMA user_version=13');
 const existing=layout==='main-ban-only'?['draw_word_exclusions']:marketTables,rows=Object.fromEntries(existing.map(table=>[table,f.db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all()])),users=f.db.prepare('SELECT * FROM users ORDER BY id').all(),before=validateDatabase(f.file);assert.equal(before.schemaVersion,13);f.db.close();
 const source={envId:'legacy-13-test',dbFile:f.file,historyDir:path.join(f.root,'source','history'),communityDir:path.join(f.root,'source','community'),musicDir:path.join(f.root,'source','music')};for(const dir of [source.historyDir,source.communityDir,source.musicDir])fs.mkdirSync(dir,{recursive:true});const keyFile=path.join(f.root,'test-key'),outputDir=path.join(f.root,'bundle'),destinationDir=path.join(f.root,'restored');await run({action:'keygen',keyFile});await run({action:'export',source,sourceStopped:true,keyFile,outputDir});await run({action:'verify',bundleDir:outputDir,keyFile});const request={action:'restore',bundleDir:outputDir,keyFile,destinationDir};assert.equal((await run(request)).dryRun,true);const restored=await run({...request,apply:true});assert.deepEqual(validateDatabase(f.file),before,'cold restore must leave the legacy source unchanged');
 function check(db){assert.equal(db.prepare('PRAGMA user_version').get().user_version,SCHEMA_VERSION);assert.deepEqual(db.prepare('SELECT * FROM users ORDER BY id').all(),users);for(const [table,expected] of Object.entries(rows))assert.deepEqual(db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all(),upgradedMarketRows(table,expected));for(const table of [...marketTables,'draw_word_exclusions','character_sounds'])assert.ok(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(table));assert.equal(new MarketStore(db,()=>after).stats(f.members[0].id).score,layout==='market-only'?-1:0);assert.equal(new DrawWordStore(db).isExcluded(WORDS[0]),layout==='main-ban-only');}
 const restoredFile=settings(restored.config).dbFile,copy=openDatabase(restoredFile);try{check(copy);assert.equal(copy.prepare('SELECT COUNT(*) n FROM sessions').get().n,0);}finally{copy.close();}const upgraded=openDatabase(f.file);try{check(upgraded);}finally{upgraded.close();}const restarted=openDatabase(f.file);try{check(restarted);}finally{restarted.close();}assert.equal(validateDatabase(f.file).schemaVersion,SCHEMA_VERSION);
});
test('incomplete legacy 13 and schema 14 layouts are rejected instead of exported or silently repaired',async t=>{for(const [version,drop] of [[13,dropMarket+'DROP TABLE draw_word_exclusions;'],[13,'DROP TABLE market_requests;'],[14,'DROP TABLE draw_word_exclusions;'],[14,'DROP TABLE market_requests;'],[14,dropMarket+'DROP TABLE character_sounds;']]){const f=await fixture(t);legacyMarketSchema(f.db);f.db.exec(drop+'PRAGMA user_version='+version);assert.throws(()=>validateDatabase(f.file),code('INVALID_DATABASE'));f.db.close();assert.throws(()=>openDatabase(f.file),/Incomplete (legacy|database) schema (13|14)/);const unchanged=new DatabaseSync(f.file,{readOnly:true});try{assert.equal(unchanged.prepare('PRAGMA user_version').get().user_version,version);}finally{unchanged.close();}}});

async function race(file,operations,now){const barrier=new SharedArrayBuffer(4),workers=operations.map(operation=>new Worker(path.join(__dirname,'helpers/market-worker.cjs'),{workerData:{file,barrier,now,...operation}}));
 try{const ready=workers.map(worker=>new Promise((resolve,reject)=>{worker.once('error',reject);worker.once('message',message=>message.ready?resolve():reject(Error('Worker not ready')));}));await Promise.all(ready);
  const results=workers.map(worker=>new Promise((resolve,reject)=>{worker.on('message',message=>{if('ok' in message)resolve(message);});worker.once('error',reject);worker.once('exit',code=>{if(code)reject(Error('Worker exited '+code));});}));Atomics.store(new Int32Array(barrier),0,1);Atomics.notify(new Int32Array(barrier),0,workers.length);return await Promise.all(results);
 }finally{await Promise.all(workers.map(w=>w.terminate()));}}
test('separate SQLite connections serialize competing revisions and replay identical settlements once',async t=>{const f=await fixture(t),id=createLegacyRound(f),u=f.members[0];const responses=await race(f.file,['dip','rally'].map(optionId=>({operation:'vote',userId:u.id,input:{requestId:req(),roundId:id,optionId,expectedRevision:0}})),start);assert.equal(responses.filter(x=>x.ok).length,1);assert.equal(responses.find(x=>!x.ok).code,'STALE_VOTE');
 const independent=await race(f.file,[f.admin,f.members[1]].map(user=>({operation:'vote',userId:user.id,input:{requestId:req(),roundId:id,optionId:'rally',expectedRevision:0}})),start);assert.ok(independent.every(x=>x.ok));
 const input={requestId:req(),roundId:id,returnPct:2,expectedRevision:0,confirmed:true},duplicate=await race(f.file,[0,1].map(()=>({operation:'settle',userId:f.admin.id,input})),after);assert.ok(duplicate.every(x=>x.ok));assert.equal(duplicate.filter(x=>x.result.replayed).length,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM market_settlements').get().n,1);
 const corrections=await race(f.file,[-2,0].map(returnPct=>({operation:'settle',userId:f.admin.id,input:{requestId:req(),roundId:id,returnPct,expectedRevision:1,confirmed:true,reason:'競爭更正'}})),after+1000);assert.equal(corrections.filter(x=>x.ok).length,1);assert.equal(corrections.find(x=>!x.ok).code,'STALE_RESULT');assert.equal(f.db.prepare('SELECT COUNT(*) n FROM market_ledger').get().n,9);assert.equal(validateMarketDatabase(f.db),true);
});
test('queued vote samples server time after lock acquisition and rejects a crossed deadline',async t=>{const f=await fixture(t),id=createLegacyRound(f),barrier=new SharedArrayBuffer(4),sharedTime=new SharedArrayBuffer(8);Atomics.store(new BigInt64Array(sharedTime),0,BigInt(start));const worker=new Worker(path.join(__dirname,'helpers/market-worker.cjs'),{workerData:{file:f.file,barrier,sharedTime,operation:'vote',userId:f.members[0].id,input:{requestId:req(),roundId:id,optionId:'surge',expectedRevision:0}}});
 try{await new Promise((resolve,reject)=>{worker.once('message',resolve);worker.once('error',reject);});f.db.exec('BEGIN IMMEDIATE');const result=new Promise((resolve,reject)=>{worker.once('message',resolve);worker.once('error',reject);});Atomics.store(new Int32Array(barrier),0,1);Atomics.notify(new Int32Array(barrier),0);await new Promise(resolve=>setTimeout(resolve,80));Atomics.store(new BigInt64Array(sharedTime),0,BigInt(cutoff));f.db.exec('COMMIT');assert.equal((await result).code,'VOTING_CLOSED');assert.equal(f.db.prepare('SELECT COUNT(*) n FROM market_votes').get().n,0);
 }finally{if(f.db.isTransaction)f.db.exec('ROLLBACK');await worker.terminate();}
});
test('failed correction restores the previous scores and complete audit without partial reversal',async t=>{const f=await fixture(t),id=createLegacyRound(f);vote(f,f.members[0],id,'rally');f.setTime(after);settle(f,id,2);const before=f.store.view(f.members[0]);f.db.exec("CREATE TRIGGER correction_failure BEFORE INSERT ON market_ledger WHEN NEW.revision=2 AND NEW.kind='award' BEGIN SELECT RAISE(ABORT,'correction failed'); END");assert.throws(()=>settle(f,id,-2,1,'更正'));assert.deepEqual(f.store.view(f.members[0]).stats,before.stats);assert.equal(f.store.view(f.members[0]).rounds[0].result.revision,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM market_ledger').get().n,1);assert.equal(validateMarketDatabase(f.db),true);});

test('23:59 whole minute is open until Taipei target midnight while old v1 snapshots remain immutable',async t=>{const f=await fixture(t),id=createLegacyRound(f),u=f.members[0];
 f.setTime(Date.parse('2027-01-05T15:59:00.000Z'));assert.equal(vote(f,u,id,'dip').revision,1);
 f.setTime(Date.parse('2027-01-05T15:59:59.999Z'));assert.equal(vote(f,u,id,'rally',1).revision,2);
 f.setTime(Date.parse('2027-01-05T16:00:00.000Z'));assert.throws(()=>vote(f,u,id,'surge',2),code('VOTING_CLOSED'));
 const legacy={...R.snapshot(),version:1,cutoffTime:'21:00'};delete legacy.cutoffExclusive;assert.equal(R.validate(legacy),legacy);assert.equal(R.cutoffFor(target,legacy),'2027-01-05T13:00:00.000Z');
 const historical=await fixture(t),legacyId=createLegacyRound(historical,legacy),legacyUser=historical.members[0];
 const before=historical.db.prepare('SELECT * FROM market_rounds WHERE id=?').get(legacyId);historical.setTime(Date.parse('2027-01-05T12:59:59.999Z'));vote(historical,legacyUser,legacyId,'rise');historical.setTime(Date.parse('2027-01-05T13:00:00Z'));assert.throws(()=>vote(historical,legacyUser,legacyId,'rally',1),code('VOTING_CLOSED'));
 assert.deepEqual(historical.db.prepare('SELECT * FROM market_rounds WHERE id=?').get(legacyId),before);assert.equal(validateMarketDatabase(historical.db),true);assert.equal(validateMarketDatabase(f.db),true);
 const invalid={...R.snapshot(),cutoffExclusive:'previous-minute'};assert.throws(()=>R.validate(invalid));
});
