'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{randomUUID}=require('node:crypto');
const {MinimalRoom}=require('../src/games/minimal'),{MusicQuizRoom}=require('../src/games/musicquiz');const flush=async()=>{for(let i=0;i<40;i++)await Promise.resolve();};
function fixture(type='minimal',room,storage=new Map()){
 const r=room||(type==='minimal'?new MinimalRoom('ABCDEF','client',()=>0):new MusicQuizRoom('ABCDEF','client',()=>0));if(!room){r.add('reader');if(type==='minimal'){r.add('peer');r.add('peer2');}r.start();if(type==='minimal'){for(const p of r.artists())r.act(p.id,'submit',{roundId:r.roundId,requestId:randomUUID(),shapes:[]});r.act(r.host,'next',{roundId:r.roundId,requestId:randomUUID()});}}
 const p=r.players[0],ids=new Map(),events={},timers=new Set(),requests=[],audioBindings=new Set();let deferred=null,loseReply=false;
 class E{constructor(tag='div'){this.tag=tag;this.children=[];this.value='';this.disabled=false;this.textContent='';this.style={};this.paused=true;}set id(v){this._id=v;ids.set('#'+v,this);}get id(){return this._id;}append(...items){this.children.push(...items);}setAttribute(){}setPointerCapture(){}pause(){this.paused=true;}removeIds(c){if(c.id)ids.delete('#'+c.id);for(const child of c.children)this.removeIds(child);}replaceChildren(...items){for(const c of this.children)this.removeIds(c);this.children=items;}querySelectorAll(selector){return this.children.flatMap(c=>[...(selector.split(',').includes(c.tag)?[c]:[]),...c.querySelectorAll(selector)]);}}
 for(const id of ['feedback','controls','retry','leave','game','phase','players','deadline','source','results','connection','guide']){const e=new E();e.id=id;}
 const context={document:{hidden:false,querySelector:s=>ids.get(s)||null,createElement:tag=>new E(tag),addEventListener:(type,fn)=>events[type]=fn},location:{pathname:'/'+type+'/ABCDEF',replace(){}},crypto:{randomUUID},AbortController,sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},confirm:()=>true,
  RoomApi:{request:async(route,data,options)=>{requests.push({route,data,options});if(deferred){const next=await deferred;deferred=null;return next;}if(route==='action'){r.act(p.id,data.action,data);if(loseReply){loseReply=false;throw Error('lost reply');}}return r.view(p.id);}},RoomReconnect:{restore:async()=>({}),forget(){}},AudioSettings:{bindPreview:a=>{audioBindings.add(a);return ()=>audioBindings.delete(a);}},StrokeCanvas:{pointFrom:e=>[e.clientX,e.clientY],createRenderer:()=>({render(){}})},setInterval:fn=>{timers.add(fn);return fn;},clearInterval:fn=>timers.delete(fn)};
 context.window={addEventListener:(type,fn)=>events[type]=fn};vm.runInNewContext(fs.readFileSync(require.resolve('../public/shared/party-shapes.js'),'utf8'),context);context.PartyShapes=context.window.PartyShapes;vm.runInNewContext(fs.readFileSync(require.resolve('../public/party-games.js'),'utf8'),context);
 return {r,p,ids,events,timers,requests,audioBindings,storage,async poll(){for(const fn of timers)await fn();await flush();},defer:x=>deferred=x,lose:()=>loseReply=true,buttons:()=>ids.get('#controls').querySelectorAll('button')};
}
test('minimal drafts remain through polls and reload, and shape sync cannot mutate a retry payload',async()=>{const f=fixture();await flush();const c=f.ids.get('#drawing'),e={button:0,pointerId:1,clientX:20,clientY:20,preventDefault(){}};c.onpointerdown(e);f.lose();c.onpointerup({...e,clientX:40,clientY:40});await flush();const first=f.requests.find(q=>q.route==='action');assert.equal(f.r.drafts[f.p.id].length,1);await f.poll();assert.equal(f.ids.get('#drawing'),c);const again=fixture('minimal',f.r,f.storage);await flush();assert.ok(again.ids.get('#drawing'));await f.ids.get('#retry').onclick();await flush();const mutations=f.requests.filter(q=>q.route==='action');assert.equal(mutations[0].data.requestId,mutations[1].data.requestId);assert.equal(first.data.shapes.length,1);});
test('BFCache ignores late response, resumes a single poller and music has one removable binding',async()=>{const f=fixture('musicquiz');await flush();assert.equal(f.audioBindings.size,1);const input=f.ids.get('#answer');input.value='私人未送出歌名';input.oninput();let resolve;f.defer(new Promise(done=>resolve=done));const poll=f.poll();await flush();f.events.pagehide();assert.equal(f.timers.size,0);assert.equal(f.audioBindings.size,0);assert.equal(f.requests.at(-1).options.signal.aborted,true);f.events.pageshow({persisted:true});resolve({...f.r.view(f.p.id),phase:'finished',version:999});await poll;await flush();assert.equal(f.ids.get('#answer'),input);assert.equal(f.timers.size,1);await f.poll();assert.equal(f.audioBindings.size,1);});
test('geometry conversion produces genuine circles and simple lines without colour or freehand extensions',()=>{const context={window:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../public/shared/party-shapes.js'),'utf8'),context);const result=context.window.PartyShapes.toStrokes([{kind:'circle',cx:100,cy:100,r:20},{kind:'line',x1:5,y1:10,x2:15,y2:20}]);assert.equal(result[0].tool,'ellipse');assert.equal(result[0].points[1][0]-result[0].points[0][0],result[0].points[1][1]-result[0].points[0][1]);assert.equal(result[1].tool,'line');assert.equal(result[0].color,'#222222');});
