const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {createApp}=require('../src/app');
const {openDatabase}=require('../src/db/index');
const {createAuth}=require('../src/auth/index');

test('room directory shows current join choices and respects game, capacity, and kicked seats',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'bga-rooms-'));
 const config={port:0,host:'127.0.0.1',historyDir:path.join(root,'history'),communityDir:path.join(root,'community'),dbFile:path.join(root,'app.sqlite')};
 const db=openDatabase(config.dbFile);
 await createAuth(db).bootstrap('roomadmin','test-password-123');
 db.close();
 const app=createApp(config);
 try{
  const {port}=await app.listen(),base=`http://127.0.0.1:${port}`;
  const post=async(route,cookie,data)=>{
   const response=await fetch(base+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify(data)});
   return {status:response.status,body:await response.json(),cookie:response.headers.get('set-cookie')?.split(';')[0]};
  };
  const login=await post('auth/login',null,{username:'roomadmin',password:'test-password-123'});
  assert.equal(login.status,200);
  const admin=login.cookie;
  const register=async username=>{
   const invite=await post('admin/invites',admin,{days:1});
   assert.equal(invite.status,200);
   const joined=await post('auth/register',null,{username,displayName:username,password:'test-password-123',confirmPassword:'test-password-123',invite:invite.body.code});
   assert.equal(joined.status,200);
   return joined.cookie;
  };
  const guest=await register('roomguest');
  const outsider=await register('roomother');
  const observer=await register('roomwatch');
  const list=async cookie=>{
   const response=await fetch(base+'/api/rooms',{headers:cookie?{Cookie:cookie}:{}});
   return {status:response.status,body:await response.json()};
  };
  assert.equal((await list()).status,401);
  assert.deepEqual((await list(guest)).body.rooms,[]);
  const race=(await post('create',admin,{type:'thunder',roomName:'賽車桌'})).body;
  const poker=(await post('create',admin,{type:'poker',roomName:'撲克桌'})).body;
  const majority=(await post('create',admin,{type:'majority',roomName:'派對桌'})).body;
  const anonymousReconnect=await post('reconnect',null,{code:race.code});
  assert.equal(anonymousReconnect.status,401);
  assert.equal((await post('reconnect',guest,{code:race.code})).body.code,'NOT_SEATED');
  const redirect=await fetch(base+'/race/'+race.code,{redirect:'manual'});
  assert.equal(redirect.status,302);
  assert.equal(redirect.headers.get('location'),'/login?next=%2Frace%2F'+race.code);
  let rooms=(await list(guest)).body.rooms;
  assert.equal(rooms.length,3);
  assert.deepEqual(new Set(rooms.map(room=>room.type)),new Set(['thunder','poker','majority']));
  assert.ok(rooms.every(room=>room.playerCount===1&&room.joinable&&!room.seated));
  assert.ok(rooms.every(room=>!('players' in room)&&!('secret' in room)));
  assert.equal((await post('join',guest,{code:race.code})).status,200);
  assert.equal((await post('join',guest,{code:poker.code})).status,200);
  const raceBefore=await (await fetch(base+'/api/state?code='+race.code,{headers:{Cookie:guest}})).json();
  assert.equal((await post('reconnect',guest,{code:race.code})).body.reconnected,true);
  const raceAfter=await (await fetch(base+'/api/state?code='+race.code,{headers:{Cookie:guest}})).json();
  assert.equal(raceAfter.me,raceBefore.me);
  assert.equal(raceAfter.players.length,raceBefore.players.length);
  assert.equal((await post('start',admin,{code:race.code})).status,200);
  assert.equal((await post('start',admin,{code:poker.code})).status,200);
  rooms=(await list(outsider)).body.rooms;
  assert.equal(rooms.find(room=>room.code===race.code).joinable,false);
  assert.equal(rooms.find(room=>room.code===poker.code).joinable,true);
  assert.equal(rooms.find(room=>room.code===majority.code).joinable,true);
  assert.equal((await list(guest)).body.rooms.find(room=>room.code===race.code).seated,true);
  assert.equal((await post('join',outsider,{code:race.code})).status,400);
  assert.equal((await post('join',outsider,{code:poker.code})).status,200);
  const raceState=await (await fetch(base+'/api/state?code='+race.code,{headers:{Cookie:admin}})).json();
  const guestSeat=raceState.players.find(player=>player.name==='roomguest');
  assert.equal((await post('kick',admin,{code:race.code,playerId:guestSeat.id,confirmed:true})).status,200);
  const kicked=(await list(guest)).body.rooms.find(room=>room.code===race.code);
  assert.equal(kicked.kicked,true);
  assert.equal(kicked.joinable,false);
  assert.equal((await post('join',guest,{code:race.code})).status,403);
  assert.equal((await post('reconnect',guest,{code:race.code})).body.code,'KICKED');
  for(let i=0;i<5;i++)assert.equal((await post('bot',admin,{code:poker.code})).status,i<3?200:400);
  const full=(await list(observer)).body.rooms.find(room=>room.code===poker.code);
  assert.equal(full.playerCount,6);
  assert.equal(full.joinable,false);
  assert.equal((await list(guest)).body.rooms.find(room=>room.code===poker.code).joinable,true);
  for(const type of ['draw','gift','majority','thunder','poker']){
   const room=(await post('create',admin,{type})).body;
   assert.equal((await post('leave',outsider,{code:room.code})).body.code,'NOT_SEATED');
   assert.equal((await post('join',guest,{code:room.code})).status,200);
   const leaving=await post('leave',admin,{code:room.code});assert.equal(leaving.status,200);assert.equal(leaving.body.deleted,false);
   assert.equal((await list(admin)).body.rooms.find(r=>r.code===room.code).seated,false);
   assert.equal((await post('reconnect',admin,{code:room.code})).body.code,'NOT_SEATED');
   const remaining=await (await fetch(base+'/api/state?code='+room.code,{headers:{Cookie:guest}})).json();assert.equal(remaining.host,true);
   assert.equal((await post('leave',guest,{code:room.code})).body.deleted,true);
   assert.ok(!(await list(guest)).body.rooms.some(r=>r.code===room.code));
   assert.equal((await post('reconnect',guest,{code:room.code})).body.code,'ROOM_NOT_FOUND');
  }
  const botOnly=(await post('create',admin,{type:'poker'})).body;
  assert.equal((await post('bot',admin,{code:botOnly.code})).status,200);
  assert.equal((await post('leave',admin,{code:botOnly.code})).body.deleted,true);
  assert.ok(!(await list(admin)).body.rooms.some(r=>r.code===botOnly.code));
 }finally{await app.close();fs.rmSync(root,{recursive:true,force:true});}
});
