const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {randomUUID,hkdfSync,createHmac}=require('node:crypto'),{DatabaseSync}=require('node:sqlite');
const {openDatabase,SCHEMA_VERSION}=require('../src/db'),{AchievementStore}=require('../src/achievements/store');
const {legacyMarketSchema,dropEmptyCurveTables,useLegacyRoundSnapshot}=require('./helpers/market-legacy-schema.cjs');
const {MarketStore}=require('../src/market/store');
const {validateDatabase}=require('../src/data/validation'),{run,canonical}=require('../src/data/transfer'),{settings}=require('../src/config');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'schema-forks-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const file=path.join(root,'source','app.sqlite'),db=openDatabase(file),user=randomUUID();db.prepare('INSERT INTO users(id,username,display_name,password_hash,role,created_at) VALUES(?,?,?,?,?,?)').run(user,'historical','保留原暱稱','scrypt:'+Buffer.alloc(16,1).toString('hex')+':'+Buffer.alloc(64,2).toString('hex'),'admin','2026-01-01T00:00:00.000Z');db.prepare('INSERT INTO user_achievements VALUES(?,?,?,?)').run(user,'poker-first-hand','original','2026-01-02T00:00:00.000Z');return {root,file,db,user};}
function rows(db){return Object.fromEntries(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map(({name})=>[name,db.prepare('SELECT * FROM '+name+' ORDER BY rowid').all()]));}
function historical(f,kind){
 if(kind==='achievement17'){
  let now=Date.parse('2027-01-03T12:00:00Z');const market=new MarketStore(f.db,()=>now),admin={id:f.user,role:'admin'},round=market.create(admin,{requestId:randomUUID(),targetDate:'2027-01-04',confirmed:true});useLegacyRoundSnapshot(f.db,round.roundId);market.vote(admin,{requestId:randomUUID(),roundId:round.roundId,optionId:'rally',expectedRevision:0});now=Date.parse('2027-01-04T08:00:00Z');market.settle(admin,{requestId:randomUUID(),roundId:round.roundId,returnPct:3,expectedRevision:0,confirmed:true});
  new AchievementStore(f.db).processUnit({unit_event_id:randomUUID(),match_id:randomUUID(),game_type:'draw',unit:'round',round:1,status:'rules_completed',completed_at:'2026-01-03T00:00:00.000Z',participants:[{user_id:f.user,seat_id:'seat',eligible:true,artist:true,strokeAccepted:true}],metrics:{participantCount:1},purpose:'production',source:'game_server',rule_version:1});
  legacyMarketSchema(f.db,{preserveAchievements:true});f.db.exec('PRAGMA user_version=17');
 }else{
  f.db.exec('DROP TABLE achievement_progress; DROP TABLE processed_unit_events');if(kind==='market17')dropEmptyCurveTables(f.db);f.db.exec('PRAGMA user_version='+(kind==='market17'?17:18));
 }
 const before=rows(f.db);f.db.close();return before;
}
for(const kind of ['achievement17','market17','market18'])test('historical '+kind+' upgrades to the combined schema without changing prior rows or badge dates',t=>{
 const f=fixture(t),before=historical(f,kind);assert.equal(validateDatabase(f.file).schemaVersion,kind==='market18'?18:17);const db=openDatabase(f.file);
 try{assert.equal(db.prepare('PRAGMA user_version').get().user_version,SCHEMA_VERSION);assert.equal(SCHEMA_VERSION,19);const after=rows(db);for(const name of Object.keys(before))assert.deepEqual(after[name].map(row=>Object.fromEntries(Object.keys(before[name][0]||row).map(key=>[key,row[key]]))),before[name].map(row=>({...row})),name);assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);for(const name of Object.keys(after).filter(n=>!Object.hasOwn(before,n)))assert.deepEqual(after[name],[],name);}finally{db.close();}
});
for(const table of ['processed_unit_events','market_automation_state','market_forecasts'])test('combined schema cannot silently repair missing '+table,t=>{
 const f=fixture(t);f.db.exec('DROP TABLE '+table);f.db.close();assert.throws(()=>openDatabase(f.file),/schema/);assert.throws(()=>validateDatabase(f.file));const db=new DatabaseSync(f.file);try{assert.equal(db.prepare('PRAGMA user_version').get().user_version,19);assert.equal(db.prepare("SELECT name FROM sqlite_master WHERE name=?").get(table),undefined);}finally{db.close();}
});
test('late migration failure leaves the historical automation schema, rows and version untouched',t=>{
 const f=fixture(t);historical(f,'market18');const db=new DatabaseSync(f.file);db.exec('CREATE VIEW achievement_progress AS SELECT 1 AS unexpected');const before=rows(db);db.close();assert.throws(()=>openDatabase(f.file),/achievement schema/);const check=new DatabaseSync(f.file);try{assert.equal(check.prepare('PRAGMA user_version').get().user_version,18);assert.deepEqual(rows(check),before);assert.equal(check.prepare("SELECT name FROM sqlite_master WHERE name='processed_unit_events'").get(),undefined);}finally{check.close();}
});
for(const kind of ['market17','market18'])test('authenticated '+kind+' backup without a unit digest remains restorable with original badges',async t=>{
 const f=fixture(t),before=historical(f,kind),source={envId:'forks',dbFile:f.file,historyDir:path.join(f.root,'source/history'),communityDir:path.join(f.root,'source/community'),musicDir:path.join(f.root,'source/music')};for(const name of ['historyDir','communityDir','musicDir'])fs.mkdirSync(source[name],{recursive:true});const keyFile=path.join(f.root,'key'),bundleDir=path.join(f.root,'bundle'),destinationDir=path.join(f.root,'restored');await run({action:'keygen',keyFile});await run({action:'export',source,sourceStopped:true,keyFile,outputDir:bundleDir});const file=path.join(bundleDir,'manifest.json'),manifest=JSON.parse(fs.readFileSync(file));manifest.code.maximumSchema=kind==='market17'?17:18;delete manifest.summary.database.achievementsSha256;delete manifest.authentication;const key=Buffer.from(hkdfSync('sha256',fs.readFileSync(keyFile),manifest.bundleId,'afterhours-data-manifest-v1',32));manifest.authentication=createHmac('sha256',key).update(canonical(manifest)).digest('hex');fs.writeFileSync(file,JSON.stringify(manifest));await run({action:'verify',bundleDir,keyFile});const restored=await run({action:'restore',bundleDir,keyFile,destinationDir,apply:true,expectedBundleId:manifest.bundleId});const db=openDatabase(settings(restored.config).dbFile);try{const after=rows(db);for(const name of Object.keys(before))assert.deepEqual(after[name].map(row=>Object.fromEntries(Object.keys(before[name][0]||row).map(key=>[key,row[key]]))),before[name].map(row=>({...row})),name);}finally{db.close();}
});
