const {test}=require('node:test'),assert=require('node:assert/strict');
const {mediaHarness,mediaSnapshot,roomState,deferred,json}=require('./helpers/media-browser.cjs');
const music=(id='music-a')=>({id,type:'music',title:'歌曲A',trackId:'track-a',durationSec:180,requestedById:'member',requestedByName:'點播的朋友'});
const queued=(id,type='music')=>({...music(id),type,...(type==='video'?{videoId:'M7lc1UVf-VE',title:'YouTube影片'}:{})});
const posts=f=>f.network.filter(request=>request.body),gets=f=>f.network.filter(request=>request.route.startsWith('/api/room-media?'));
function mutable(initial,options={}){let state=structuredClone(initial);const f=mediaHarness({...options,fetchHandler:async request=>{if(request.route==='/api/music')return json({tracks:[{id:'track-a',title:'歌曲A',author:'作者'}]});if(request.body){const body=request.body;state={...state,revision:state.revision+1};if(body.action==='reorder')state.queue=body.orderIds.map(id=>state.queue.find(item=>item.id===id));if(body.action==='remove')state.queue=state.queue.filter(item=>item.id!==body.itemId);if(body.action==='duration')state.current={...state.current,durationSec:body.durationSec};if(body.action==='pause'||body.action==='play')state.playback={...state.playback,state:body.action==='play'?'playing':'paused'};if(body.action==='seek')state.playback={...state.playback,anchorPositionSec:body.positionSec};}return json(state);}});return {f,get:()=>state,set:next=>{state=structuredClone(next);}};}
test('first room context fetches once even closed; unchanged markers and local timeline ticks never poll',async()=>{
 const initial=mediaSnapshot({current:null}),{f,set}=mutable(initial,{youtube:false});await f.update(roomState(initial,{media:null}));assert.equal(gets(f).length,1);assert.equal(f.node('tableMedia').open,false);assert.equal(f.node('tableMediaConsent').open,true);
 await f.click('mediaConsentDecline');for(let index=0;index<8;index++)await f.update(roomState(initial));await f.advance(10000);assert.equal(gets(f).length,1);assert.equal(f.thirdParty.length,0);
 await f.open();assert.equal(gets(f).length,2);assert.equal(f.network.filter(request=>request.route==='/api/music').length,1);await f.advance(5000);assert.equal(gets(f).length,2);
 const next=mediaSnapshot({current:null,revision:2});set(next);await f.update(roomState(next));assert.equal(gets(f).length,3);assert.equal(f.node('tableMediaConsent').open,false);
});
test('declining video loads no Google script or iframe; explicit later acceptance permits only the current video',async()=>{
 const initial=mediaSnapshot(),{f,set}=mutable(initial,{youtube:false});await f.update(roomState(initial));assert.equal(f.thirdParty.length,0);assert.equal(f.node('mediaPlayer').children.length,0);await f.click('mediaConsentDecline');await f.open();assert.equal(f.thirdParty.length,0);
 const next=mediaSnapshot({revision:2,current:{...initial.current,id:'video-b',videoId:'bZb4Zj7MfK0'}});set(next);await f.update(roomState(next));assert.equal(f.thirdParty.length,0);await f.click('mediaVideoJoin');assert.equal(f.thirdParty.length,1);f.installYT();await f.flush();assert.equal(f.players.length,1);assert.match(f.players[0].iframe.src,/bZb4Zj7MfK0/);assert.doesNotMatch(f.players[0].iframe.src,/M7lc1UVf-VE/);
});
test('room consent waits for hidden pages and existing game modals and is not shown again for the same seat',async()=>{
 const f=mediaHarness();const modal=f.otherModal();await f.update(roomState());assert.equal(f.node('tableMediaConsent').open,false);modal.close();f.emitMutations([{target:modal}]);assert.equal(f.node('tableMediaConsent').open,true);await f.click('mediaConsentDecline');await f.update(roomState());assert.equal(f.node('tableMediaConsent').open,false);
 const hidden=mediaHarness();hidden.hide(true);await hidden.update(roomState());assert.equal(hidden.node('tableMediaConsent').open,false);hidden.hide(false);assert.equal(hidden.node('tableMediaConsent').open,true);
});
test('mixed queue shows server titles, requester and type; members can enqueue but cannot reorder or transport',async()=>{
 const state=mediaSnapshot({isHost:false,canControl:false,canManageQueue:false,myPlayerId:'guest',queue:[queued('song'),queued('clip','video')]}),{f}=mutable(state);await f.update(roomState(state));await f.click('mediaConsentDecline');await f.open();
 const rows=f.node('mediaQueue').children;assert.equal(rows.length,2);assert.match(rows[0].getAttribute('aria-label'),/歌曲A.*歌曲.*點播的朋友/);assert.match(rows[1].getAttribute('aria-label'),/YouTube影片.*影片/);assert.equal(rows[0].draggable,false);assert.equal(f.node('mediaPlay').disabled,true);assert.equal(f.node('mediaSeek').disabled,true);
 rows[0].onkeydown({target:rows[0],key:'ArrowDown',preventDefault(){}});assert.equal(posts(f).length,0);f.node('mediaTrack').value='track-a';await f.submit('mediaMusicForm');assert.equal(posts(f).length,1);assert.equal(posts(f)[0].body.action,'enqueue');assert.equal(posts(f)[0].body.type,'music');
});
test('same-revision room permissions immediately promote and demote media controls',async()=>{
 const state=mediaSnapshot({isHost:false,canControl:false,canManageQueue:false,myPlayerId:'guest'}),{f}=mutable(state);await f.update(roomState(state));await f.click('mediaConsentDecline');assert.equal(f.node('mediaPlay').disabled,true);const count=gets(f).length;
 await f.update(roomState(state,{permissions:{role:'manager',canManageMedia:true,isHost:false}}));assert.equal(f.node('mediaPlay').disabled,false);assert.equal(f.node('mediaSeek').disabled,false);assert.equal(gets(f).length,count);
 await f.update(roomState(state,{permissions:{role:'member',canManageMedia:false,isHost:false}}));assert.equal(f.node('mediaPlay').disabled,true);f.node('mediaSeek').value='7';f.node('mediaSeek').onchange();await f.flush();assert.equal(posts(f).length,0);
});
test('manager keyboard and drag ordering send the complete current queue and expected revision once',async()=>{
 const initial=mediaSnapshot({queue:[queued('a'),queued('b'),queued('c')]}),{f}=mutable(initial);await f.update(roomState(initial));await f.click('mediaConsentDecline');await f.open();const middle=f.node('mediaQueue').children[1];middle.focus();middle.onkeydown({target:middle,key:'ArrowUp',preventDefault(){}});await f.flush();assert.deepEqual(posts(f)[0].body.orderIds,['b','a','c']);assert.equal(posts(f)[0].body.expectedRevision,1);assert.equal(f.document.activeElement,f.node('mediaQueue').children[0]);
 const row=f.node('mediaQueue').children[1],source=f.node('mediaQueue').children[2],transfer={setData(){},getData:()=> 'c'};source.ondragstart({preventDefault(){},dataTransfer:transfer});row.ondrop({preventDefault(){},dataTransfer:transfer});await f.flush();assert.deepEqual(posts(f)[1].body.orderIds,['b','c','a']);assert.equal(posts(f)[1].body.expectedRevision,2);assert.match(posts(f)[1].body.requestId,/^[a-f0-9-]{36}$/);assert.equal(posts(f)[1].body.roomInstanceId,'room-a');assert.equal(posts(f)[1].body.playbackSessionId,'session-a');
});
test('stale reorder adopts the server queue and leaves it for confirmation without automatically replaying the old order',async()=>{
 const initial=mediaSnapshot({queue:[queued('a'),queued('b')]}),newer=mediaSnapshot({revision:3,queue:[queued('a'),queued('b'),queued('other')]}),f=mediaHarness({fetchHandler:async request=>request.body?json({error:'stale',state:newer},{ok:false,status:409}):json(initial)});await f.update(roomState(initial));await f.click('mediaConsentDecline');const row=f.node('mediaQueue').children[1];row.onkeydown({target:row,key:'ArrowUp',preventDefault(){}});await f.flush();assert.equal(posts(f).length,1);assert.deepEqual(f.node('mediaQueue').children.map(item=>item.dataset.itemId),['a','b','other']);assert.match(f.node('mediaStatus').textContent,/確認/);
});
test('music to video to music stops the opposite player, including late Audio.play and old YouTube ready callbacks',async()=>{
 const first=mediaSnapshot({current:music(),playback:{state:'playing',anchorPositionSec:0,anchorServerMs:100000,rate:1}}),{f,set}=mutable(first,{pendingAudio:true,enabled:true});await f.update(roomState(first));await f.click('mediaConsentAccept');await f.open();await f.click('mediaResume');const old=f.audioClips[0];assert.ok(old.resolvePlay);
 const video=mediaSnapshot({revision:2});set(video);await f.update(roomState(video));assert.equal(old.paused,true);assert.equal(old.src,undefined);assert.equal(f.players.length,1);const previousVideo=f.players[0];previousVideo.ready();
 const final=mediaSnapshot({revision:3,current:music('music-b'),playback:first.playback});set(final);await f.update(roomState(final));assert.equal(previousVideo.destroyed,true);const fresh=f.audioClips.at(-1);assert.notEqual(fresh,old);fresh.resolvePlay();await f.flush();assert.equal(fresh.paused,false);old.resolvePlay();previousVideo.ready();await f.flush();assert.equal(old.paused,true);assert.equal(fresh.paused,false);assert.equal(f.players.length,1);
});
test('successive videos retire the old player even after the shared API has already loaded',async()=>{
 const initial=mediaSnapshot(),{f,set}=mutable(initial);await f.update(roomState(initial));await f.click('mediaConsentAccept');const old=f.players[0];old.ready();const next=mediaSnapshot({revision:2,current:{...initial.current,id:'next-video',videoId:'bZb4Zj7MfK0'},playbackSessionId:'session-b'});set(next);await f.update(roomState(next));assert.equal(old.destroyed,true);assert.equal(f.players.length,2);old.ready();assert.equal(f.players[1].destroyed,false);assert.match(f.players[1].iframe.src,/bZb4Zj7MfK0/);
});
test('pending API load cannot create an old iframe after the room changes or the current becomes music',async()=>{
 const first=mediaSnapshot(),{f,set}=mutable(first,{youtube:false});await f.update(roomState(first));await f.click('mediaConsentAccept');assert.equal(f.thirdParty.length,1);
 const next=mediaSnapshot({revision:2,current:music()});set(next);await f.update(roomState(next));f.installYT();await f.flush();assert.equal(f.players.length,0);assert.equal(f.node('mediaPlayer').children.length,0);assert.equal(f.audioClips.length,1);
 const other=mediaSnapshot({roomInstanceId:'room-b',myPlayerId:'other-seat',current:null});set(other);await f.update(roomState(other,{code:'DEF456'}));assert.equal(f.node('tableMediaConsent').open,true);assert.equal(f.audioClips[0].src,undefined);
});
test('blocked music and YouTube retain user-operated native controls, safe links and recoverable playback status',async()=>{
 const musicState=mediaSnapshot({current:music(),playback:{state:'playing',anchorPositionSec:0,anchorServerMs:100000,rate:1}}),{f}=mutable(musicState,{blockedAudio:true,enabled:true});await f.update(roomState(musicState));await f.click('mediaConsentDecline');await f.open();await f.click('mediaResume');assert.equal(f.audioClips[0].controls,true);assert.match(f.node('mediaPlaybackStatus').textContent,/原生播放/);
 const v=mediaHarness();await v.update(roomState());await v.click('mediaConsentAccept');const player=v.players[0];player.ready();player.blocked();assert.match(v.node('mediaPlaybackStatus').textContent,/在這裡播放/);assert.match(player.iframe.src,/controls=1/);assert.match(player.iframe.getAttribute('allow'),/autoplay/);
 for(const error of [101,150,153]){player.error(error);assert.equal(v.node('mediaNativeVideo').hidden,false);assert.match(v.node('mediaPlaybackStatus').textContent,/原生播放器/);}await v.update(roomState());assert.equal(v.node('mediaNativeVideo').hidden,false);await v.click('mediaNativeVideo');assert.equal(player.destroyed,true);assert.doesNotMatch(v.node('mediaPlayer').children[0].src,/enablejsapi/);assert.match(v.node('mediaYouTubeLink').href,/youtube\.com\/watch\?v=M7lc1UVf-VE/);assert.equal(posts(v).length,0);
});
test('paused alignment uses cue then pause; local native playback changes do not send shared transport commands',async()=>{
 const f=mediaHarness();await f.update(roomState());await f.click('mediaConsentAccept');const player=f.players[0];player.ready();assert.equal(player.calls.at(-1)[0],'pause');assert.ok(player.calls.some(call=>call[0]==='cue'&&call[1].startSeconds===12));
 player.state(1);player.state(2);player.state(3);await f.advance(3000);assert.equal(posts(f).length,0);await f.click('mediaAlign');assert.equal(posts(f).length,0);assert.equal(player.calls.at(-1)[0],'pause');
});
test('only current managers report video duration and ended once per revision/session with item identity',async()=>{
 const initial=mediaSnapshot({current:{...mediaSnapshot().current,durationSec:undefined},playback:{state:'playing',anchorPositionSec:0,anchorServerMs:100000,rate:1},isHost:false,isManager:true}),{f}=mutable(initial);await f.update(roomState(initial));await f.click('mediaConsentAccept');const player=f.players[0];player.duration=123;player.ready();player.ready();await f.flush();assert.equal(posts(f).filter(request=>request.body.action==='duration').length,1);assert.equal(posts(f)[0].body.itemId,'item-a');assert.equal(posts(f)[0].body.durationSec,123);
 await f.advance(121000);player.state(0);player.state(0);await f.flush();assert.equal(posts(f).filter(request=>request.body.action==='ended').length,1);assert.equal(posts(f).at(-1).body.itemId,'item-a');assert.equal(posts(f).at(-1).body.expectedRevision,2);
 const guestState={...initial,myPlayerId:'guest',isManager:false,canControl:false,canManageQueue:false},g=mutable(guestState).f;await g.update(roomState(guestState));await g.click('mediaConsentAccept');g.players[0].ready();g.players[0].state(0);await g.flush();assert.equal(posts(g).length,0);
});
test('late GET and POST from an old instance or seat cannot replace the new room snapshot or consent',async()=>{
 const oldGet=deferred(),newState=mediaSnapshot({roomInstanceId:'room-b',myPlayerId:'new-seat',current:null});let index=0;const f=mediaHarness({fetchHandler:request=>request.route==='/api/music'?json({tracks:[]}):++index===1?oldGet.promise:json(newState)});const initial=roomState();await f.update(initial);await f.update(roomState(newState,{code:'DEF456'}));oldGet.resolve(json(mediaSnapshot()));await f.flush();assert.equal(f.node('mediaCurrentTitle').textContent,'尚未播放');assert.equal(f.node('tableMediaConsent').open,true);assert.ok(f.network[0].options.signal.aborted);
 const oldPost=deferred(),a=mediaSnapshot();let active=a;const p=mediaHarness({fetchHandler:request=>request.body?oldPost.promise:json(active)});await p.update(roomState(a));await p.click('mediaConsentDecline');const pending=p.node('mediaPlay').click();active=newState;await p.update(roomState(newState,{code:'DEF456'}));oldPost.resolve(json({...a,revision:2}));await pending;await p.flush();assert.equal(p.node('mediaCurrentTitle').textContent,'尚未播放');assert.equal(p.node('mediaPlay').disabled,true);
});
test('a marker that advances during GET is retained and fetched once rather than overwritten by the older response',async()=>{
 const first=deferred(),newer=mediaSnapshot({revision:3,title:'unused'});let count=0;const f=mediaHarness({fetchHandler:()=>++count===1?first.promise:json(newer)});await f.update(roomState(mediaSnapshot({revision:2})));await f.update(roomState(newer));first.resolve(json(mediaSnapshot({revision:2})));await f.flush();assert.equal(gets(f).length,2);assert.equal(f.node('mediaCurrentTitle').textContent,newer.current.title);await f.update(roomState(newer));assert.equal(gets(f).length,2);
});
test('closing video, hiding or another modal stops this client without a room command',async()=>{
 for(const close of [f=>f.window.TableMedia.closeForDialog({}),f=>f.hide(true),f=>{const modal=f.otherModal();f.emitMutations([{target:modal}]);}]){const f=mediaHarness();await f.update(roomState());await f.click('mediaConsentAccept');f.players[0].ready();close(f);assert.equal(f.players[0].destroyed,true);assert.equal(posts(f).length,0);}
});
test('window keyboard move and resize stay local, retain the player and release pointer capture on close',async()=>{
 const f=mediaHarness();await f.update(roomState());await f.click('mediaConsentAccept');f.players[0].ready();await f.flushFrames();const player=f.players[0],iframe=player.iframe,network=f.network.length,calls=player.calls.length,bar=f.node('mediaWindowBar'),handle=f.node('mediaResize');
 bar.onkeydown({target:bar,key:'ArrowLeft',preventDefault(){}});handle.onkeydown({key:'ArrowDown',preventDefault(){}});await f.flushFrames();assert.equal(f.players.length,1);assert.equal(f.players[0].iframe,iframe);assert.equal(player.calls.length,calls);assert.equal(f.network.length,network);assert.ok(f.storage.has('bga.media.window.v1'));assert.ok(f.storage.has('bga.media.size.v1'));assert.ok(parseFloat(f.node('tableMedia').style.getPropertyValue('--media-player-height'))>=210);
 handle.onpointerdown({button:0,pointerId:7,clientX:500,clientY:500,preventDefault(){}});assert.equal(handle.hasPointerCapture(7),true);await f.click('mediaClose');assert.equal(handle.hasPointerCapture(7),false);assert.equal(f.frames.size,0);
});
test('visibility requires more than half the player area, including viewport and clipping ancestors',async()=>{
 for(const left of [980,1000]){const f=mediaHarness();f.node('mediaPlayer').rect={left,top:60,width:600,height:340,right:left+600,bottom:400};await f.update(roomState());await f.click('mediaConsentAccept');assert.equal(f.players.length,0);assert.match(f.node('mediaPlaybackStatus').textContent,/空間/);}
 const f=mediaHarness();await f.update(roomState());await f.click('mediaConsentAccept');f.players[0].ready();const watcher=f.observers.find(observer=>observer.target===f.players[0].iframe);watcher.emit([{intersectionRatio:.5}]);assert.equal(f.players[0].destroyed,true);
});
test('a failed revision refresh recovers from the same game marker with update-driven one-second retry and then stays quiet',async()=>{
 const initial=mediaSnapshot(),next=mediaSnapshot({revision:2,current:music()});let mediaGets=0;const f=mediaHarness({fetchHandler:request=>{if(request.route==='/api/music')return json({tracks:[]});mediaGets++;return mediaGets===1?json(initial):mediaGets===2?json({error:'temporary'},{ok:false,status:503}):json(next);}});await f.update(roomState(initial));await f.click('mediaConsentDecline');await f.update(roomState(next));assert.equal(gets(f).length,2);assert.equal(f.node('mediaCurrentTitle').textContent,'影片A');
 await f.advance(999);await f.update(roomState(next));assert.equal(gets(f).length,2);await f.advance(1);await f.update(roomState(next));assert.equal(gets(f).length,3);assert.equal(f.node('mediaCurrentTitle').textContent,'歌曲A');for(let index=0;index<10;index++)await f.update(roomState(next));assert.equal(gets(f).length,3);assert.equal(f.thirdParty.length,0);
});
test('snapshot retry budgets stop at three attempts, support markerless initial loads and restart only on manual open or new marker',async()=>{
 let failed=true;const empty=mediaSnapshot({current:null}),f=mediaHarness({fetchHandler:request=>request.route==='/api/music'?json({tracks:[]}):failed?json({error:'temporary'},{ok:false,status:503}):json(empty)}),state=roomState(empty,{media:null});await f.update(state);assert.equal(gets(f).length,1);
 await f.advance(1000);await f.update(state);assert.equal(gets(f).length,2);await f.advance(3999);await f.update(state);assert.equal(gets(f).length,2);await f.advance(1);await f.update(state);assert.equal(gets(f).length,3);await f.advance(10000);await f.update(state);assert.equal(gets(f).length,3);
 failed=false;await f.open();assert.equal(gets(f).length,4);assert.equal(f.node('mediaCurrentTitle').textContent,'尚未播放');await f.update(roomState(empty));assert.equal(gets(f).length,4);
});
test('closing cancels an in-flight snapshot and its late result cannot reopen video or replace the closed view',async()=>{
 const pending=deferred(),initial=mediaSnapshot(),later=mediaSnapshot({revision:2,current:{...initial.current,id:'late-video'}});let count=0;const f=mediaHarness({fetchHandler:request=>request.route==='/api/music'?json({tracks:[]}):++count===1?json(initial):pending.promise});await f.update(roomState(initial));await f.click('mediaConsentDecline');const opening=f.window.TableMedia.open();await f.flush();assert.equal(gets(f).length,2);await f.click('mediaClose');assert.equal(gets(f)[1].options.signal.aborted,true);pending.resolve(json(later));await opening;await f.flush();assert.equal(f.node('tableMedia').open,false);assert.equal(f.node('mediaCurrentTitle').textContent,'影片A');assert.equal(f.players.length,0);assert.equal(gets(f).length,2);
});
test('a new room instance starts a fresh retry budget and an old room reply cannot poison it',async()=>{
 const old=deferred(),next=mediaSnapshot({roomInstanceId:'room-b',current:null});let count=0;const f=mediaHarness({fetchHandler:request=>++count===1?old.promise:json(next)});await f.update(roomState());await f.update(roomState(next));assert.equal(gets(f).length,2);old.resolve(json({error:'old503'},{ok:false,status:503}));await f.flush();for(let index=0;index<5;index++)await f.update(roomState(next));assert.equal(gets(f).length,2);assert.equal(f.node('mediaCurrentTitle').textContent,'尚未播放');assert.doesNotMatch(f.node('mediaStatus').textContent,/old503/);
});
test('permission-denied snapshot retries stay stopped while timeout and malformed successful replies use the bounded budget',async()=>{
 for(const status of [401,403,404,422]){const f=mediaHarness({fetchHandler:()=>json({error:'denied'},{ok:false,status})});await f.update(roomState());await f.advance(20000);for(let index=0;index<10;index++)await f.update(roomState());assert.equal(gets(f).length,1);}
 for(const failure of [{ok:false,status:408,json:async()=>({error:'timeout'})},{ok:true,status:200,json:async()=>{throw Error('invalid JSON');}}]){let count=0;const f=mediaHarness({fetchHandler:()=>++count===1?failure:json(mediaSnapshot({current:null}))});await f.update(roomState(mediaSnapshot({current:null})));await f.advance(1000);await f.update(roomState(mediaSnapshot({current:null})));assert.equal(gets(f).length,2);assert.equal(f.node('mediaCurrentTitle').textContent,'尚未播放');}
});
test('an interrupted client reconnects on an unchanged marker without reopening a locally closed video',async()=>{
 const f=mediaHarness();await f.update(roomState());await f.click('mediaConsentAccept');f.players[0].ready();f.window.TableMedia.disconnected();assert.equal(f.players[0].destroyed,true);await f.update(roomState());assert.equal(gets(f).length,2);assert.equal(f.node('tableMedia').open,false);assert.equal(f.players.length,1);assert.equal(f.node('tableMediaConsent').open,false);
});
test('locally closing video stays closed across an idle current and a later queued video in the same instance',async()=>{
 const initial=mediaSnapshot(),{f,set}=mutable(initial);await f.update(roomState(initial));await f.click('mediaConsentAccept');await f.click('mediaClose');const idle=mediaSnapshot({revision:2,current:null});set(idle);await f.update(roomState(idle));const later=mediaSnapshot({revision:3,current:{...initial.current,id:'later-video'}});set(later);await f.update(roomState(later));assert.equal(f.players.length,1);assert.equal(f.node('tableMedia').open,false);await f.open();assert.equal(f.players.length,1);await f.click('mediaVideoJoin');assert.equal(f.players.length,2);
});
test('a clipping ancestor exposing exactly half the video stops playback while more than half stays eligible',async()=>{
 const f=mediaHarness();await f.update(roomState());await f.click('mediaConsentAccept');const player=f.players[0];player.ready();const parent=f.node('mediaPrimary');f.window.getComputedStyle=node=>({overflow:node===parent?'hidden':'visible'});parent.rect={left:30,top:60,width:361,height:340};await f.click('mediaAlign');assert.equal(player.destroyed,false);parent.rect.width=300;await f.click('mediaAlign');assert.equal(player.destroyed,true);assert.equal(posts(f).length,0);
});
test('a newer command acknowledgement makes an older failed GET harmless and uncertain commands retry the same UUID',async()=>{
 const pending=deferred(),initial=mediaSnapshot(),newer=mediaSnapshot({revision:2,playback:{...initial.playback,state:'playing'}});let get=0,write=0;const f=mediaHarness({fetchHandler:request=>{if(request.route==='/api/music')return json({tracks:[]});if(request.body){write++;if(write===1)throw Error('response lost');return json(newer);}return ++get===1?json(initial):pending.promise;}});await f.update(roomState(initial));await f.click('mediaConsentDecline');const opening=f.window.TableMedia.open();await f.flush();await f.click('mediaPlay');await f.click('mediaPlay');assert.equal(posts(f)[0].body.requestId,posts(f)[1].body.requestId);assert.equal(f.node('mediaPause').disabled,false);
 pending.resolve(json({error:'old503'},{ok:false,status:503}));await opening;await f.flush();assert.equal(f.node('mediaCurrentTitle').textContent,'影片A');assert.equal(f.node('tableMedia').open,true);assert.doesNotMatch(f.node('mediaStatus').textContent,/old503/);assert.equal(gets(f).length,2);
});
test('a stopped queue keeps play and skip available only to managers without starting from a member enqueue',async()=>{
 const initial=mediaSnapshot({current:null,queue:[queued('pending')]}),{f}=mutable(initial);await f.update(roomState(initial));await f.click('mediaConsentDecline');assert.equal(f.node('mediaPlay').disabled,false);assert.equal(f.node('mediaSkip').disabled,false);assert.equal(f.node('mediaPause').disabled,true);assert.equal(f.audioClips.length,0);
 await f.update(roomState(initial,{permissions:{role:'member',canManageMedia:false,isHost:false}}));assert.equal(f.node('mediaPlay').disabled,true);assert.equal(f.node('mediaSkip').disabled,true);
});
test('a queue update during dragging rejects the frozen stale intent and a fresh drag uses the new complete order',async()=>{
 const initial=mediaSnapshot({queue:[queued('a'),queued('b')]}),{f,set}=mutable(initial);await f.update(roomState(initial));await f.click('mediaConsentDecline');await f.open();const transfer={setData(){},getData:()=> 'b'};f.node('mediaQueue').children[1].ondragstart({preventDefault(){},dataTransfer:transfer});const newer=mediaSnapshot({revision:2,queue:[queued('a'),queued('b'),queued('other')]});set(newer);await f.update(roomState(newer));f.node('mediaQueue').children[0].ondrop({preventDefault(){},dataTransfer:transfer});await f.flush();assert.equal(posts(f).length,0);assert.match(f.node('mediaStatus').textContent,/重新拖曳/);
 f.node('mediaQueue').children[1].ondragstart({preventDefault(){},dataTransfer:transfer});f.node('mediaQueue').children[0].ondrop({preventDefault(){},dataTransfer:transfer});await f.flush();assert.deepEqual(posts(f)[0].body.orderIds,['b','a','other']);assert.equal(posts(f)[0].body.expectedRevision,2);
});
test('paused native playback, early local seek to end and unknown durations cannot advance the shared queue',async()=>{
 for(const changes of [{},{current:{...mediaSnapshot().current,durationSec:undefined},playback:{state:'playing',anchorPositionSec:0,anchorServerMs:100000,rate:1}}]){const state=mediaSnapshot(changes),{f}=mutable(state);await f.update(roomState(state));await f.click('mediaConsentAccept');f.players[0].state(0);await f.flush();assert.equal(posts(f).filter(request=>request.body.action==='ended').length,0);}
 const state=mediaSnapshot({playback:{state:'playing',anchorPositionSec:0,anchorServerMs:100000,rate:1}}),{f}=mutable(state);await f.update(roomState(state));await f.click('mediaConsentAccept');f.players[0].ready();await f.advance(10000);f.players[0].state(0);await f.flush();assert.equal(posts(f).length,0);await f.advance(88000);f.players[0].state(0);await f.flush();assert.equal(posts(f).filter(request=>request.body.action==='ended').length,1);
});
test('YouTube metadata above the API duration limit stays unknown instead of sending a truncated duration',async()=>{
 const state=mediaSnapshot({current:{...mediaSnapshot().current,durationSec:undefined},playback:{state:'playing',anchorPositionSec:0,anchorServerMs:100000,rate:1}}),{f}=mutable(state);await f.update(roomState(state));await f.click('mediaConsentAccept');const player=f.players[0];player.duration=14401;player.ready();player.state(1);player.state(0);await f.flush();assert.equal(posts(f).length,0);
});
