const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {fixture}=require('./helpers/ui-notifications.cjs');
const message=handle=>handle.element.children[1].children[0],close=handle=>handle.element.children.at(-1);
test('notifications expose safe polite content and a shared dismiss icon, accepting only same-origin actions',()=>{
 const f=fixture(),text='<img src=x onerror=alert(1)>\n完整錯誤訊息',handle=f.notify(text,{kind:'error',href:'javascript:alert(1)',label:'<b>惡意</b>'});assert.equal(message(handle).textContent,text);assert.equal(message(handle).innerHTML,'');assert.equal(handle.element.getAttribute('role'),'status');assert.equal(handle.element.getAttribute('aria-live'),'polite');assert.equal(handle.element.getAttribute('aria-atomic'),'true');assert.equal(handle.element.children[1].children.length,1);assert.equal(close(handle).dataset.icon,'close');assert.equal(close(handle).dataset.iconOnly,'true');assert.equal(close(handle).getAttribute('aria-label'),'關閉通知');
 for(const href of ['https://evil.test/x','//evil.test/x','\\\\evil.test/x','data:text/html,bad'])assert.equal(f.notify('不能外連 '+href,{href}).element.children[1].children.length,1);
 const link=f.notify('查看成就',{href:'/achievements?from=game',label:'<成就>'}).element.children[1].children[1];assert.equal(link.href,'/achievements?from=game');assert.equal(link.textContent,'<成就>');assert.equal(f.notify('  '),null);
});
test('only three notifications are visible and overflow has a bounded FIFO queue and idempotent disposal',()=>{
 const f=fixture(),handles=Array.from({length:20},(_,i)=>f.notify('通知 '+i,{key:'event:'+i}));assert.equal(f.state().visible,3);assert.equal(f.state().queued,12);assert.equal(f.state().timers,3);assert.equal(handles[3].element.isConnected,false);assert.equal(handles[3].element.listeners.get('pointerenter').size,0,'discarded queue entries release listeners');assert.equal(handles[3].dismiss(),false);
 handles[0].dismiss();assert.equal(f.state().visible,3);assert.equal(f.state().queued,11);assert.equal(handles[8].element.isConnected,true,'the oldest retained queue entry becomes visible');assert.equal(f.state().timers,3);assert.equal(handles[0].dismiss(),false);f.ui.notifications.clear();assert.equal(f.state().visible,0);assert.equal(f.state().queued,0);assert.equal(f.timers.size,0);assert.equal(f.document.body.children.length,0);
});
test('semantic keys dedupe active and completed events without extending expiry and the seen set stays bounded',async()=>{
 const f=fixture(),first=f.notify('同一事件',{key:'same',durationMs:3000});await f.tick(2000);assert.equal(f.notify('別的字但同一事件',{key:'same'}),first);await f.tick(1000);assert.equal(first.element.isConnected,false);assert.equal(f.notify('已結束事件',{key:'same'}),null);
 for(let i=0;i<300;i++){const handle=f.notify('event '+i,{key:'bounded:'+i});handle.dismiss();}assert.equal(f.state().seen,256);assert.ok(f.notify('已淘汰的記憶',{key:'bounded:0'}));
});
test('hover and keyboard focus pause the remaining expiry, and moving focus inside a card stays paused',async()=>{
 const f=fixture(),handle=f.notify('可以慢慢讀',{durationMs:5000,href:'/achievements'});await f.tick(1800);handle.element.dispatch('pointerenter');await f.tick(10000);assert.equal(handle.element.isConnected,true);handle.element.dispatch('focusin');handle.element.dispatch('pointerleave');await f.tick(10000);assert.equal(handle.element.isConnected,true);handle.element.dispatch('focusout',{relatedTarget:close(handle)});assert.equal(f.state().timers,0);handle.element.dispatch('focusout',{relatedTarget:null});await f.tick(3199);assert.equal(handle.element.isConnected,true);await f.tick(1);assert.equal(handle.element.isConnected,false);
});
test('dismiss by keyboard returns to its connected origin without grabbing focus for a new notification',()=>{
 const f=fixture(),origin=new f.Node('button');f.document.body.append(origin);origin.focus();const handle=f.notify('邀請已複製');assert.equal(f.document.activeElement,origin);close(handle).click();assert.equal(handle.element.isConnected,false);assert.equal(f.document.activeElement,origin);assert.equal(f.timers.size,0);
});
test('hidden pages retain readable content, cancel animation and particles and never replay old or queued effects',async()=>{
 const f=fixture(),first=f.notify('已解鎖',{key:'earned:first',celebrate:true});await f.tick(1000);f.hide(true);assert.equal(first.element.isConnected,true);assert.equal(message(first).textContent,'已解鎖');assert.equal(f.state().timers,0);assert.equal(f.animations[0].cancelled,true);assert.equal(f.celebrations[0].cancelled,true);const hidden=f.notify('背景新成就',{key:'earned:hidden',celebrate:true});await f.tick(20000);assert.equal(hidden.element.isConnected,true);f.hide(false);assert.equal(f.animations.length,1);assert.equal(f.celebrations.length,1);await f.tick(3999);assert.equal(first.element.isConnected,true);await f.tick(1);assert.equal(first.element.isConnected,false);assert.equal(hidden.element.isConnected,true);
 const backlog=fixture();Array.from({length:4},(_,i)=>backlog.notify('佇列 '+i,{key:'queue:'+i,celebrate:true}));backlog.hide(true);backlog.hide(false);const count=backlog.celebrations.length;await backlog.tick(5000);assert.equal(backlog.celebrations.length,count,'a formerly hidden queued event cannot celebrate later');
});
test('reduced motion and disabled policy show static notifications and suppress canceled effects after reenabling',()=>{
 for(const options of [{reduced:true},{enabled:false},{policy:false,reduced:true}]){const f=fixture(options),handle=f.notify('靜態成就',{celebrate:true});assert.equal(handle.element.isConnected,true);assert.equal(f.animations.length,0);assert.equal(f.celebrations.length,0);}
 const f=fixture();f.notify('有動效',{key:'one',celebrate:true});f.reduce(true);assert.equal(f.animations[0].cancelled,true);assert.equal(f.celebrations[0].cancelled,true);f.reduce(false);f.enable(false);f.enable(true);assert.equal(f.animations.length,1);assert.equal(f.celebrations.length,1);assert.equal(f.state().visible,1);
});
test('queued notifications that become stale do not start delayed decoration or particles',async()=>{
 const f=fixture();const handles=Array.from({length:4},(_,i)=>f.notify('成就 '+i,{key:'stale:'+i,celebrate:true,durationMs:3000}));assert.equal(f.celebrations.length,3);await f.tick(3000);assert.equal(handles[3].element.isConnected,true);assert.equal(f.celebrations.length,3);assert.equal(f.animations.length,3);
});
test('external node or host removal releases each timer, event listener and celebration handle',()=>{
 const f=fixture(),first=f.notify('移除我',{celebrate:true}),second=f.notify('保留我',{celebrate:true});first.element.remove();f.mutate();assert.equal(f.state().visible,1);assert.equal(f.timers.size,1);assert.equal(first.element.listeners.get('focusin').size,0);assert.equal(f.celebrations[0].cancelled,true);second.element.parentNode.remove();f.mutate();assert.equal(f.state().visible,0);assert.equal(f.timers.size,0);assert.equal(f.celebrations[1].cancelled,true);assert.ok(f.notify('下次還能顯示'));
});
test('pagehide removes the stack, queue, listeners, timers and effects; repeated disposal is safe',()=>{
 const f=fixture();Array.from({length:5},(_,i)=>f.notify('離頁 '+i,{key:'leave:'+i,celebrate:true}));f.window.dispatch('pagehide',{persisted:false});assert.equal(f.state().disposed,true);assert.equal(f.state().visible,0);assert.equal(f.state().queued,0);assert.equal(f.state().seen,0);assert.equal(f.timers.size,0);assert.equal(f.subscriptions.size,0);assert.equal(f.observers[0].disconnected,true);assert.ok(f.celebrations.every(item=>item.cancelled));assert.equal(f.document.listeners.get('visibilitychange').size,0);assert.equal(f.media.listeners.get('change').size,0);assert.equal(f.notify('已離頁'),null);f.ui.notifications.destroy();
});
test('BFCache suspends every old card and effect, then accepts only future notifications on return',()=>{
 const f=fixture(),old=f.notify('離開前成就',{key:'before',celebrate:true});f.window.dispatch('pagehide',{persisted:true});assert.equal(old.element.isConnected,false);assert.equal(f.timers.size,0);assert.equal(f.state().suspended,true);assert.equal(f.state().disposed,false);assert.equal(f.observers[0].disconnected,true);assert.equal(f.notify('離頁中的晚回覆'),null);assert.equal(f.celebrations[0].cancelled,true);f.window.dispatch('pageshow',{persisted:true});assert.equal(f.state().suspended,false);assert.equal(f.state().visible,0);assert.equal(f.notify('舊事件',{key:'before'}),null);const next=f.notify('之後的新事件',{key:'after',celebrate:true});assert.equal(next.element.isConnected,true);assert.equal(f.celebrations.length,2);assert.equal(f.observers.length,2);assert.equal(f.state().timers,1);
});
test('before DOM ready queues stay bounded, then mount only three cards; optional particle failures are harmless',()=>{
 const f=fixture({body:false,celebration:false});const handles=Array.from({length:14},(_,i)=>f.notify('等待 body '+i,{key:'ready:'+i,celebrate:true}));assert.equal(f.state().visible,0);assert.equal(f.state().queued,12);assert.equal(f.timers.size,0);f.attachBody();assert.equal(f.state().visible,3);assert.equal(f.state().queued,9);assert.equal(handles[2].element.isConnected,true);f.ui.notifications.clear();f.ui.celebrate=()=>{throw Error('context unavailable');};const fallback=f.notify('可退回的成就',{celebrate:true});assert.equal(fallback.element.isConnected,true);f.ui.notifications.clear();assert.equal(f.timers.size,0);
});
test('local notification duration is clamped and duplicate unkeyed messages dedupe only while active',async()=>{
 const f=fixture(),short=f.notify('短通知',{durationMs:1});assert.equal(f.notify('短通知'),short);await f.tick(2999);assert.equal(short.element.isConnected,true);await f.tick(1);assert.equal(short.element.isConnected,false);const again=f.notify('短通知',{durationMs:Infinity});assert.notEqual(again,short);await f.tick(5000);assert.equal(again.element.isConnected,false);const long=f.notify('完整長訊息 '.repeat(400),{durationMs:999999});assert.equal(message(long).textContent,'完整長訊息 '.repeat(400).trim());await f.tick(12000);assert.equal(long.element.isConnected,false);
});
test('notification styles keep content above local particles, preserve wrapping and avoid permanent animations',()=>{
 const css=fs.readFileSync(path.join(__dirname,'../public/shared/ui-notifications.css'),'utf8');assert.match(css,/\.ui-notification\{position:relative;isolation:isolate/);assert.match(css,/\.ui-notification-icon,\.ui-notification-content,\.ui-notification-close\{position:relative;z-index:1/);assert.match(css,/overflow-wrap:anywhere;white-space:pre-wrap/);assert.match(css,/max-height:calc\(100dvh - 24px\);overflow:auto/);assert.match(css,/\.ui-notification\[hidden\].*display:none!important/);assert.doesNotMatch(css,/infinite|text-overflow:ellipsis|animation:/);
});

function trackerClient(f,onEarned){
 const requests=[];f.context.fetch=(route,options)=>{let resolve;const promise=new Promise(done=>{resolve=done;});requests.push({route,options,resolve});return promise;};
 const tracker=f.ui.createAchievementTracker({onEarned});return {tracker,requests,reply(index,achievements,{ok=true,jsonError=false}={}){requests[index].resolve({ok,json:async()=>{if(jsonError)throw Error('invalid body');return {achievements};}});}};
}

test('achievement snapshots reject malformed replies, retain every server ID, and static hidden/reduced notifications never replay celebration',async()=>{
 const f=fixture(),announced=[],client=trackerClient(f,items=>{for(const item of items){announced.push(item.id);f.notify(String(item.title||item.id),{key:'achievement:'+item.id,celebrate:true});}}),old={id:'old',unlockedAt:'2026-10-01'},first={id:'new-server-id',title:'<img src=x onerror=bad()>',unlockedAt:'2026-10-07'},second={id:'missing-title',unlockedAt:'2026-10-07'};
 for(const [items,options]of [[null,{}],[[old],{ok:false}],[[old],{jsonError:true}]]){const request=client.tracker.check();client.reply(client.requests.length-1,items,options);await request;assert.equal(client.tracker.getState().baseline,false);assert.equal(announced.length,0);}
 const baseline=client.tracker.check();client.reply(3,[old]);await baseline;f.hide(true);const hidden=client.tracker.check();client.reply(4,[old,first,second,{...first},null,{id:7,unlockedAt:'x'}]);await hidden;assert.deepEqual(announced,[first.id,second.id]);assert.equal(client.tracker.getState().known,3);assert.equal(f.celebrations.length,0);assert.equal(f.animations.length,0);const content=f.document.body.children[0].children.map(node=>node.children[1].children[0]);assert.equal(content[0].textContent,first.title);assert.equal(content[0].innerHTML,'');assert.equal(content[1].textContent,second.id);
 f.hide(false);f.reduce(true);const next=client.tracker.check();client.reply(5,[old,first,second,{id:'reduced-earned',unlockedAt:'2026-10-07'}]);await next;f.reduce(false);assert.equal(f.celebrations.length,0);assert.equal(f.animations.length,0);assert.equal(client.requests.length,6);assert.ok(client.requests.every(request=>request.route==='/api/achievements'));f.ui.notifications.destroy();assert.equal(f.timers.size,0);
});

test('achievement tracker instances and requests are bounded and disposal resolves jobs without late callbacks or replacement reads',async()=>{
 const f=fixture(),requests=[],earned=[];f.context.fetch=(route,options)=>{let resolve;const promise=new Promise(done=>{resolve=done;});requests.push({route,options,resolve});return promise;};const clients=[],pending=[];
 for(let index=0;index<9;index++){const tracker=f.ui.createAchievementTracker({onEarned:items=>earned.push(...items)});clients.push(tracker);pending.push(tracker.check());}assert.equal(f.state().trackers,8);assert.equal(clients[0].getState().disposed,true);assert.equal(requests[0].options.signal.aborted,true);assert.equal(f.timers.size,8);f.ui.notifications.destroy();await Promise.all(pending);assert.equal(f.state().trackers,0);assert.equal(f.timers.size,0);assert.ok(requests.every(request=>request.options.signal.aborted));for(const request of requests)request.resolve({ok:true,json:async()=>({achievements:[{id:'late',unlockedAt:'x'}]})});await f.flush();await clients[8].check();await f.ui.createAchievementTracker({onEarned:items=>earned.push(...items)}).check();assert.equal(requests.length,9);assert.equal(earned.length,0);
});

test('destroying a tracker during response-body parsing prevents a stale success from establishing its baseline',async()=>{
 const f=fixture();let resolveBody;const client=trackerClient(f,()=>assert.fail('destroyed tracker must not notify')),pending=client.tracker.check();client.requests[0].resolve({ok:true,json:()=>new Promise(resolve=>{resolveBody=resolve;})});await f.flush();assert.equal(typeof resolveBody,'function');client.tracker.destroy();await pending;resolveBody({achievements:[{id:'late',unlockedAt:'x'}]});await f.flush();assert.equal(client.tracker.getState().baseline,false);assert.equal(f.state().trackers,0);assert.equal(f.timers.size,0);assert.equal(client.requests.length,1);f.ui.notifications.destroy();
});
