const {test}=require('node:test'),assert=require('node:assert/strict');
const {controller}=require('./helpers/notifications-game-client.cjs');
const {browserHarness,drawingState}=require('./helpers/draw-browser.cjs');
const {fixture}=require('./helpers/ui-notifications.cjs');
for(const file of ['app.js','gift.js','majority.js','race.js']){
 test(file+' applies its initial baseline before a settlement reply that arrives first',async t=>{
  const f=controller(file),old={id:'old-earned',title:'以前取得',unlockedAt:'2026-10-01'},fresh={id:'new-earned',title:'這次新取得',unlockedAt:'2026-10-07'};t.after(()=>f.emit('pagehide',{persisted:false}));assert.equal(f.achievementRequests.length,1);const settled=f.check();assert.equal(f.achievementRequests.length,2);f.reply(1,[old,fresh]);await f.flush();assert.equal(f.notifications.length,0,'a finishing response waits for its original baseline');f.reply(0,[old]);await settled;await f.flush();assert.deepEqual(f.notifications.map(item=>item.options.key),['achievement:new-earned']);assert.equal(f.achievementRequests.length,2,'exactly the existing initial and semantic reads');
 });
 test(file+' failed initial baseline keeps the first successful snapshot silent and later snapshots cannot shrink known IDs',async t=>{
  const f=controller(file),old={id:'old-earned',title:'以前取得',unlockedAt:'2026-10-01'},fresh={id:'new-earned',title:'這次新取得',unlockedAt:'2026-10-07'};t.after(()=>f.emit('pagehide',{persisted:false}));const firstSuccess=f.check();f.reply(1,[old]);await f.flush();f.reply(0,[],{ok:false});await firstSuccess;assert.equal(f.notifications.length,0);assert.equal(f.tracker().getState().known,1);
  const newer=f.check(),stale=f.check();f.reply(3,[old]);await f.flush();f.reply(2,[old,fresh]);await Promise.all([newer,stale]);assert.equal(f.tracker().getState().known,2);const same=f.check();f.reply(4,[old,fresh]);await same;assert.deepEqual(f.notifications.map(item=>item.options.key),['achievement:new-earned']);assert.equal(f.achievementRequests.length,5,'one read per existing check, without retries');
 });
}
test('twenty actual drawing Arrow key events immediately expose the final position without queueing old coordinates',async t=>{
 const game=browserHarness(),notifications=fixture();notifications.ui.setStatus=(node,text)=>{node.textContent=text;};game.context.window.GameUI=notifications.ui;game.receive(drawingState('artist'));await new Promise(resolve=>setImmediate(resolve));t.after(()=>{game.context.clearTimeout(game.context.toast.timer);game.listeners.get('window:pagehide')({persisted:false});notifications.ui.notifications.destroy();});const before=notifications.state(),key=game.listeners.get('#drawCanvas:keydown');assert.equal(typeof key,'function');for(let index=0;index<20;index++)key({key:'ArrowRight',preventDefault(){}});
 const visible=node=>node.hidden||node.style?.display==='none'?'':node.textContent+' '+node.children.map(visible).join(' '),text=visible(notifications.document.body)+' '+visible(game.element('#toast'));assert.match(text,/畫布位置 277，129/);assert.equal(notifications.state().queued,0,'continuous keyboard status must not enter the event FIFO');assert.equal(notifications.state().visible,before.visible);assert.equal(notifications.state().seen,before.seen);
});

test('real poker controller bounds outstanding semantic checks, preserves the first baseline and newest full snapshot without extra reads',async t=>{
 const f=controller('app.js'),old={id:'old-earned',title:'以前取得',unlockedAt:'2026-10-01'},all=Array.from({length:20},(_,index)=>({id:'earned-'+index,title:'新成就 '+index,unlockedAt:'2026-10-07'}));t.after(()=>f.emit('pagehide',{persisted:false}));const checks=Array.from({length:20},()=>f.check());assert.equal(f.achievementRequests.length,21);assert.equal(f.tracker().getState().pending,8);assert.ok(f.timers.size<=8,'only retained jobs own a timeout');assert.equal(f.achievementRequests.filter(request=>request.options.signal.aborted).length,13);
 for(let index=1;index<21;index++)f.reply(index,[old,...all]);await f.flush();assert.equal(f.notifications.length,0);f.reply(0,[old]);await Promise.all(checks);await f.flush();assert.deepEqual(f.notifications.map(item=>item.options.key),all.map(item=>'achievement:'+item.id));assert.equal(f.tracker().getState().pending,0);assert.equal(f.tracker().getState().known,21);assert.equal(f.achievementRequests.length,21);assert.equal(f.window.GameUI.notifications.getState().visible,3);assert.equal(f.window.GameUI.notifications.getState().queued,12);
});

test('a stalled controller baseline times out once; later successful data is a silent baseline and abandoned late replies cannot announce',async t=>{
 const f=controller('gift.js'),old={id:'old-earned',unlockedAt:'2026-10-01'},fresh={id:'new-earned',title:'這次新取得',unlockedAt:'2026-10-07'};t.after(()=>f.emit('pagehide',{persisted:false}));const next=f.check();f.reply(1,[old]);await f.flush();await f.advance(10000);await next;assert.equal(f.achievementRequests[0].options.signal.aborted,true);assert.equal(f.tracker().getState().pending,0);assert.equal(f.tracker().getState().baseline,true);assert.equal(f.notifications.length,0);f.reply(0,[old,fresh]);await f.flush();assert.equal(f.notifications.length,0);assert.equal(f.tracker().getState().known,1);const newCheck=f.check();f.reply(2,[old,fresh]);await newCheck;assert.deepEqual(f.notifications.map(item=>item.options.key),['achievement:new-earned']);await f.advance(60000);assert.equal(f.achievementRequests.length,3,'timeout and idle do not start an automatic GET');
});

test('real controller BFCache cancels pending reads, retains its established baseline, and ignores old completions after return',async t=>{
 const f=controller('app.js'),old={id:'old-earned',unlockedAt:'2026-10-01'},fresh={id:'new-earned',title:'之後新取得',unlockedAt:'2026-10-07'},abandoned={id:'late-abandoned',unlockedAt:'2026-10-07'};t.after(()=>f.emit('pagehide',{persisted:false}));f.reply(0,[old]);await f.flush();const pending=f.check();f.emit('pagehide',{persisted:true});await pending;assert.equal(f.achievementRequests[1].options.signal.aborted,true);assert.equal(f.tracker().getState().pending,0);assert.equal(f.tracker().getState().known,1);assert.equal(f.timers.size,0);await f.check();assert.equal(f.achievementRequests.length,2,'suspended controllers cannot start reads');f.emit('pageshow',{persisted:true});assert.equal(f.achievementRequests.length,2,'restoring the helper does not fetch or replay');f.reply(1,[old,abandoned]);await f.flush();assert.equal(f.notifications.length,0);const future=f.check();f.reply(2,[old,fresh]);await future;assert.deepEqual(f.notifications.map(item=>item.options.key),['achievement:new-earned']);assert.equal(f.achievementRequests.length,3);
});

test('ordinary pagehide aborts controller requests and prevents late awards or new calls',async()=>{
 const f=controller('race.js'),next=f.check();f.emit('pagehide',{persisted:false});await next;assert.equal(f.tracker().getState().disposed,true);assert.equal(f.window.GameUI.notifications.getState().trackers,0);assert.ok(f.achievementRequests.every(request=>request.options.signal.aborted));for(let index=0;index<2;index++)f.reply(index,[{id:'late',unlockedAt:'2026-10-07'}]);await f.flush();await f.check();assert.equal(f.notifications.length,0);assert.equal(f.achievementRequests.length,2);assert.equal(f.timers.size,0);
});
