const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
const {dom}=require('./helpers/widget-dom.cjs'),R=require('../public/market-rules');
const read=file=>fs.readFileSync(path.join(__dirname,'../public/',file),'utf8'),pause=()=>new Promise(resolve=>setImmediate(resolve));
const deferred=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};
function runtime(page,{search='',hash='',fetch}={}){
 const f=dom(read(page+'.html')),listeners=new Map(),intervals=new Map(),frames=new Map(),storage=new Map();let elapsed=0,nextFrame=0;
 const location={origin:'https://example.test',pathname:'/'+page,search,hash,href:''},document=f.document;
 const context=vm.createContext({document,location,history:{replaceState(_state,_title,href){const next=new URL(href,location.origin);location.pathname=next.pathname;location.search=next.search;location.hash=next.hash;}},fetch,URL,URLSearchParams,Date,Intl,Set,Map,WeakMap,WeakSet,Promise,encodeURIComponent,Uint8Array,crypto:webcrypto,performance:{now:()=>elapsed},MutationObserver:f.MutationObserver,
  addEventListener(type,fn){const list=listeners.get(type)||[];list.push(fn);listeners.set(type,list);},removeEventListener(type,fn){listeners.set(type,(listeners.get(type)||[]).filter(item=>item!==fn));},dispatchEvent(event){for(const fn of listeners.get(event.type)||[])fn(event);},
  localStorage:{getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)},matchMedia:()=>({matches:false,addEventListener(){},removeEventListener(){}}),requestAnimationFrame(fn){const id=++nextFrame;frames.set(id,fn);return id;},cancelAnimationFrame:id=>frames.delete(id),setInterval(fn,delay){intervals.set(delay,fn);},clearInterval(){},setTimeout,clearTimeout,
  Option:class extends f.Element{constructor(text,value){super('option');this.textContent=text;this.value=value;}},Event:class{constructor(type){this.type=type;}},confirm:()=>true,
  AudioSettings:{bindPreview:()=>()=>{}},FileReader:class{readAsDataURL(file){this.result='data:'+file.type+';base64,aGVsbG8=';Promise.resolve().then(()=>this.onload());}},MarketRules:R
 });context.window=context;
 vm.runInContext(read('shared/ui-components.js'),context,{filename:'ui-components.js'});vm.runInContext(read('shared/ui-widgets.js'),context,{filename:'ui-widgets.js'});vm.runInContext(read(page+'.js'),context,{filename:page+'.js'});
 return {...f,context,location,intervals,frames,dispatch(type,extra={}){for(const fn of listeners.get(type)||[])fn({type,...extra});},async settle(){for(let i=0;i<3;i++)await pause();},async tick(delay){elapsed+=delay;await intervals.get(delay)?.();await pause();}};
}
function collection({search='',hook}={}){
 const calls=[],profile={appearance:{version:5,characterId:'builtin:traveler',expression:'neutral'},avatar:{kind:'character',characterId:'builtin:traveler',expression:'neutral'}},artworks=[{id:'art-a',name:'收藏頭像',url:'/assets/art-a',owned:true,shared:false}],characters=[{id:'builtin:traveler',name:'旅行者',owned:false,expressions:{neutral:'/assets/traveler'}}],tracks=[{id:'song-a',title:'歌A',author:'玩家',duration:30,ownerId:'member'}];
 const fetch=async(url,options={})=>{const body=options.body?JSON.parse(options.body):null;calls.push({url,body});if(hook){const result=await hook({url,body});if(result)return result;}
  let value;if(url==='/api/collection/avatars')value={artworks};else if(url==='/api/profile/options')value={characters};else if(url==='/api/profile/settings'){if(body)Object.assign(profile,body);value=profile;}else if(url==='/api/music')value={tracks,me:'member',admin:false};else if(url==='/api/artworks'&&body){artworks.push({id:'art-b',name:body.name,url:'/assets/art-b',owned:true,shared:false});value={id:'art-b'};}else throw Error('Unexpected collection route '+url);return Response.json(value);};
 return {...runtime('collection',{search,fetch}),calls,profile};
}
function market({role='member',hash='',hook}={}){
 const calls=[],round={id:'round-a',targetDate:'2027-01-04',cutoffAt:R.cutoffFor('2027-01-04'),settlementAfter:R.settlementFor('2027-01-04'),rules:R.snapshot(),phase:'closed',vote:null,result:null,voteCount:2,settlementHistory:[]},state={me:{id:'member',username:'member',displayName:'玩家',role},serverNow:'2027-01-04T08:00:00Z',rules:R.snapshot(),stats:{score:7,hits:2,played:3},ledger:[],rounds:[round]},pending=[{id:'img-a',version:1,authorName:'作者',buckets:['dip'],weekdays:[1],width:32,height:32,status:'pending',createdAt:'2027-01-03T08:00:00Z'}];
 const fetch=async(url,options={})=>{const body=options.body?JSON.parse(options.body):null;calls.push({url,body});if(hook){const result=await hook({url,body});if(result)return result;}
  let value;if(url==='/api/market'||url==='/api/admin/market')value=state;else if(url==='/api/market/images/draw')value={targetDate:body.targetDate,images:{}};else if(url==='/api/market/images/mine')value={images:[],limits:{}};else if(url.startsWith('/api/admin/market/images')&&!body)value={images:pending.filter(image=>image.status==='pending'),limits:{}};
  else if(url==='/api/admin/market/preview')value={targetDate:round.targetDate,returnPct:Number(body.returnPct),bucket:'rally',voteCount:2,counts:{hit:1,miss:1,tie:0},ownPrevious:0,ownNext:5,ownScoreAfter:12};else if(url==='/api/admin/market/settle')value={ok:true};else if(url==='/api/admin/market/images/approve'){for(const image of pending)if(body.images.some(ref=>ref.id===image.id))image.status='approved';value={ok:true};}else throw Error('Unexpected market route '+url);return Response.json(value);};
 return {...runtime('market',{hash,fetch}),calls,state,pending};
}
test('collection real client and shared tabs preserve section deep links, manual focus and music pause without HTTP on arrows',async()=>{
 const f=collection({search:'?section=music&from=room'});await f.settle();assert.equal(f.node('collection-tab-music').getAttribute('aria-selected'),'true');assert.equal(f.node('section-music').hidden,false);const audio=f.node('music-grid').querySelector('audio'),calls=f.calls.length;
 f.node('collection-tab-music').focus();f.node('collection-tab-music').dispatch('keydown',{key:'Home'});assert.equal(f.document.activeElement,f.node('collection-tab-avatars'));assert.equal(f.node('section-music').hidden,false);assert.equal(f.calls.length,calls);assert.equal(audio.pauses,0);
 f.node('collection-tab-avatars').dispatch('keydown',{key:'Enter'});assert.equal(f.node('section-music').hidden,true);assert.equal(audio.pauses,1);assert.equal(f.location.search,'?section=avatars&from=room');assert.equal(f.calls.length,calls);
 f.location.search='?section=characters';f.dispatch('popstate');assert.equal(f.node('section-characters').hidden,false);assert.equal(f.node('collection-tab-characters').getAttribute('aria-selected'),'true');assert.equal(f.calls.length,calls);
});
test('collection real upload validation leaves status intact, preserves server errors and locks duplicate submission',async()=>{
 const wait=deferred();let hold=false;const f=collection({hook:({url})=>hold&&url==='/api/artworks'?wait.promise:undefined});await f.settle();const form=f.node('avatar-upload'),status=form.querySelector('[role=status]'),button=form.querySelector('button[type=submit]');status.textContent='先前伺服器提示';const before=f.calls.length;
 await form.onsubmit({target:form,preventDefault(){}});assert.equal(f.calls.length,before);assert.equal(status.textContent,'先前伺服器提示');assert.equal(form.elements.name.getAttribute('aria-invalid'),'true');assert.ok(form.elements.name.getAttribute('aria-describedby'));
 form.elements.name.value='新圖片';form.elements.name.dispatch('input');form.elements.file.files=[{size:80,type:'image/png'}];form.elements.file.dispatch('change');hold=true;const submitted=form.onsubmit({target:form,preventDefault(){}});await f.settle();assert.equal(button.disabled,true);assert.equal(status.textContent,'處理中…');assert.equal(f.calls.filter(call=>call.url==='/api/artworks').length,1);
 await form.onsubmit({target:form,preventDefault(){}});assert.equal(f.calls.filter(call=>call.url==='/api/artworks').length,1);wait.resolve(Response.json({error:'上傳失敗，請保留檔案重試'},{status:500}));await submitted;assert.equal(button.disabled,false);assert.equal(status.textContent,'上傳失敗，請保留檔案重試');assert.equal(form.elements.name.value,'新圖片');assert.equal(form.elements.file.files.length,1);assert.equal(form.querySelectorAll('[data-ui-field-error]').length,0);
});
test('collection card selection waits for acknowledgement and preserves readable names with icon actions',async()=>{
 const f=collection();await f.settle();const card=f.node('avatars-grid').querySelector('[data-selection="artwork:art-a"]'),button=card.querySelector('button');assert.equal(card.dataset.selected,'false');assert.equal(card.querySelector('h3').textContent,'收藏頭像');assert.equal(button.getAttribute('aria-label'),'設為頭像');assert.equal(button.dataset.uiIcon,'check');
 await button.click().returned;assert.equal(card.dataset.selected,'true');assert.equal(card.querySelector('.collection-current').textContent,'使用中');assert.equal(f.profile.avatar.artworkId,'art-a');
});
test('collection successful upload clears field feedback without hiding success, and pagehide releases widgets while pausing audio',async()=>{
 const f=collection();await f.settle();const form=f.node('avatar-upload'),status=form.querySelector('[role=status]');await form.onsubmit({target:form,preventDefault(){}});assert.equal(form.querySelectorAll('[data-ui-field-error]').length,2);form.elements.name.value='上傳成功';form.elements.file.files=[{type:'image/png',size:80}];await form.onsubmit({target:form,preventDefault(){}});await f.settle();assert.equal(status.textContent,'已加入收藏庫。');assert.equal(form.elements.name.value,'');assert.equal(form.elements.file.files.length,0);assert.equal(form.querySelectorAll('[data-ui-field-error]').length,0);assert.equal(form.elements.name.getAttribute('aria-invalid'),null);assert.equal(form.elements.name.getAttribute('aria-describedby'),null);assert.equal(f.node('avatars-count').textContent,'3 張');
 const audio=f.node('music-grid').querySelector('audio');f.dispatch('pagehide',{persisted:true});assert.equal(audio.pauses,1);assert.equal(f.node('collection-tabs').getAttribute('role'),'tablist');f.dispatch('pagehide',{persisted:false});assert.equal(audio.pauses,2);assert.equal(f.node('collection-tabs').getAttribute('role'),null);
});
test('market real client tabs are manual, keep hash navigation and exclude hidden admin without issuing HTTP on arrows',async()=>{
 const f=market({hash:'#records'});await f.settle();assert.equal(f.node('records').hidden,false);assert.equal(f.node('market-tab-admin').hidden,true);const calls=f.calls.length;f.node('market-tab-records').focus();f.node('market-tab-records').dispatch('keydown',{key:'ArrowRight'});assert.equal(f.document.activeElement,f.node('market-tab-daily'));assert.equal(f.location.hash,'#records');assert.equal(f.node('records').hidden,false);assert.equal(f.calls.length,calls);
 f.node('market-tab-daily').dispatch('keydown',{key:' '});await f.settle();assert.equal(f.location.hash,'daily');assert.equal(f.node('daily').hidden,false);assert.equal(f.calls.filter(call=>call.url==='/api/market/images/draw').length,1);
 f.location.hash='#admin';f.dispatch('hashchange');assert.equal(f.node('admin').hidden,true);assert.equal(f.node('daily').hidden,false);assert.equal(f.node('market-tab-admin').getAttribute('tabindex'),'-1');
});
test('market admin permission loss hides its panel, preserves manual focus across refresh and validates before preview',async()=>{
 const f=market({role:'admin',hash:'#admin'});await f.settle();assert.equal(f.node('admin').hidden,false);const form=f.node('settleForm'),calls=f.calls.length;await form.onsubmit({target:form,preventDefault(){}});assert.equal(f.calls.length,calls);assert.equal(form.elements.returnPct.getAttribute('aria-invalid'),'true');assert.ok(form.elements.returnPct.getAttribute('aria-describedby'));
 f.node('market-tab-admin').focus();f.node('market-tab-admin').dispatch('keydown',{key:'ArrowLeft'});assert.equal(f.document.activeElement,f.node('market-tab-records'));await f.tick(15000);assert.equal(f.node('market-tab-records').getAttribute('tabindex'),'0');assert.equal(f.node('admin').hidden,false);
 f.state.me.role='member';await f.node('refresh').click().returned;assert.equal(f.node('market-tab-admin').hidden,true);assert.equal(f.node('admin').hidden,true);assert.equal(f.node('daily').hidden,false);assert.equal(f.node('adminAudit').hidden,true);
});
test('market real settlement dialog keeps preview on cancel and returns focus without mutating server data',async()=>{
 const f=market({role:'admin',hash:'#admin'});await f.settle();const form=f.node('settleForm');form.elements.returnPct.value='2';form.elements.returnPct.dispatch('input');await form.onsubmit({target:form,preventDefault(){}});assert.equal(f.node('confirmDialog').open,true);assert.match(f.node('previewContent').textContent,/2027-01-04/);assert.equal(f.node('confirmDialog').getAttribute('aria-labelledby'),'confirmTitle');assert.equal(form.querySelectorAll('[data-ui-field-error]').length,0);
 f.node('confirmDialog').escape();assert.equal(f.node('confirmDialog').open,false);assert.equal(f.document.activeElement,f.node('previewButton'));assert.equal(form.elements.returnPct.value,'2');assert.equal(f.calls.filter(call=>call.url==='/api/admin/market/settle').length,0);
 await form.onsubmit({target:form,preventDefault(){}});f.node('cancelConfirm').click();assert.equal(f.node('confirmDialog').open,false);assert.equal(f.document.activeElement,f.node('previewButton'));await f.node('confirmSettlement').click().returned;assert.equal(f.calls.filter(call=>call.url==='/api/admin/market/settle').length,0);
});
test('market shared approval dialog blocks Escape and duplicate writes while pending, freezes its batch and closes cleanly',async()=>{
 const wait=deferred();let hold=false;const f=market({role:'admin',hash:'#admin',hook:({url,body})=>hold&&url==='/api/admin/market/images/approve'&&body?wait.promise:undefined});await f.settle();f.node('approveFiltered').click();assert.equal(f.node('approvalDialog').open,true);assert.match(f.node('approvalSummary').textContent,/1 張/);hold=true;const submitted=f.node('confirmApproval').click().returned;await f.settle();assert.equal(f.node('confirmApproval').disabled,true);assert.equal(f.node('cancelApproval').disabled,true);assert.equal(f.node('approvalDialog').escape().defaultPrevented,true);
 f.node('confirmApproval').click();f.node('cancelApproval').click();assert.equal(f.calls.filter(call=>call.url==='/api/admin/market/images/approve').length,1);assert.deepEqual(f.calls.at(-1).body.images,[{id:'img-a',version:1}]);wait.resolve(Response.json({ok:true}));await submitted;assert.equal(f.node('approvalDialog').open,false);assert.equal(f.node('cancelApproval').disabled,false);assert.equal(f.calls.filter(call=>call.url==='/api/admin/market/images/approve').length,1);assert.equal(f.node('reviewSelectionCount').textContent,'已勾選 0 / 1 張');
});
test('market approval cancel and Escape preserve pending images, return focus and leave stale confirm inert',async()=>{
 const f=market({role:'admin',hash:'#admin'});await f.settle();for(const close of ['button','escape']){f.node('approveFiltered').focus();f.node('approveFiltered').click();assert.equal(f.node('approvalDialog').open,true);if(close==='button')f.node('cancelApproval').click();else f.node('approvalDialog').escape();assert.equal(f.node('approvalDialog').open,false);assert.equal(f.document.activeElement,f.node('approveFiltered'));await f.node('confirmApproval').click().returned;assert.equal(f.calls.filter(call=>call.url==='/api/admin/market/images/approve').length,0);assert.equal(f.pending[0].status,'pending');assert.equal(f.node('confirmApproval').getAttribute('aria-label'),'確認核准 1 張');}
});
