'use strict';
const {randomUUID}=require('node:crypto');
const {PartyRoom,fail,clone,text}=require('./party-base'),{QUESTIONS}=require('./bluff-catalog');
class BluffRoom extends PartyRoom{
 constructor(code,name,rng,now){super('bluff',code,name,9,3,rng,now);this.options={levels:[1,2,3],roleSeconds:30};this.deadline=null;this.botMemories={};this.sequence=[];this.roles={};this.readyIds=[];this.spokenIds=[];this.challenges=[];this.botStatements={};this.thinkerId=null;this.question=null;}
 configure(id,data){if(id!==this.host)fail('HOST_ONLY','只有房主可以設定',403);if(!['waiting','finished'].includes(this.phase))fail('MATCH_STARTED','開始後不能改難度');const levels=data.levels===undefined?this.options.levels:data.levels,roleSeconds=data.roleSeconds===undefined?this.options.roleSeconds:data.roleSeconds;if(![10,30,60].includes(roleSeconds))fail('INVALID_ROLE_SECONDS','看身分時間只能選 10 秒、30 秒或 1 分鐘',400);if(!Array.isArray(levels)||!levels.length||levels.length>3||new Set(levels).size!==levels.length||levels.some(n=>![1,2,3].includes(n)))fail('INVALID_LEVELS','請選 1–3 級難度',400);if(QUESTIONS.filter(q=>levels.includes(q.level)).length<this.activePlayers().length)fail('NOT_ENOUGH_QUESTIONS','此難度題數不足以讓每人擔任一次想想',400);this.options={levels:levels.slice(),roleSeconds};this.event('settings','更新題目難度與看身分時間');}
 index(n){const i=this.rng(n);if(!Number.isInteger(i)||i<0||i>=n)throw Error('無效抽題結果');return i;}
 start(){const pool=QUESTIONS.filter(q=>this.options.levels.includes(q.level));const seats=this.activePlayers().map(p=>p.id),count=seats.length;if(count<3)fail('NEED_PLAYERS','至少 3 人，可加入測試 AI',400);if(pool.length<count)fail('NOT_ENOUGH_QUESTIONS','所選難度題數不足',400);const sequence=[];while(sequence.length<count)sequence.push(pool.splice(this.index(pool.length),1)[0]);const honestSeats=sequence.map(()=>this.index(count-1)),first=this.index(count),thinkerOrder=seats.slice(first).concat(seats.slice(0,first));this.prepare();this.players.forEach(p=>p.score=3);this.sequence=sequence;this.honestSeats=honestSeats;this.thinkerOrder=thinkerOrder;this.roundLimit=count;this.nextRound();}
 nextRound(){this.round++;this.roundId=randomUUID();this.question=this.sequence[this.round-1];this.thinkerId=this.thinkerOrder[this.round-1];const others=this.players.filter(p=>p.id!==this.thinkerId),honest=others[this.honestSeats[this.round-1]].id;this.roles=Object.fromEntries(this.players.map(p=>[p.id,p.id===this.thinkerId?'thinker':p.id===honest?'honest':'bluffer']));this.readyIds=[];this.spokenIds=[];this.challenges=[];this.botStatements={};this.phase='preparing';this.deadline=this.now()+this.options.roleSeconds*1000;this.botMemories=Object.fromEntries(this.players.filter(p=>p.bot).map(p=>[p.id,this.view(p.id).secretAnswer]));this.event('round','第 '+this.round+' 輪：各自查看角色，準備好後開始口說。');}
 act(id,action,data={}){return this.command(id,action,data,p=>{
  if(action==='ready'){if(this.phase!=='preparing'||this.now()>=this.deadline)fail('INVALID_PHASE','看身分時間已結束');if(this.readyIds.includes(id))fail('ALREADY_READY','已準備');this.readyIds.push(id);this.event('ready',p.name+' 已準備');if(this.readyIds.length===this.players.length){this.beginDiscussion();}}
  else if(action==='spoken'){if(this.phase!=='discussion'||id===this.thinkerId)fail('INVALID_PHASE','只有解釋者能標記說明完畢');if(this.spokenIds.includes(id))fail('ALREADY_SPOKEN','已標記');if(p.bot){const statement=text(data.text,240);if(!statement)fail('INVALID_TEXT','測試說詞不可空白',400);this.botStatements[id]=statement;}this.spokenIds.push(id);this.event('spoken',p.name+' 已說明');}
  else if(action==='challenge'){this.requireThinker(id);this.target(data.targetId);if(this.challenges.includes(data.targetId)||this.challenges.length>=2)fail('NO_CHALLENGE','每輪最多兩張，且不能重複質疑同一人');this.challenges.push(data.targetId);this.event('challenge','想想質疑 '+this.player(data.targetId).name+'：公三小！');}
  else if(action==='guess'){this.requireThinker(id);const target=this.target(data.targetId);if(this.spokenIds.length!==this.players.length-1)fail('NOT_READY','請等每位解釋者標記說明完畢');if(data.confirmed!==true)fail('CONFIRM_REQUIRED','請確認你的選擇',400);const honest=this.players.find(q=>this.roles[q.id]==='honest'),thinker=this.player(this.thinkerId),deltas=Object.fromEntries(this.players.map(q=>[q.id,0]));if(target.id===honest.id){deltas[thinker.id]+=this.question.level;deltas[honest.id]+=this.question.level;}else deltas[target.id]+=this.question.level;for(const challenged of this.challenges){if(challenged===honest.id)deltas[thinker.id]-=3;else{deltas[challenged]--;deltas[thinker.id]++;}}this.players.forEach(q=>q.score+=deltas[q.id]);this.results.push({round:this.round,title:this.question.title,level:this.question.level,answer:this.question.answer,source:this.question.source,thinkerName:thinker.name,honestName:honest.name,selectedName:target.name,correct:target.id===honest.id,challenges:this.challenges.map(pid=>this.player(pid).name),roles:this.players.map(q=>({name:q.name,role:this.roles[q.id],delta:deltas[q.id],score:q.score}))});this.deadline=null;this.botMemories={};this.phase='reveal';this.event('reveal','老實人是 '+honest.name+'，本輪已計分。');if(this.round===this.roundLimit)this.finish();}
  else if(action==='next'){if(id!==this.host)fail('HOST_ONLY','只有房主可以換輪',403);if(this.phase!=='reveal')fail('INVALID_PHASE','先完成本輪');this.nextRound();}
  else fail('INVALID_ACTION','不支援的操作',400);
 });}
 beginDiscussion(){this.phase='discussion';this.deadline=null;this.event('discussion','看身分結束，輪流解釋與質問；想想最後選一位老實人。');}
 auto(){if(this.phase==='preparing'&&this.deadline!=null&&this.now()>=this.deadline)this.beginDiscussion();}
 requireThinker(id){if(this.phase!=='discussion')fail('INVALID_PHASE','現在不能判斷');if(id!==this.thinkerId)fail('THINKER_ONLY','只有想想可以判斷',403);}
 target(id){const p=this.player(id);if(!p||id===this.thinkerId)fail('INVALID_TARGET','請選另一位解釋者',400);return p;}
 view(id){const base=this.baseView(id),active=['preparing','discussion'].includes(this.phase),role=this.phase==='preparing'&&this.now()<this.deadline?this.roles[id]:null,q=this.question;return clone({...base,options:this.options,deadline:this.deadline,serverNow:this.now(),thinkerId:this.thinkerId,myRole:role,secretAnswer:active&&role==='honest'?q.answer:null,prompt:active?{title:q.title,level:q.level,hints:q.level===1?[q.category]:q.level===2?[...new Set(QUESTIONS.map(q=>q.category))].filter(c=>c===q.category||['氣象','動物','天文'].filter(c=>c!==q.category).slice(0,2).includes(c)).sort():[]}:null,readyIds:this.readyIds,spokenIds:this.spokenIds,challenges:this.challenges,botStatements:this.botStatements,canGuess:this.phase==='discussion'&&id===this.thinkerId&&this.spokenIds.length===this.players.length-1});}
}
module.exports={BluffRoom};
