const {assertRecordCapacity}=require('../rooms/membership');
const {randomInt,randomUUID}=require('node:crypto');
const {TOPICS,QUESTIONS}=require('./majority-questions');
const {validateQuestion}=require('../community/store');
const {validCustomPercent,drawContent}=require('./content-draw');
const copy=value=>JSON.parse(JSON.stringify(value));
const freeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){for(const child of Object.values(value))freeze(child);Object.freeze(value);}return value;};
const MAX_PENDING_ACHIEVEMENT_UNITS=256;
const CANONICAL_USER_ID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
// Only Unicode compatibility, case and whitespace are normalized; no fuzzy matching.
const normalize=value=>value.normalize('NFKC').toLowerCase().trim().replace(/\s+/gu,' ');
class MajorityRoom{
 constructor(code,name,rng=randomInt){this.type='majority';this.code=code;this.name=name;this.rng=rng;this.players=[];this.phase='waiting';this.version=0;this.round=0;this.roundLimit=10;this.options={rounds:10,customPercent:null};this.log=[];this.events=[];this.updated=Date.now();this.candidates=[];this.usedQuestionIds=[];this.seenQuestionIds=[];this.answers={};this.groups=[];this.result=null;this.question=null;this.deadline=null;this.presenterId=null;this.participantIds=[];this.questionQueue=[];this.reactions=[];this.reactionSeq=0;Object.defineProperty(this,'achievementUnits',{value:{matchId:null,current:null,pending:new Map()},enumerable:false});}
 pendingAchievementUnits(){return [...this.achievementUnits.pending.values()];}
 drainAchievementUnits(){return this.pendingAchievementUnits();}
 acknowledgeAchievementUnit(unitEventId){return this.achievementUnits.pending.delete(unitEventId);}
 achievementCapacity(){
  if((typeof this.achievementUnitStart==='function'||typeof this.achievementUnitCompleted==='function')&&this.achievementUnits.pending.size>=MAX_PENDING_ACHIEVEMENT_UNITS)throw Error('回合紀錄等待儲存，請稍後再開始下一輪');
 }
 beginAchievementUnit(participantSeatIds){
  if(typeof this.achievementUnitStart!=='function'&&typeof this.achievementUnitCompleted!=='function'){this.achievementUnits.current=null;return;}
  const context=freeze({match_id:this.achievementUnits.matchId,unit_event_id:randomUUID(),game_type:this.type,unit:'round',round:this.round,participantSeatIds:[...participantSeatIds]});
  const participants=[],seats=new Set(participantSeatIds.filter(id=>this.players.some(player=>player.id===id&&!player.bot))),users=new Set(),usedSeats=new Set();
  try{
   const supplied=this.achievementUnitStart?.(context);
   if(supplied&&typeof supplied.then==='function')Promise.resolve(supplied).catch(()=>{});
   if(Array.isArray(supplied))for(const item of supplied){
    if(!item||typeof item.user_id!=='string'||!CANONICAL_USER_ID.test(item.user_id)||!seats.has(item.seat_id)||users.has(item.user_id.toLowerCase())||usedSeats.has(item.seat_id))continue;
    participants.push({user_id:item.user_id,seat_id:item.seat_id});users.add(item.user_id.toLowerCase());usedSeats.add(item.seat_id);
   }
  }catch{/* Optional persistence hooks cannot roll back accepted gameplay. */}
  this.achievementUnits.current={context,participants:freeze(participants),mappingComplete:participantSeatIds.every(id=>{const player=this.players.find(item=>item.id===id);return !!player&&(!!player.bot||usedSeats.has(id));}),completed:false};
 }
 completeAchievementUnit(status){
  const state=this.achievementUnits,unit=state.current;
  if(!unit||unit.completed)return;
  if(status==='rules_completed'&&!unit.mappingComplete)status='interrupted';
  const mappedSeats=new Set(unit.participants.map(participant=>participant.seat_id));
  const active=new Set(this.activePlayers().filter(player=>mappedSeats.has(player.id)&&this.participantIds.includes(player.id)).map(player=>player.id));
  const participants=unit.participants.map(participant=>({...participant,eligible:active.has(participant.seat_id)&&Object.hasOwn(this.answers,participant.seat_id),answerAccepted:active.has(participant.seat_id)&&Object.hasOwn(this.answers,participant.seat_id)}));
  const max=Math.max(0,...this.groups.map(group=>group.count)),leaders=this.groups.filter(group=>group.count===max);
  const answeringSeats=new Set(this.activePlayers().filter(player=>this.participantIds.includes(player.id)).map(player=>player.id));
  const group=this.groups.length===1?this.groups[0]:null;
  const allSame=unit.mappingComplete&&active.size>=3&&!!group&&group.count===answeringSeats.size&&group.playerIds.length===answeringSeats.size&&new Set(group.playerIds).size===answeringSeats.size&&group.playerIds.every(id=>answeringSeats.has(id))&&[...answeringSeats].every(id=>Object.hasOwn(this.answers,id));
  const snapshot=freeze({unit_event_id:unit.context.unit_event_id,match_id:unit.context.match_id,game_type:this.type,unit:'round',round:unit.context.round,status,completed_at:new Date().toISOString(),participants,metrics:{participantCount:active.size,allSame,tiedLargest:unit.mappingComplete&&max>=2&&leaders.length>=2}});
  unit.completed=true;state.pending.set(snapshot.unit_event_id,snapshot);
  try{const notified=this.achievementUnitCompleted?.(snapshot);if(notified&&typeof notified.then==='function')Promise.resolve(notified).catch(()=>{});}catch{/* The latched snapshot remains pending for reconciliation. */}
 }
 event(kind,text){this.events.push({id:++this.version,kind,text});this.events=this.events.slice(-12);this.log.unshift(text);this.log=this.log.slice(0,60);this.updated=Date.now();}
 player(id){return this.players.find(p=>p.id===id);}
 activePlayers(){return this.players.filter(p=>!p.kicked);}
 kick(id,target,leaving=false){if(id!==this.host)throw Error('只有房主可以踢人');const p=this.player(target);if(!p||p.kicked)throw Error('找不到玩家');if(target===this.host)throw Error('不能踢出自己');const live=this.activePlayers().filter(p=>!p.waitingForNextRound),index=live.findIndex(p=>p.id===target),next=live[(index+1)%live.length];this.questionQueue=this.questionQueue.filter(q=>q.owner!==target);if(this.phase==='waiting')this.players.splice(this.players.indexOf(p),1);else p.kicked=true;this.event('kick',p.name+(leaving?' 已離開房間':' 已被房主踢出'));const active=this.activePlayers();if(this.presenterId===target&&this.phase!=='choosing')this.nextPresenterId=next.id;if(this.phase==='finished'){const eligible=active.filter(p=>!p.waitingForNextRound),high=Math.max(...eligible.map(p=>p.score));this.winner={ids:eligible.filter(p=>p.score===high).map(p=>p.id),score:high};return;}if(this.phase==='waiting')return;
 if(['choosing','answering','review'].includes(this.phase)){this.participantIds=this.participantIds.filter(pid=>pid!==target);delete this.answers[target];for(const g of this.groups){g.playerIds=g.playerIds.filter(pid=>pid!==target);g.count=g.playerIds.length;}this.groups=this.groups.filter(g=>g.count);}
 if(active.length<2){this.phase='finished';this.deadline=null;this.winner={ids:active.map(p=>p.id),score:active[0]?.score||0,reason:'玩家不足，本局提前結束'};this.event('finish','玩家不足，本局提前結束');this.completeAchievementUnit('abandoned');return;}
 if(this.phase==='choosing'&&this.presenterId===target){this.presenterId=next.id;this.candidates=[];this.event('pass','已改由 '+next.name+' 出題');}if(this.phase==='answering'&&this.participantIds.every(pid=>Object.hasOwn(this.answers,pid)))this.close('complete');}
 actor(){return this.presenterId;}
 add(name,bot=false){assertRecordCapacity(this);if(this.activePlayers().length>=12)throw Error('最多 12 位玩家');if(typeof name!=='string'||!name.trim())throw Error('請輸入名字');const p={id:randomUUID(),secret:randomUUID(),name:name.trim().slice(0,16),bot,score:0,waitingForNextRound:this.phase!=='waiting',lastSeen:Date.now()};this.players.push(p);if(!this.host)this.host=p.id;this.event('join',`${p.name} 加入房間${p.waitingForNextRound?(this.phase==='finished'?'，下一局開始參與':'，下一題開始參與'):''}`);return p;}
 configure(id,data={}){if(id!==this.host)throw Error('只有房主可以更改設定');if(!['waiting','finished'].includes(this.phase))throw Error('遊戲中不能更改設定');const rounds=data.rounds??data.roundLimit;if(!Number.isInteger(rounds)||rounds<3||rounds>30)throw Error('回合數必須是 3 至 30 的整數');const customPercent=data.customPercent===undefined?this.options.customPercent:data.customPercent;if(!validCustomPercent(customPercent))throw Error('自訂題目比例請選擇自動、0%、25%、50%、75% 或 100%');this.roundLimit=rounds;this.options={rounds,customPercent};this.event('settings',`設定為 ${rounds} 回合；自訂題目${customPercent===null?'依題庫比例':customPercent+'%'}`);}
 start(){if(!['waiting','finished'].includes(this.phase))throw Error('遊戲尚未結束');this.achievementCapacity();if(this.activePlayers().length<3||this.activePlayers().length>12)throw Error('需要 3 至 12 位玩家');this.players=this.activePlayers();for(const p of this.players)p.score=0;this.achievementUnits.matchId=randomUUID();this.round=0;this.nextPresenterId=null;this.usedQuestionIds=[];this.seenQuestionIds=[];this.results=[];this.winner=null;this.newRound();}
 newRound(){this.achievementCapacity();for(const p of this.activePlayers())p.waitingForNextRound=false;this.round++;this.presenterId=this.nextPresenterId||this.activePlayers()[this.round===1?0:(this.activePlayers().findIndex(p=>p.id===this.presenterId)+1)%this.activePlayers().length].id;this.nextPresenterId=null;this.participantIds=this.activePlayers().map(p=>p.id);this.phase='choosing';this.question=null;this.answers={};this.groups=[];this.result=null;this.candidates=[];this.deadline=null;this.closedReason=null;this.beginAchievementUnit(this.participantIds);this.event('round',`第 ${this.round} 回合，由 ${this.player(this.presenterId).name} 出題`);if(this.questionQueue.length){const queued=this.questionQueue.shift();this.presenterId=queued.owner;this.candidates=[copy(queued.question)];this.ask({...queued.question,questionId:queued.question.id||undefined});}}
 draw(data){const topic=data.topic||TOPICS[0].id,type=data.type||'two';if(!TOPICS.some(t=>t.id===topic)||!['two','three','blank'].includes(type))throw Error('題目分類不正確');const builtin=QUESTIONS.filter(q=>q.topic===topic&&q.type===type),custom=(this.questionProvider?.()||[]).filter(q=>q.topic===topic&&q.type===type);if(!builtin.length&&!custom.length)throw Error('此分類沒有題目');const draw=drawContent({builtin,custom,count:3,customPercent:this.options.customPercent,usedIds:this.usedQuestionIds,rng:this.rng});this.usedQuestionIds=draw.usedIds;this.candidates=draw.items.map(q=>({...copy(q),reused:this.seenQuestionIds.includes(q.id)}));for(const q of draw.items)if(!this.seenQuestionIds.includes(q.id))this.seenQuestionIds.push(q.id);this.topic=topic;this.questionType=type;this.event('draw','出題者已抽取候選題目');}
 ask(data){let q;if(data.questionId!==undefined){q=this.candidates.find(c=>c.id===data.questionId)||[...QUESTIONS,...(this.questionProvider?.()||[])].find(c=>c.id===data.questionId);if(!q)throw Error('請選擇目前候選題目');q=copy(q);}else{const {type,prompt,options}=data;if(!['two','three','blank'].includes(type)||typeof prompt!=='string'||!prompt.trim()||prompt.trim().length>160)throw Error('題目需為 1 至 160 字');let choices=[];if(type!=='blank'){const count=type==='two'?2:3;if(!Array.isArray(options)||options.length!==count||options.some(o=>typeof o!=='string'||!o.trim()||o.trim().length>60))throw Error('選項數量或長度不正確');choices=options.map(o=>o.trim());if(new Set(choices.map(normalize)).size!==count)throw Error('選項不可重複');}q={id:null,topic:'custom',type,prompt:prompt.trim(),options:choices,custom:true};}this.question=q;this.topic=q.topic;this.questionType=q.type;this.candidates=[];this.phase='answering';this.deadline=Date.now()+120000;this.event('ask','題目已公開，請秘密作答');}
 answer(id,data){if(Object.hasOwn(this.answers,id))throw Error('答案已鎖定，不能修改');let answer=data.answer;if(this.question.type==='blank'){if(typeof answer!=='string'||!answer.trim()||answer.trim().length>60||!normalize(answer))throw Error('答案需為 1 至 60 字');answer=answer.trim();}else if(!Number.isInteger(answer)||answer<0||answer>=this.question.options.length)throw Error('請選擇有效選項');this.answers[id]=answer;this.event('answer',`${this.player(id).name} 已提交答案`);if(this.participantIds.every(pid=>Object.hasOwn(this.answers,pid)))this.close('complete');}
 buildGroups(){const groups=[];for(const id of this.participantIds){if(!Object.hasOwn(this.answers,id))continue;const answer=this.answers[id],key=this.question.type==='blank'?normalize(answer):String(answer);let group=groups.find(g=>g.key===key);if(!group){group={id:`group-${groups.length+1}`,key,label:this.question.type==='blank'?answer:this.question.options[answer],playerIds:[],count:0,winner:false};groups.push(group);}group.playerIds.push(id);group.count++;}return groups;}
 close(reason){this.closedReason=reason;this.deadline=null;this.groups=this.buildGroups();if(this.question.type==='blank'){this.phase='review';this.event('review','作答結束，請房主確認同義答案分組');}else this.score();}
 score(){const max=Math.max(0,...this.groups.map(g=>g.count));const leaders=this.groups.filter(g=>g.count===max);const winning=max>=2&&leaders.length===1?leaders[0].id:null;const gains={};for(const p of this.players)gains[p.id]=0;for(const g of this.groups){g.winner=g.id===winning;for(const id of g.playerIds)if(g.winner){const points=this.question.type==='blank'?2:1;gains[id]=points;this.player(id).score+=points;}}const points=this.question.type==='blank'?2:1;const presenterPenalty=!this.player(this.presenterId)?.kicked&&this.question.type==='blank'&&max*3<=this.participantIds.length?1:0;if(presenterPenalty){gains[this.presenterId]--;this.player(this.presenterId).score--;}this.phase='reveal';this.result={points,presenterPenalty,round:this.round,groups:copy(this.groups),answers:copy(this.answers),gains,missingIds:this.participantIds.filter(id=>!Object.hasOwn(this.answers,id)),reason:this.closedReason};this.event('reveal',(winning?`唯一最大答案組每人獲得 ${points} 分`:'最大組並列或不足兩人，無人加分')+(presenterPenalty?'；最大組未超過全體玩家 1/3，出題者扣 1 分':''));this.completeAchievementUnit('rules_completed');}
 act(id,action,data={}){if(!this.player(id)||this.player(id).kicked)throw Error('找不到玩家');
if(this.phase==='reveal'&&action==='next'&&(id===this.host||id===this.presenterId)&&this.round<this.roundLimit)this.achievementCapacity();
if(['answer','withdraw'].includes(action)&&!this.participantIds.includes(id))throw Error('這題已開始，請等下一題作答');
if(action==='react'){const emoji=data.emoji;if(!['👍','❤️','😂','😮','😭','🔥','👏','🤔'].includes(emoji))throw Error('不支援的表情');const p=this.player(id),now=Date.now();if(p.reactedAt&&now-p.reactedAt<1200)throw Error('表情稍等一下再送');p.reactedAt=now;this.reactions=this.reactions.filter(r=>now-r.at<8000);this.reactions.push({id:++this.reactionSeq,player:id,emoji,at:now});return;}
if(action==='enqueue'){if(this.phase==='finished')throw Error('請先開始新局');if(this.questionQueue.filter(q=>q.owner===id).length>=5||this.questionQueue.length>=60)throw Error('每人最多預備 5 題');let q;if(data.questionId){q=[...QUESTIONS,...(this.questionProvider?.()||[])].find(q=>q.id===data.questionId);if(!q)throw Error('找不到題目');}else q={...validateQuestion(data),id:null,custom:true};this.questionQueue.push({id:randomUUID(),owner:id,question:copy(q)});this.event('enqueue',this.player(id).name+' 已預備一題');return;}
if(action==='unqueue'){const i=this.questionQueue.findIndex(q=>q.id===data.queueId&&q.owner===id);if(i<0)throw Error('只能移除自己的預備題目');this.questionQueue.splice(i,1);this.event('unqueue','已移除預備題目');return;}
if(this.phase==='answering'&&['answer','withdraw'].includes(action)&&Date.now()>=this.deadline){this.close('timeout');throw Error('作答時間已結束');}
if(this.phase==='answering'&&action==='withdraw'){if(!Object.hasOwn(this.answers,id))throw Error('還沒有提交答案');delete this.answers[id];this.event('withdraw',this.player(id).name+' 已收回答案');return;}
if(this.phase==='choosing'&&action==='pass'){if(id!==this.host)throw Error('只有房主可以更換出題者');const ready=this.activePlayers().filter(p=>!p.waitingForNextRound);this.presenterId=ready[(ready.findIndex(p=>p.id===this.presenterId)+1)%ready.length].id;this.candidates=[];this.event('pass','房主已更換出題者');return;}if(this.phase==='choosing'&&['draw','ask'].includes(action)){if(id!==this.presenterId)throw Error('只有本回合出題者可以出題');if(action==='draw')this.draw(data);else this.ask(data);return;}if(this.phase==='answering'&&action==='answer'){this.answer(id,data);return;}if(this.phase==='answering'&&action==='close'){if(id!==this.host)throw Error('只有房主可以結束作答');this.close('host');return;}if(this.phase==='review'&&['merge','resetGroups','score'].includes(action)){if(id!==this.host)throw Error('只有房主可以確認分組');if(action==='score'){this.score();return;}if(action==='resetGroups')this.groups=this.buildGroups();else{const from=this.groups.find(g=>g.id===data.from),to=this.groups.find(g=>g.id===data.to);if(!from||!to||from===to)throw Error('請選擇兩個不同答案組');to.playerIds.push(...from.playerIds);to.count=to.playerIds.length;this.groups=this.groups.filter(g=>g!==from);}this.event('groups',action==='merge'?'房主已合併答案組':'已還原原始答案組');return;}if(this.phase==='reveal'&&action==='next'){if(id!==this.host&&id!==this.presenterId)throw Error('請由房主或出題者繼續');this.results.push({question:copy(this.question),...copy(this.result)});if(this.round>=this.roundLimit){this.phase='finished';const eligible=this.activePlayers().filter(p=>!p.waitingForNextRound),high=Math.max(...eligible.map(p=>p.score));this.winner={ids:eligible.filter(p=>p.score===high).map(p=>p.id),score:high};this.event('finish','全部回合結束');}else this.newRound();return;}throw Error('目前階段無法執行此操作');}
 auto(){if(this.phase==='answering'&&this.deadline!==null&&Date.now()>=this.deadline)this.close('timeout');}
 view(id){const visible=['review','reveal','finished'].includes(this.phase);return copy({type:this.type,code:this.code,name:this.name,phase:this.phase,version:this.version,host:this.host===id,hostId:this.host,me:id,presenterId:this.presenterId,actor:this.presenterId,round:this.round,roundLimit:this.roundLimit,options:this.options,topics:TOPICS,topic:this.topic||null,questionType:this.questionType||null,question:this.question,deadline:this.deadline,queueCount:this.questionQueue.length,ownQueue:this.questionQueue.filter(q=>q.owner===id),reactions:this.reactions.filter(r=>Date.now()-r.at<8000),participantIds:this.participantIds,answeredIds:Object.keys(this.answers),ownAnswer:Object.hasOwn(this.answers,id)?this.answers[id]:null,candidates:this.phase==='choosing'&&id===this.presenterId?this.candidates:[],groups:visible?this.groups:[],answers:visible?this.answers:undefined,result:['reveal','finished'].includes(this.phase)?this.result:null,closedReason:this.closedReason||null,winner:this.winner||null,departed:this.players.filter(p=>p.kicked).map(p=>({id:p.id,name:p.name})),players:this.activePlayers().map(p=>({id:p.id,name:p.name,avatar:p.avatar||null,bot:!!p.bot,score:p.score,waitingForNextRound:!!p.waitingForNextRound,online:!!p.bot||Date.now()-p.lastSeen<15000})),log:this.log,events:this.events,normalization:'填空答案只合併 Unicode NFKC、英文大小寫及連續空白；其他同義詞由房主確認。'});}
}
module.exports={MajorityRoom};
