const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{randomUUID,webcrypto}=require('node:crypto');
const source=fs.readFileSync(path.join(__dirname,'../../public/shared/table-media.js'),'utf8');
const flush=async()=>{for(let index=0;index<12;index++)await Promise.resolve();};
const json=(body,{ok=true,status=200}={})=>({ok,status,json:async()=>structuredClone(body)});
function deferred(){let resolve,reject;const promise=new Promise((ok,fail)=>{resolve=ok;reject=fail;});return {promise,resolve,reject};}
function mediaSnapshot(changes={}){return {schemaVersion:1,roomInstanceId:'room-a',revision:1,playbackSessionId:'session-a',current:{id:'item-a',type:'video',title:'影片A',videoId:'M7lc1UVf-VE',requestedById:'host',requestedByName:'房主',durationSec:100},queue:[],playback:{state:'paused',anchorPositionSec:12,anchorServerMs:100000,rate:1},serverNowMs:100000,canControl:true,canManageQueue:true,isHost:true,isManager:false,myPlayerId:'host',...changes};}
function roomState(snapshot=mediaSnapshot(),changes={}){return {code:'ABC123',me:snapshot.myPlayerId,version:1,media:{roomInstanceId:snapshot.roomInstanceId,revision:snapshot.revision,hasCurrent:!!snapshot.current},permissions:{role:snapshot.isHost?'host':snapshot.isManager?'manager':'member',canManageMedia:snapshot.canControl,isHost:snapshot.isHost},...changes};}
function mediaHarness({youtube=true,fetchHandler,pendingAudio=false,blockedAudio=false,enabled=false,storageFailure=false,randomSource={randomUUID,getRandomValues:bytes=>webcrypto.getRandomValues(bytes)}}={}){
 const ids=new Map(),network=[],players=[],audioClips=[],thirdParty=[],observers=[],frames=new Map(),timers=new Map(),storage=new Map(),audioListeners=new Set();let now=0,nextFrame=1,nextTimer=1,settings={music:{enabled,volume:.3},effects:{enabled:false,volume:.25}},context;
 class Node{
  constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.parentNode=null;this.attributes=new Map();this.handlers=new Map();this.dataset={};this.hidden=false;this.disabled=false;this.open=false;this.value='';this.textContent='';this.capturedPointers=new Set();const classes=this._classes=new Set();this.classList={add:name=>classes.add(name),remove:name=>classes.delete(name),toggle(name,force){if(force===undefined)force=!classes.has(name);force?classes.add(name):classes.delete(name);return force;},contains:name=>classes.has(name)};this.style={setProperty(name,value){this[name]=String(value);},getPropertyValue(name){return this[name]||'';},removeProperty(name){delete this[name];}};this.rect={left:30,top:60,width:600,height:340,right:630,bottom:400};}
  set id(value){this._id=value;ids.set(value,this);}get id(){return this._id||'';}
  set innerHTML(value){this._html=value;this.replaceChildren();const stack=[this],voids=new Set(['input','hr','br','img','meta','link']);for(const match of value.matchAll(/<(\/)?([a-z][a-z0-9-]*)\b([^>]*)>/gi)){const tag=match[2].toLowerCase();if(match[1]){if(stack.at(-1)?.tagName===tag.toUpperCase())stack.pop();continue;}const node=new Node(tag);for(const attribute of match[3].matchAll(/\b([a-z][\w:-]*)="([^"]*)"/gi))node.setAttribute(attribute[1],attribute[2]);node.hidden=/\bhidden\b/.test(match[3]);node.disabled=/\bdisabled\b/.test(match[3]);node.value=node.getAttribute('value')||'';stack.at(-1).append(node);if(!voids.has(tag))stack.push(node);}}
  get innerHTML(){return this._html||'';}get parentElement(){return this.parentNode;}get isConnected(){return !!this.parentNode;}set className(value){this._classes.clear();for(const name of value.split(/\s+/))if(name)this._classes.add(name);}get className(){return [...this._classes].join(' ');}get previousElementSibling(){const list=this.parentNode?.children||[];return list[list.indexOf(this)-1]||null;}
  append(...nodes){for(const node of nodes){node.remove?.();node.parentNode=this;this.children.push(node);if(node.tagName==='SCRIPT'&&/^https:/.test(node.src||''))thirdParty.push(node);}}
  replaceChildren(...nodes){for(const node of this.children)node.parentNode=null;this.children=[];this.append(...nodes);}remove(){if(this.parentNode){this.parentNode.children=this.parentNode.children.filter(node=>node!==this);this.parentNode=null;}}
  before(...nodes){if(!this.parentNode)return;const parent=this.parentNode,index=parent.children.indexOf(this);for(const node of nodes)node.remove?.();for(const node of nodes)node.parentNode=parent;parent.children.splice(index,0,...nodes);}after(...nodes){if(!this.parentNode)return;const parent=this.parentNode,index=parent.children.indexOf(this)+1;for(const node of nodes)node.remove?.();for(const node of nodes)node.parentNode=parent;parent.children.splice(index,0,...nodes);}prepend(...nodes){for(const node of nodes)node.remove?.();for(const node of nodes)node.parentNode=this;this.children.unshift(...nodes);}
  setAttribute(name,value){this.attributes.set(name,String(value));if(name==='id')this.id=String(value);if(name==='class')this.className=String(value);}getAttribute(name){return this.attributes.get(name)??null;}hasAttribute(name){return this.attributes.has(name);}removeAttribute(name){this.attributes.delete(name);if(name==='src')delete this.src;}
  matches(selector){if(selector.includes(':not(:disabled)')&&this.disabled)return false;selector=selector.replace(':not(:disabled)','');const tag=selector.match(/^[a-z]+/i)?.[0];if(tag&&tag.toUpperCase()!==this.tagName)return false;const id=selector.match(/#([\w-]+)/)?.[1];if(id&&id!==this.id)return false;for(const match of selector.matchAll(/\.([\w-]+)/g))if(!this.classList.contains(match[1]))return false;for(const match of selector.matchAll(/\[([\w-]+)(?:="([^"]*)")?\]/g)){const value=this.getAttribute(match[1])??this[match[1]];if(value===undefined||value===null||match[2]!==undefined&&String(value)!==match[2])return false;}return true;}
  querySelectorAll(selector){const descend=node=>node.children.flatMap(child=>[child,...descend(child)]);return descend(this).filter(node=>selector.split(',').some(choice=>{const parts=choice.replace(':scope','').trim().split(/\s*>\s*|\s+/);if(!node.matches(parts.at(-1)))return false;let parent=node.parentNode;for(let index=parts.length-2;index>=0;index--){if(choice.includes('>')){if(!parent?.matches(parts[index]))return false;parent=parent.parentNode;}else{while(parent&&!parent.matches(parts[index]))parent=parent.parentNode;if(!parent)return false;parent=parent.parentNode;}}return true;}));}
  querySelector(selector){return this.querySelectorAll(selector)[0]||null;}contains(node){return this===node||this.children.some(child=>child.contains(node));}closest(selector){for(let node=this;node;node=node.parentNode)if(node.matches(selector))return node;return null;}
  addEventListener(type,callback){if(!this.handlers.has(type))this.handlers.set(type,new Set());this.handlers.get(type).add(callback);}dispatch(type,event={}){for(const callback of this.handlers.get(type)||[])callback(event);}
  getBoundingClientRect(){const px=(value,fallback)=>typeof value==='string'&&value.endsWith('px')?parseFloat(value):fallback;const left=px(this.style.left,this.rect.left),top=px(this.style.top,this.rect.top),width=px(this.style.width,this.rect.width),height=px(this.style.height,this.rect.height);return {x:left,y:top,left,top,width,height,right:left+width,bottom:top+height};}
  setPointerCapture(id){this.capturedPointers.add(id);}releasePointerCapture(id){this.capturedPointers.delete(id);}hasPointerCapture(id){return this.capturedPointers.has(id);}focus(){document.activeElement=this;}
  show(){this.open=true;this.modal=false;}showModal(){this.open=true;this.modal=true;}close(){if(this.open){this.open=false;this.dispatch('close');}}click(){if(!this.disabled)return this.onclick?.({target:this,preventDefault(){}});}submit(){return this.onsubmit?.({target:this,preventDefault(){}});}
 }
 const document={body:new Node('body'),head:new Node('head'),hidden:false,activeElement:null,handlers:new Map(),createElement:tag=>new Node(tag),createTextNode:text=>{const node=new Node('span');node.textContent=text;return node;},querySelector(selector){if(selector==='dialog:modal')return [...ids.values()].find(node=>node.tagName==='DIALOG'&&node.open&&node.modal)||null;return this.body.querySelector(selector)||this.head.querySelector(selector);},querySelectorAll(selector){return [...this.body.querySelectorAll(selector),...this.head.querySelectorAll(selector)];},addEventListener(type,callback){if(!this.handlers.has(type))this.handlers.set(type,new Set());this.handlers.get(type).add(callback);},removeEventListener(type,callback){this.handlers.get(type)?.delete(callback);},dispatch(type,event={}){for(const fn of this.handlers.get(type)||[])fn(event);}};
 const window={innerWidth:1280,innerHeight:720,handlers:new Map(),addEventListener(type,callback){if(!this.handlers.has(type))this.handlers.set(type,new Set());this.handlers.get(type).add(callback);},dispatch(type,event={}){for(const fn of this.handlers.get(type)||[])fn(event);},requestAnimationFrame(callback){const id=nextFrame++;frames.set(id,callback);return id;},cancelAnimationFrame:id=>frames.delete(id)};
 window.GameUI={decorateButton(node,_icon,{label}){node.setAttribute('aria-label',label);},setStatus(node,message){node.textContent=message;},playerName:name=>'<span class="ui-player-name">'+name+'</span>'};window.AudioSettings={get:()=>structuredClone(settings),set(kind,patch,meta){settings[kind]={...settings[kind],...patch};for(const fn of audioListeners)fn(structuredClone(settings),meta);},subscribe(fn){audioListeners.add(fn);fn(structuredClone(settings),{});return ()=>audioListeners.delete(fn);}};
 class Audio extends Node{constructor(){super('audio');this.paused=true;this.currentTime=0;this.readyState=1;this.volume=1;audioClips.push(this);}play(){if(blockedAudio)return Promise.reject(Error('blocked'));if(pendingAudio)return new Promise(resolve=>{this.resolvePlay=()=>{this.paused=false;resolve();};});this.paused=false;return Promise.resolve();}pause(){this.paused=true;}load(){}ended(){this.onended?.();}}
 const makePlayer=()=>class Player{constructor(iframe,{events}){this.iframe=iframe;this.events=events;this.calls=[];this.destroyed=false;this.duration=100;players.push(this);}pauseVideo(){this.calls.push(['pause']);this.events.onStateChange?.({data:2,target:this});}playVideo(){this.calls.push(['play']);this.events.onStateChange?.({data:1,target:this});}seekTo(value){this.calls.push(['seek',value]);this.events.onStateChange?.({data:1,target:this});}cueVideoById(value){this.calls.push(['cue',value]);}setVolume(value){this.calls.push(['volume',value]);}mute(){this.calls.push(['mute']);}unMute(){this.calls.push(['unmute']);}getDuration(){return this.duration;}destroy(){this.calls.push(['destroy']);this.destroyed=true;this.iframe.remove();}ready(){this.events.onReady?.({target:this});}state(value){this.events.onStateChange?.({data:value,target:this});}blocked(){this.events.onAutoplayBlocked?.({target:this});}error(value){this.events.onError?.({data:value,target:this});}};
 if(youtube)window.YT={Player:makePlayer()};class Observer{constructor(callback){this.callback=callback;this.disconnected=false;observers.push(this);}observe(target){this.target=target;}disconnect(){this.disconnected=true;}emit(records){this.callback(records);}}
 const fetch=async(route,options={})=>{const request={route,options,body:options.body?JSON.parse(options.body):null};network.push(request);if(fetchHandler)return fetchHandler(request);return json(route==='/api/music'?{tracks:[]}:mediaSnapshot());};
 const schedule=(fn,delay,repeat)=>{const id=nextTimer++;timers.set(id,{fn,at:now+delay,repeat});return id;};
 context=vm.createContext({window,document,Audio,Option:class extends Node{constructor(text,value){super('option');this.textContent=text;this.value=value;}},location:{origin:'https://example.test'},crypto:randomSource,performance:{now:()=>now},localStorage:{getItem:key=>{if(storageFailure)throw Error('blocked');return storage.get(key)??null;},setItem:(key,value)=>{if(storageFailure)throw Error('blocked');storage.set(key,value);},removeItem:key=>storage.delete(key)},AbortController,fetch,IntersectionObserver:Observer,ResizeObserver:Observer,MutationObserver:Observer,setTimeout:(fn,delay)=>schedule(fn,delay,0),clearTimeout:id=>timers.delete(id),setInterval:(fn,delay)=>schedule(fn,delay,delay),clearInterval:id=>timers.delete(id)});vm.runInContext(source,context,{filename:'public/shared/table-media.js'});
 const node=id=>{const result=ids.get(id.replace(/^#/,''));if(!result)throw Error('unknown node '+id);return result;};
 const advance=async ms=>{const end=now+ms;for(;;){const first=[...timers].filter(([,entry])=>entry.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!first)break;const [id,entry]=first;now=entry.at;if(entry.repeat)entry.at+=entry.repeat;else timers.delete(id);entry.fn();await flush();}now=end;await flush();};
 return {context,window,document,node,network,players,audioClips,thirdParty,observers,frames,timers,storage,flush,advance,async flushFrames(){const pending=[...frames];frames.clear();for(const [,callback] of pending)callback(now);await flush();},async update(state){window.TableMedia.update(state);await flush();},async open(){await window.TableMedia.open();await flush();},async click(id){await node(id).click();await flush();},async submit(id){await node(id).submit();await flush();},setFetch(fn){fetchHandler=fn;},installYT(){window.YT={Player:makePlayer()};window.onYouTubeIframeAPIReady?.();},hide(value){document.hidden=value;document.dispatch('visibilitychange');},otherModal(){const other=new Node('dialog');other.id='other-modal';other.showModal();return other;},emitMutations(records){for(const observer of observers)if(observer.target===document.body)observer.emit(records);},run:code=>vm.runInContext(code,context)};
}
module.exports={mediaHarness,mediaSnapshot,roomState,deferred,json,flush};
