// Event/DOM controls for executing the real widgets and clients. No UI logic is mocked.
const decode=text=>text.replace(/&(amp|lt|gt|quot|#39);/g,(_all,key)=>({amp:'&',lt:'<',gt:'>',quot:'"','#39':"'"}[key]));
function dom(html=''){
 const observers=[];let document;
 class Element{
  constructor(tag='div'){this.tagName=tag.toUpperCase();this.nodeType=1;this.attributes=new Map();this.children=[];this.parentElement=null;this.listeners=new Map();this._value=undefined;this._checked=undefined;this.files=[];this.pauses=0;this.style={};
   this.dataset=new Proxy({},{get:(_target,key)=>this.getAttribute('data-'+String(key).replace(/[A-Z]/g,c=>'-'+c.toLowerCase()))??undefined,set:(_target,key,value)=>{this.setAttribute('data-'+String(key).replace(/[A-Z]/g,c=>'-'+c.toLowerCase()),value);return true;}});
   this.classList={contains:value=>this.className.split(/\s+/).includes(value),add:(...values)=>{this.className=[...new Set([...this.className.split(/\s+/).filter(Boolean),...values])].join(' ');},remove:(...values)=>{this.className=this.className.split(/\s+/).filter(value=>!values.includes(value)).join(' ');},toggle:(value,on)=>{const enabled=on??!this.classList.contains(value);this.classList[enabled?'add':'remove'](value);return enabled;}};
  }
  get ownerDocument(){return document;}get id(){return this.getAttribute('id')||'';}set id(value){this.setAttribute('id',value);}get className(){return this.getAttribute('class')||'';}set className(value){this.setAttribute('class',value);}
  get name(){return this.getAttribute('name')||'';}set name(value){this.setAttribute('name',value);}get type(){return this.getAttribute('type')||(this.tagName==='BUTTON'?'submit':'text');}set type(value){this.setAttribute('type',value);}
  get hidden(){return this.hasAttribute('hidden');}set hidden(value){value?this.setAttribute('hidden',''):this.removeAttribute('hidden');}get disabled(){return this.hasAttribute('disabled');}set disabled(value){value?this.setAttribute('disabled',''):this.removeAttribute('disabled');}
  get required(){return this.hasAttribute('required');}set required(value){value?this.setAttribute('required',''):this.removeAttribute('required');}get checked(){return this._checked??this.hasAttribute('checked');}set checked(value){this._checked=!!value;}
  get value(){return this._value??this.getAttribute('value')??(this.tagName==='SELECT'?this.querySelector('option')?.value||'':'');}set value(value){this._value=String(value);}get open(){return this.hasAttribute('open');}set open(value){value?this.setAttribute('open',''):this.removeAttribute('open');}
  get isConnected(){return this===document.body||document.body.contains(this);}get childElementCount(){return this.children.filter(node=>node.nodeType===1).length;}get textContent(){return this.children.map(node=>node.nodeType===3?node.text:node.textContent).join('');}set textContent(value){for(const child of this.children)child.parentElement=null;this.children=[{nodeType:3,text:String(value),parentElement:this}];}
  get innerHTML(){return this._html||'';}set innerHTML(value){this._html=String(value);this.replaceChildren();parse(this,this._html);}
  setAttribute(name,value){this.attributes.set(name,String(value));}getAttribute(name){return this.attributes.get(name)??null;}hasAttribute(name){return this.attributes.has(name);}removeAttribute(name){this.attributes.delete(name);}
  append(...nodes){for(let node of nodes){if(typeof node==='string')node={nodeType:3,text:node};node.remove?.();node.parentElement=this;this.children.push(node);}}insertBefore(node,before){node.remove?.();const index=this.children.indexOf(before);node.parentElement=this;if(index<0)this.children.push(node);else this.children.splice(index,0,node);}
  replaceChildren(...nodes){for(const child of this.children)child.parentElement=null;this.children=[];this.append(...nodes);}remove(){if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(node=>node!==this);this.parentElement=null;}
  insertAdjacentElement(where,node){if(where!=='afterend')throw Error('Unsupported test insertion');const parent=this.parentElement,index=parent.children.indexOf(this);node.parentElement=parent;parent.children.splice(index+1,0,node);}
  contains(node){return node===this||this.children.some(child=>child.nodeType===1&&child.contains(node));}
  matches(selector){return selector.split(',').some(part=>{part=part.trim();for(const negative of part.matchAll(/:not\(([^()]*)\)/g))if(this.matches(negative[1]))return false;part=part.replace(/:not\([^()]*\)/g,'');const tag=part.match(/^[a-z][\w-]*/i)?.[0];if(tag&&this.tagName!==tag.toUpperCase())return false;for(const id of part.matchAll(/#([\w-]+)/g))if(this.id!==id[1])return false;for(const name of part.matchAll(/\.([\w-]+)/g))if(!this.classList.contains(name[1]))return false;for(const match of part.matchAll(/\[([\w-]+)(?:=["']?([^\]"']+)["']?)?\]/g))if(!this.hasAttribute(match[1])||match[2]!==undefined&&this.getAttribute(match[1])!==match[2])return false;if(part.includes(':checked')&&!this.checked)return false;if(part.includes(':hover')&&!this.hover)return false;if(part.includes(':modal')&&!this.modal)return false;return true;});}
  closest(selector){for(let node=this;node;node=node.parentElement)if(node.matches(selector))return node;return null;}
  querySelectorAll(selector){const found=[];for(const child of this.children){if(child.nodeType!==1)continue;for(const part of selector.split(',')){const segments=part.trim().split(/\s+/);if(child.matches(segments.at(-1))){let parent=child.parentElement,index=segments.length-2;while(index>=0&&parent){if(parent.matches(segments[index]))index--;parent=parent.parentElement;}if(index<0){found.push(child);break;}}}found.push(...child.querySelectorAll(selector));}return [...new Set(found)];}
  querySelector(selector){if(selector===':scope > summary')return this.children.find(node=>node.tagName==='SUMMARY')||null;return this.querySelectorAll(selector)[0]||null;}
  addEventListener(type,fn,options){const list=this.listeners.get(type)||[];list.push({fn,capture:options===true||options?.capture});this.listeners.set(type,list);}removeEventListener(type,fn){this.listeners.set(type,(this.listeners.get(type)||[]).filter(item=>item.fn!==fn));}
  dispatch(type,extra={}){const event={type,target:this,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},...extra},chain=[];for(let node=this;node;node=node.parentElement)chain.push(node);
   for(const node of [...chain].reverse())for(const item of node.listeners.get(type)||[])if(item.capture)item.fn(event);
   for(const node of chain){if(typeof node['on'+type]==='function')event.returned=node['on'+type](event);for(const item of node.listeners.get(type)||[])if(!item.capture)item.fn(event);}return event;
  }
  click(){return this.disabled?null:this.dispatch('click');}focus(){if(!this.disabled&&!this.closest('[hidden]')&&document.activeElement!==this){const previous=document.activeElement;previous?.dispatch?.('focusout',{relatedTarget:this});document.activeElement=this;this.dispatch('focusin',{relatedTarget:previous});}}pause(){this.pauses++;}load(){}showModal(){this.modalCalls=(this.modalCalls||0)+1;this.modal=true;this.open=true;this.querySelector('button:not([disabled])')?.focus();}show(){this.modal=false;this.open=true;}close(){if(this.open){this.open=false;this.modal=false;this.dispatch('close');}}
  escape(){const event=this.dispatch('cancel');if(!event.defaultPrevented)this.close();return event;}
  get elements(){const controls=this.querySelectorAll('input,select,textarea,button');for(const control of controls)if(control.name)controls[control.name]=control;return controls;}
  get willValidate(){return ['INPUT','SELECT','TEXTAREA'].includes(this.tagName)&&!this.disabled&&!['hidden','button','submit'].includes(this.type);}
  get validity(){if(this._validity)return this._validity;let valid=true;if(this.required){if(this.type==='file')valid=!!this.files.length;else if(this.type==='checkbox')valid=this.checked;else if(this.type==='radio')valid=this.closest('form').querySelectorAll('input').some(input=>input.name===this.name&&input.checked);else valid=!!this.value;}return {valid};}
  get validationMessage(){return this.validity.valid?'':'請填寫此欄位。';}checkValidity(){this.checks=(this.checks||0)+1;let valid=true;for(const control of this.elements){if(control.willValidate&&!control.validity.valid){valid=false;control.dispatch('invalid');}}return valid;}reportValidity(){this.reports=(this.reports||0)+1;return this.checkValidity();}
  reset(){this.dispatch('reset');for(const control of this.elements){control._value=undefined;control._checked=undefined;control.files=[];}}
 }
 function parse(parent,html){const stack=[parent],voidTags=new Set(['INPUT','IMG','BR','HR','META','LINK','SOURCE']);for(const token of html.matchAll(/<!--[\s\S]*?-->|<[^>]+>|[^<]+/g)){const value=token[0];if(value.startsWith('<!--')||value.startsWith('<!'))continue;if(value.startsWith('</')){if(stack.length>1)stack.pop();continue;}if(value.startsWith('<')){const tag=value.match(/^<([\w-]+)/)?.[1];if(!tag)continue;const node=new Element(tag);for(const match of value.slice(tag.length+1).matchAll(/([^\s=/>]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+)))?/g))node.setAttribute(match[1],decode(match[2]??match[3]??match[4]??''));stack.at(-1).append(node);if(!voidTags.has(node.tagName)&&!value.endsWith('/>'))stack.push(node);}else stack.at(-1).append(decode(value));}}
 const body=new Element('body');document={body,activeElement:body,visibilityState:'visible',createElement:tag=>new Element(tag),getElementById:id=>body.querySelector('#'+id),querySelector:selector=>body.querySelector(selector),querySelectorAll:selector=>body.querySelectorAll(selector),addEventListener:(...args)=>body.addEventListener(...args),removeEventListener:(...args)=>body.removeEventListener(...args)};
 if(html)parse(body,html.match(/<body[^>]*>([\s\S]*)<\/body>/i)?.[1]||html);
 class MutationObserver{constructor(callback){this.callback=callback;this.connected=false;observers.push(this);}observe(){this.connected=true;}disconnect(){this.connected=false;}}
 return {document,Element,MutationObserver,observers,mutate(){for(const observer of observers)if(observer.connected)observer.callback([]);},node:id=>document.getElementById(id)};
}
module.exports={dom};
